-- TB3D 1.1.0.0.0.4   added bolt option in modders script , added TB3D_Update to replace, gun explode option,
-- zaton to red forest, dmx135, using dmx blood instead of amk, fixed soul cube, tp news removed, chg redeffect call,
-- drop item to inv, dose_asses removed, frogs and cooling moved to services, dav update 16Apr14, hud, gen to dm,
-- hosp to agro, tip_id, send_tip_id optimization, 97104, 98975,6, _ds_to_poli target, sticks,
-- changed "exo_mil_exoskeleton_addrs" to "exo_mil_exoskeleton_addx" aleks1970, npp2 to x14, eprip to prip, removed blowout_wave,
-- switched targets; hosp and red forest to tunnels, jup to eprip, shadows_cube_prov_check, allow cube quest in collector,
-- rsch_to_wait, 99043, hud_show_enemy
function my_ver() return "1.1.0.0.0.4" end
--[[- max.script, centralized create_level_changer, uncommtd line 48 (11/21/11)------------
 File         : dmx_mod.script
 Description  : The main script fashion, contain quest function, spawn, etc.
 Copyright    : DMX MOD
 Author       : Shadows & Co
--]]-----------------------------------------------------------------------------------

function dmx_use(obj)
	if TB3D_Modders.Global_Debug == true then TB3D_Services.info_alert("dmx mod: use") end
	use_sound_items(obj)
	use_radiation_detector(obj)
	use_silencers_box(obj)
	use_bolt_box(obj)
	use_item_ammo_flame_transfer(obj)
	if TB3D_Modders.Global_Debug == true then TB3D_Services.info_alert("dmx mod: use done") end
end

local last_health = 0
function dmx_update(delta)
	--TB3D_Services.packet_alert("dmx mod: update")
	if last_health > db.actor.health + 0.008 then
		dmx_hit_callback(last_health - db.actor.health, db.actor:who_hit_name(), db.actor:who_hit_section_name())
	end
	last_health = db.actor.health
	--TB3D_Services.packet_alert("dmx mod: update done")
end

function dmx_hit_callback(amount, who_name, who_section_name)
	if who_section_name == "zone_mine_field" or who_section_name == "zone_mine_electra" then
		amk.start_timer("remove_mine_timer", 2, who_name)
	end
end

function dmx_net_destroy()
    bolt_ending.net_destroy()
end

------------------------------------------------------------------------------------------------------------------------
-- Spawn CHARACTERS
-- Suslov on the Marshes
function syslov_spawn()
	local obj = alife():story_object(97120)
	if not obj then
		obj = alife():create("syslov",vector():set(-178.59976196289,0.929643034935,-320.59954833984),51819,3365) 
		local tbl = amk.read_stalker_params(obj)
		tbl.sid = 97120
		amk.write_stalker_params(tbl, obj)
		--TB3D_Services.info_alert("DMX mod: syslov spawn")
	end
end

-- The battalion commander at the cordon
function kombat_spawn() 
	alife():create("kombat",vector():set(183.67390441895,1.8403881788254,360.74264526367),484425,230) 
end

------------------------------------------------------------------------------------------------------------------------
-- MARK CHARACTER
-- Setting tags, 110007 updated - aleks1970
function mapspot_npc(sid,id)
	if sid and id then
		if sid==003 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")				-- Sidorovich
		elseif sid==032 then level.map_add_object_spot(id, "military_trader_npc_mapspot", "map_mil_trader")		-- Major Kuznetsov
		elseif sid==500 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")			-- Bartender
		elseif sid==507 then level.map_add_object_spot(id, "boss_npc_mapspot", "map_cmdr_debt")
		elseif sid==707 then level.map_add_object_spot(id, "boss_npc_mapspot", "map_cmdr_freedom")
		elseif sid==734 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")			-- Curmudgeon
		elseif sid==902 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")			-- Sugars
		elseif sid==4000 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")			-- pred barman
		elseif sid==4001 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")			-- pred trader
		elseif sid==4002 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")			-- kras trader
		elseif sid==4003 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")			-- dd trader
		elseif sid==4004 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")			-- l02_stalker
		elseif sid==9501 then level.map_add_object_spot(id, "repair_npc_mapspot", "map_technician")		-- Syak
		elseif sid==9504 then level.map_add_object_spot(id, "repair_npc_mapspot", "map_technician")		-- Lanky
		elseif sid==9506 then level.map_add_object_spot(id, "military_trader_npc_mapspot", "map_mil_trader")	-- Sherstuk
		elseif sid==9903 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")			-- Adrenaline
		elseif sid==14000 then level.map_add_object_spot(id, "boss_npc_mapspot", "map_cmdr_clearsky")
		elseif sid==97120 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")		-- Suslov
		elseif sid==97123 then level.map_add_object_spot(id, "repair_npc_mapspot", "map_technician") 	-- Basil 
		elseif sid==97125 then level.map_add_object_spot(id, "trader_npc_mapspot", "map_trader")		-- tweed
		elseif sid==97126 then level.map_add_object_spot(id, "repair_npc_mapspot", "map_technician")	-- karina
		elseif sid==97128 then level.map_add_object_spot(id, "repair_npc_mapspot", "map_technician")	-- tractorist
		end
	end
end

-- Removing labels is offline, 110007 updated - aleks1970
function remove_mapspot_npc(sid,id)
	if sid and id then
		if sid==003 then level.map_remove_object_spot(id, "trader_npc_mapspot")			-- Sidorovich
		elseif sid==032 then level.map_remove_object_spot(id, "military_trader_npc_mapspot")	-- Major Kuznetsov
		elseif sid==500 then level.map_remove_object_spot(id, "trader_npc_mapspot")		-- Bartender
		elseif sid==507 then level.map_remove_object_spot(id, "boss_npc_mapspot")		-- Voronin
		elseif sid==707 then level.map_remove_object_spot(id, "boss_npc_mapspot")		-- Lukas
		elseif sid==734 then level.map_remove_object_spot(id, "trader_npc_mapspot")		-- Curmudgeon
		elseif sid==902 then level.map_remove_object_spot(id, "trader_npc_mapspot")		-- Sugars
		elseif sid==4000 then level.map_remove_object_spot(id, "trader_npc_mapspot")	-- pred barman
		elseif sid==4001 then level.map_remove_object_spot(id, "trader_npc_mapspot")	-- pred trader
		elseif sid==4002 then level.map_remove_object_spot(id, "trader_npc_mapspot")	-- kras trader
		elseif sid==4003 then level.map_remove_object_spot(id, "trader_npc_mapspot")	-- dd trader
		elseif sid==4004 then level.map_remove_object_spot(id, "trader_npc_mapspot")	-- l02_stalker
		elseif sid==9501 then level.map_remove_object_spot(id, "repair_npc_mapspot")	-- Syak
		elseif sid==9504 then level.map_remove_object_spot(id, "repair_npc_mapspot")	-- Lanky
		elseif sid==9506 then level.map_remove_object_spot(id, "military_trader_npc_mapspot")	-- Sherstuk
		elseif sid==9903 then level.map_remove_object_spot(id, "trader_npc_mapspot")	-- Adrenaline
		elseif sid==14000 then level.map_remove_object_spot(id, "boss_npc_mapspot")		-- Sviblov
		elseif sid==97120 then level.map_remove_object_spot(id, "trader_npc_mapspot")	-- Suslov
		elseif sid==97123 then level.map_remove_object_spot(id, "repair_npc_mapspot")	-- Basil 
		elseif sid==97125 then level.map_remove_object_spot(id, "trader_npc_mapspot")	-- tweed
		elseif sid==97126 then level.map_remove_object_spot(id, "repair_npc_mapspot")	-- karina
		elseif sid==97128 then level.map_remove_object_spot(id, "repair_npc_mapspot")	-- tractorist
		end
	end
end
------------------------------------------------------------------------------------------------------------------------
-- ARTICLES ABOUT LOCATIONS
-- check the availability of money for papers
function syslov_moral_many(actor,npc)
	return actor:money() > 1500
end

-- give away money for the articles
function syslov_moral_many_dal(t1,t2)
	local npc=t1
	if npc:id()==db.actor:id() then npc=t2 end
	dialogs.relocate_money(npc,1500,"out")
end
------------------------------------------------------------------------------------------------------------------------
-- SKAT UPGRADE
function spawn_upgrades()																	--109974
	alife():create("doc_1",vector():set(-198.597,4.488,168.971),25633,1363)
	alife():create("art_acumm",vector():set(-33.133,3.548,-64.111),198,1960)
	alife():create("doc_8",vector():set(-33.133,3.548,-64.111),198,1960)
	alife():create("art_acumm",vector():set(-33.133,3.548,-64.111),198,1960)
	alife():create("doc_10",vector():set(-89.387,-2.457,-25.271),19105,2875)
	alife():create("art_acumm",vector():set(-89.387,-2.457,-25.271),19105,2875)
end

-- check availability SCAT-15 with 3 upgrades
function syslov_skat15_have()
--TB3D_Services.packet_alert("syslov skat have")
	if TB3D_Services.is_collector(900) then
		return true
	else
		return amk_utils.inventory_search("exo_mil_exoskeleton_addx",1) ~= false	-- aleks1970	--109954
	end
end

-- verify the presence of an artifact drop soul
function skat15up_art_have()
--TB3D_Services.packet_alert("syslov skat have")
	if TB3D_Services.is_collector(901) then
		return true
	else
		return amk_utils.inventory_search("af_spirit_1",1) ~= false
	end
end

-- check the availability of money 
function skat15up_moral_many(actor,npc)
	return actor:money() > 45000
end

-- give away money
function skat15up_moral_many_dal(t1,t2)
	local npc=t1
	if npc:id()==db.actor:id() then npc=t2 end
	dialogs.relocate_money(npc,45000,"out")
end

-- give up the artifact and give HS apgreyder
function upgrader_berem_otdal_art(first_speaker, second_speaker)
	sak.out_item_namber("af_spirit_1",1)
	dialogs.relocate_item_section(second_speaker, "dmx_skat15_upgrade","in")
end
------------------------------------------------------------------------------------------------------------------------
-- Food items have BARTER COLD
-- Cigarettes
-- verify the presence of two packs of Dream
function holod_dmx_food_mechta_prov()
	return amk_utils.inventory_search("mechta",2) ~= false
end

-- give away two packs of cigarettes and get the salt
function mechta_otdal_pol_col(first_speaker, second_speaker)
	sak.out_item_namber("mechta",2)
	dialogs.relocate_item_section(second_speaker, "sigaret","in")
end

-- verify the presence of 3 cigars
function holod_dmx_food_sigara_prov()
	return amk_utils.inventory_search("cigara",3) ~= false
end

-- give up the cigars and cigarettes get salt
function sigara_otdal_pol_col(first_speaker, second_speaker)
	sak.out_item_namber("cigara",3)
	dialogs.relocate_item_section(second_speaker, "sigaret","in")
end

-- VODKA
-- verify the presence of two bubbles of the Absolute
function holod_absolut_prov()
	return amk_utils.inventory_search("absolut_vodka",2) ~= false
end

-- give away two bubble and get Kazakov
function absolut_otdal_pol_kaz(first_speaker, second_speaker)
	sak.out_item_namber("absolut_vodka",2)
	dialogs.relocate_item_section(second_speaker, "vodka","in")
end

-- verify the presence of a bubble Smirnoff
function holod_smirnoff_prov()
	return amk_utils.inventory_search("smirnoff_vodka",1) ~= false
end

-- verify the presence of one hundred rubles
function holod_dialog_many_food_prov(actor,npc)
	return actor:money() > 100
end

-- Smirnoff give up and get Kazakov
function smirnoff_otdal_pol_kaz(first_speaker, second_speaker)
	sak.out_item_namber("smirnoff_vodka",1)
	dialogs.relocate_item_section(second_speaker, "vodka","in")
end

-- give away a hundred rubles
function holod_dialog_many_food_otdal(t1,t2)
	local npc=t1
	if npc:id()==db.actor:id() then npc=t2 end
	dialogs.relocate_money(npc,100,"out")
end

-- SAUSAGE
-- verify the existence of two poles of the Doctoral
function holod_kolbasadmx_prov()
	return amk_utils.inventory_search("kolbasadmx",2) ~= false
end

-- give up their and get a regular sausage
function kolbasa_dmx_dal_pol_kolba(first_speaker, second_speaker)
	sak.out_item_namber("kolbasadmx",2)
	dialogs.relocate_item_section(second_speaker, "kolbasa","in")
end

-- check the availability of beer Chernigov
function holod_chernigov_prov()
	return amk_utils.inventory_search("pivo",1) ~= false
end

-- give up beer and get a regular sausage
function chernigov_otdal_pol_kol(first_speaker, second_speaker)
	sak.out_item_namber("pivo",1)
	dialogs.relocate_item_section(second_speaker, "kolbasa","in")
end
------------------------------------------------------------------------------------------------------------------------
-- STARTING DIALOGUE We COLD
-- Nemiroff vodka give HS
function nemiroff_vodka_berem(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "nemiroff_vodka","in")
end

-- YY give vodka Absolut
function absolut_vodka_berem(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "absolut_vodka","in")
end

-- Smirnoff vodka give HS
function smirnoff_vodka_berem(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "smirnoff_vodka","in")
end
------------------------------------------------------------------------------------------------------------------------
-- SOUL CUBE
-- check junk
function spawn_sc_outfit()
	if TB3D_Services.is_collector(902) == false then
		alife():create("merc_scientific_outfit",vector():set(-349.451,-12.208,379.170),7167,1847) -- Military Warehouses-Mercenary base - bus1 --aleks1970
		--alife():create("merc_scientific_outfit",vector():set(-357.896,-12.824,391.227),3721,1848) -- Military Warehouses-Mercenary base - bus2_1
		--alife():create("merc_scientific_outfit",vector():set(-356.305,-13.416,391.708),4177,1848) -- Military Warehouses-Mercenary base - bus2_2
		--treasure_manager.get_treasure_manager():give_treasure("mil_secret_0029") -- Military Warehouses - blue box
	end
end

function shadows_cube_prov()
	local rslt = false														--109991
	--if TB3D_Services.is_collector(902) == false then
	if amk_utils.inventory_search("nemiroff_vodka",5) ~= false and
		amk_utils.inventory_search("irp-b",2) ~= false and
		amk_utils.inventory_search("yantar",3) ~= false and
		amk_utils.inventory_search("nuts",5) ~= false and
		amk_utils.inventory_search("pivo",3) ~= false and
		amk_utils.inventory_search("energy_ad_rush",5) ~= false and
		amk_utils.inventory_search("merc_scientific_outfit",1) ~= false and
		amk_utils.inventory_search("wpn_rpd",1) ~= false then
		rslt = true
	end
	--TB3D_Services.packet_alert("cube prov["..utils.to_str(rslt).."]")
	return rslt
end
function shadows_cube_prov_check()
	return has_alife_info("shadows_cube_prov_check")
end

-- give up junk for Cube
function shadows_cube_otdal(first_speaker, second_speaker)
	sak.out_item_namber("nemiroff_vodka",5)
	sak.out_item_namber("irp-b",2)
	sak.out_item_namber("yantar",3)
	sak.out_item_namber("nuts",5)
	sak.out_item_namber("pivo",3)
	sak.out_item_namber("energy_ad_rush",5)
	sak.out_item_namber("merc_scientific_outfit",1)
	sak.out_item_namber("wpn_rpd",1)
end

-- YY give money if he does not want to find the Cube
function shadows_cube_many_25000(t1,t2)
	local npc=t1
	if npc:id()==db.actor:id() then npc=t2 end
	dialogs.relocate_money(npc,25000,"in")
end

-- spawn Shadows
function shadows_spawn()		--109995
	--if TB3D_Services.is_collector(903) == false then
		local obj = alife():create("shadows",vector():set(-279.516,0.972,35.288),7088,3351)
		local tbl = amk.read_stalker_params(obj)
		tbl.sid = 97121
		amk.write_stalker_params(tbl, obj)
		TB3D_Triggers.eprip_spawns()
	--end
end

-- Shadows - enemy
function shadows_enemy(first_speaker, second_speaker)
	second_speaker:set_relation(game_object.enemy, first_speaker)
	--TB3D_hit_styles.hit_companion(second_speaker, first_speaker, 100.0)
	TB3D_Services.change_reputation(db.actor, -40)
end

-- give a fake cube
function fake_cube_dal(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "fake_cube","in")
end

-- pick up the fake Cube
function fake_cube_otdal(first_speaker, second_speaker)
	sak.out_item_namber("fake_cube",1)
end

-- revive some of Pripyat
function cube_pripyat_spawn() 		--109995
	--if TB3D_Services.is_collector(904) == false then
		alife():create("m_controller_normal",vector():set(287.109,-0.371,266.864),474028,3769)
		alife():create("fracture_swamp",vector():set(287.109,-0.371,266.864),474028,3769)
		alife():create("fracture_master",vector():set(132.561,-0.238,216.951),359942,3769)
		alife():create("fracture_karlik",vector():set(149.252,-0.052,211.248),378888,3769)
		alife():create("cop_prip_treasure_cube",vector():set(131.672,29.114,240.428),359193,3769)
		alife():create("item_doc_x8",vector():set(136.492,29.332,239.402),365077,3769)
		alife():create("dmx_military_map",vector():set(132.064,28.907,235.955),359964,3769)
		alife():create("cop_kvartira_music",vector():set(131.227,30.029,236.661),358426,3769)
		alife():create("wpn_protecta_col",vector():set(6.984,5.361,269.103),205983,3760)
		alife():create("wpn_pkm_tactic",vector():set(35.739,-2.883,-58.234),245226,3766)
		alife():create("bloodsucker_strong",vector():set(-49.974,-0.507,-71.471),139443,3759)
		alife():create("m_poltergeist_normal_tele",vector():set(-62.949,4.224,-94.039),126481,3759)
		alife():create("pseudodog_strong",vector():set(-160.217,-0.506,-252.603),47519,3748)
		alife():create("pseudodog_strong",vector():set(-146.134,-0.507,-271.362),56480,3751)
		alife():create("af_babka_3",vector():set(-77.910,25.093,87.284),112218,3755)
		alife():create("glow_stick_blue",vector():set(133.024,28.908,239.756),364239,3769)
		alife():create("glow_stick_blue",vector():set(133.024,28.908,239.756),364239,3769)
		alife():create("glow_stick_blue",vector():set(133.024,28.908,239.756),364239,3769)
		--monolith_kbo_spawn()
	--end
end

function monolith_kbo_spawn()			--109995
	--if TB3D_Services.is_collector(905) == false then
		alife():create("kbo_monolit1",vector():set(-42.540,0.400,81.989),146270,3755)
		alife():create("kbo_monolit3",vector():set(-43.463,0.401,110.734),145710,3755)
		alife():create("kbo_monolit4",vector():set(-82.692,0.399,96.015),107366,3754)
		alife():create("kbo_monolit6",vector():set(-41.787,4.500,84.167),147056,3755)
		alife():create("kbo_monolit7",vector():set(-42.601,4.500,105.050),146450,3755)
		alife():create("kbo_monolit8",vector():set(-63.459,4.497,86.316),125948,3754)
		alife():create("kbo_monolit10",vector():set(-82.731,4.500,83.071),107276,3754)
		alife():create("kbo_monolit12",vector():set(-76.615,8.600,74.130),113517,3754)
		alife():create("kbo_monolit13",vector():set(-45.919,8.602,94.610),143029,3755)
		alife():create("kbo_monolit15",vector():set(-46.727,12.700,110.448),142386,3755)
		alife():create("kbo_monolit17",vector():set(-61.830,16.801,104.961),128245,3755)
		alife():create("kbo_monolit1",vector():set(-42.900,20.900,115.329),146501,3755)
	--end
end

-- settlement facilities
function pripyat_base_spawn()
    local obj = alife():create("mudri",vector():set(144.298,-0.096,-192.662),375712,3765)
    local tbl = amk.read_stalker_params(obj)
    tbl.sid = 97122
    amk.write_stalker_params(tbl, obj)
	alife():create("grozn",vector():set(136.787,4.905,-191.870),364574,3765)
	alife():create("alex",vector():set(130.497,-0.297,-182.324),356345,3765)
	alife():create("cop_base_music",vector():set(156.453,0.493,-179.119),384599,3765)
	alife():create("medkit_elite",vector():set(143.582,0.822,-185.929),373572,3765)
	alife():create("ammo_5.56x45_ap",vector():set(153.933,0.493,-178.611),383288,3765)
	alife():create("ammo_5.56x45_ap",vector():set(153.933,0.493,-178.611),383288,3765)
	alife():create("ammo_5.45x39_ap",vector():set(146.500,0.429,-173.041),375743,3765)
	alife():create("ammo_5.45x39_ap",vector():set(146.500,0.429,-173.041),375743,3765)
	alife():create("ammo_12x70_buck",vector():set(149.508,4.901,-172.097),378562,3765)
	alife():create("ammo_12x70_buck",vector():set(149.508,4.901,-172.097),378562,3765)
end

-- employ the vodka
function actor_drinking_vodka()
    local oItem = db.actor:object("vodka") or db.actor:object("absolut_vodka") or db.actor:object("nemiroff_vodka") or db.actor:object("smirnoff_vodka")
	if oItem then
		--TB3D_Services.packet_alert("dmx mod: actor_drinking_vodka["..oItem:name().."]")
	    db.actor:eat(oItem)
	else
		local sobj = amk.spawn_item_in_inv("vodka")
        level.client_spawn_manager():add(sobj.id,0,spawn_vodka_callback,true)
	end
end

function spawn_vodka_callback(arg,id,item)								--109982
    local oItem = db.actor:object("vodka")
	if oItem then
		--TB3D_Services.packet_alert("dmx mod: spawn_vodka_callback["..oItem:name().."]")
		db.actor:eat(oItem)
		amk.remove_item(oItem)
	end
end

-- a couple of monsters in quest map search Pripyat
function monsters_quest_spawn() 			--109995
	--if TB3D_Services.is_collector(906) == false then
		alife():create("zombie_ghost",vector():set(184.295,0.674,47.489),414274,3770)
		alife():create("bloodsucker_strong",vector():set(199.468,2.501,-8.367),427539,3768)
		alife():create("zombie_ghost",vector():set(234.454,0.547,22.189),452741,3768)
		alife():create("zombie_swamp",vector():set(234.454,0.547,22.189),452741,3768)
		alife():create("dmx_pripyat_map",vector():set(205.422,5.444,-25.960),433226,3768)
	--end
end

-- pick up a map of Pripyat
function dmx_pripyat_map_have()			--109995
	--if TB3D_Services.is_collector(907) then
		--return true
	--else
		return amk_utils.inventory_search("dmx_pripyat_map",1) ~= false
	--end
end

-- give a transition in X-8
function next_labx8()			--109995
	--if TB3D_Services.is_collector(908) == false then
		news_manager.amk_send_tip_id("labx8_private1", "unknown_private", 10, 20, "actor_sms")
		news_manager.amk_send_tip_id("labx8_private2", "shadows_private", 30, 20)
		amk.save_variable("torch_state", 1)		--109970
		labx8_cube_spawn()						--109970
		labx8_spawn_trup_ps()					--109970
		--pripyat_cop_to_lab_x8()				--109998, use elevator button
		alife():create("werewolf",vector():set(295.981,-0.193,119.076),477049,3770)	--hospital roof
		TB3D_Triggers.wolf_howls()
	--end
end

-- population of laboratory X-8
function labx8_cube_spawn()			--109995
	--if TB3D_Services.is_collector(910) == false then
		alife():create("lab_x8_treasure",vector():set(-43.313,-20.517,72.710),6747,3850)
		alife():create("burer_strong",vector():set(-83.113,-15.939,108.460),2780,3837)
		alife():create("snork_strong",vector():set(-98.249,-18.130,86.008),919,3838)
		alife():create("burer_strong",vector():set(-86.267,-20.021,82.081),2259,3838)
		alife():create("tushkano_normal",vector():set(-105.451,-32.377,77.411),453,3830)
		alife():create("tushkano_normal",vector():set(-108.119,-32.401,85.121),359,3832)
		alife():create("tushkano_normal",vector():set(-105.451,-32.377,77.411),453,3830)
		alife():create("tushkano_normal",vector():set(-108.119,-32.401,85.121),359,3832)
		alife():create("antirad",vector():set(-110.974,-31.502,90.253),259,3832)
		alife():create("ammo_5.45x39_izomorf",vector():set(-87.835,-31.175,80.502),1942,3844)
		alife():create("ammo_5.45x39_izomorf",vector():set(-87.835,-31.175,80.502),1942,3844)
		alife():create("rat_normal",vector():set(-74.285,-36.714,85.643),4481,3844)
		alife():create("item_doc_x8_2",vector():set(-58.532,-16.653,100.163),6181,3840)
		alife():create("zone_grost",vector():set(-56.302,-22.017,87.185),6352,3840)
		alife():create("tarakan_normal",vector():set(-76.451,-23.858,61.195),3957,3845)
		alife():create("af_armor_4",vector():set(-76.451,-23.858,61.195),3957,3845)
		alife():create("m_poltergeist_normal_tele",vector():set(-78.942,-24.323,87.381),3412,3839)
		alife():create("snork_strong",vector():set(-78.755,-28.446,72.607),3362,3840)
		alife():create("rat_normal",vector():set(-72.487,-20.166,64.236),4730,3847)
		alife():create("ammo_og-7b",vector():set(-75.058,-10.367,56.259),4219,3843)
		alife():create("ammo_og-7b",vector():set(-75.058,-10.367,56.259),4219,3843)
		alife():create("wpn_rpg7_m1",vector():set(-75.058,-10.367,56.259),4219,3843)
		alife():create("rat_normal",vector():set(-78.422,-16.005,71.539),3507,3838)
		alife():create("rat_normal",vector():set(-78.422,-16.005,71.539),3507,3838)
		alife():create("snork_strong",vector():set(-90.291,-15.977,78.629),1634,3831)
		alife():create("burer_strong",vector():set(-76.541,-28.470,64.181),3970,3842)
		alife():create("energy_stalker",vector():set(-56.601,-15.558,103.241),6292,3840)
		alife():create("glow_stick_blue",vector():set(-54.697,-20.974,91.194),6433,3840)
		alife():create("glow_stick_blue",vector():set(-54.697,-20.974,91.194),6433,3840)
		alife():create("glow_stick_red",vector():set(-54.697,-20.974,91.194),6433,3840)
		alife():create("glow_stick_red",vector():set(-54.697,-20.974,91.194),6433,3840)
	--end
end

-- spawn dead scientist
function labx8_spawn_trup_ps()			--109995
	--if TB3D_Services.is_collector(911) == false then
		local obj = alife():create("pavel_sergeevich",vector():set(-56.302,-22.017,87.185),6352,3840)
		local tbl = amk.read_stalker_params(obj)
		tbl.sid = 97124
		tbl.health = 0
		tbl.updhealth = 0
		amk.write_stalker_params(tbl, obj)
	--end
end

-- check the presence of Cube in the Shadow backpack
function wpn_soulcube_have()			--109995
	--if TB3D_Services.is_collector(912) then
		--return true
	--else
		return amk_utils.inventory_search("wpn_soulcube",1) ~= false
	--end
end

-- timer and the appearance of a ghost controller
function labx8_cube_take()			--109995
	--if TB3D_Services.is_collector(913) == false then
		TB3D_Triggers.spawn_alife("werewolf",234.454,0.547,22.189,452741,3768, 2)
		TB3D_Triggers.wolf_howls()
		--local snd_obj = xr_sound.get_safe_sound_object( [[monsters\\werewolf\\howls_01]] )
		--if snd_obj then snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0) end
		amk.start_timer("ghost_timer",4,"")
	--end
end

-- whether the AU card in his backpack
function dmx_military_map_have()			--109995
	--if TB3D_Services.is_collector(914) then
		--return true
	--else
		return amk_utils.inventory_search("dmx_military_map",1) ~= false
	--end
end

-- whether there is a diary in my backpack
function item_doc_x8_have()			--109995
	--if TB3D_Services.is_collector(915) then
		--return true
	--else
		return amk_utils.inventory_search("item_doc_x8",1) ~= false
	--end
end

-- whether there is documentation of X-8 in a backpack
function item_doc_x8_2_have()			--109995
	--if TB3D_Services.is_collector(916) then
		--return true
	--else
		return amk_utils.inventory_search("item_doc_x8_2",1) ~= false
	--end
end

-- give up a map of Pripyat
function give_dmx_pripyat_map(first_speaker, second_speaker)
    sak.out_item_namber("dmx_pripyat_map", 1)
end

-- give away AU map
function give_dmx_military_map(first_speaker, second_speaker)
    sak.out_item_namber("dmx_military_map", 1)
end

-- surrender of documents X-8
function give_item_doc_x8_2(first_speaker, second_speaker)
    sak.out_item_namber("item_doc_x8_2", 1)
end

-- give up diary
function give_item_doc_x8(first_speaker, second_speaker)
    sak.out_item_namber("item_doc_x8", 1)
end

-- YY give 500 rubles for each item is
function dal_many_500(t1,t2)
	local npc=t1
	if npc:id()==db.actor:id() then npc=t2 end
	dialogs.relocate_money(npc,500,"in")
end
------------------------------------------------------------------------------------------------------------------------
-- TOOLS FOR SAGE
-- Tools and spawns controller
function instruments_spawn() 			--109995
	--if TB3D_Services.is_collector(917) == false then
		alife():create("mudrec_instruments",vector():set(-188.578,0.582,-209.861),29111,3748)
		alife():create("m_controller_normal",vector():set(-182.600,-0.283,-205.787),32993,3748)
	--end
end

-- check whether the tools in his backpack
function cop_pripyat_instruments_have()
    return amk_utils.inventory_search("mudrec_instruments",1) ~= false
end

-- Sage surrender tools
function give_cop_pripyat_instruments(first_speaker, second_speaker)
    sak.out_item_namber("mudrec_instruments", 1)
	alife():create("werewolf",vector():set(-182.600,-0.283,-205.787),32993,3748)
	TB3D_Triggers.wolf_howls()
end
------------------------------------------------------------------------------------------------------------------------
-- The second way to get to the checkpoint
local outfit_propusk_tabl = {["specops_outfit"]=true, ["military_outfit"]=true, ["militaryspec_outfit"]=true, ["soldier_outfit"]=true, ["outfit_soldier_m1"]=true, ["exo_mil_exoskeleton"]=true}
function outfit_propusk(outfit)
    if outfit then
        local name = outfit:section()
        for k,v in pairs(outfit_propusk_tabl) do
            if string.find(name,k) then return true end
        end
    end
end

function actor_blockpost_propusk()		--TB3D   DMX135
	if TB3D_Services.is_collector(918) == false then
		if dmx_cars.inside_section_car() == "vehicle_uaz469_uniq" and level.name() == "l01_escape" and not has_alife_info("actor_uaz_input_info") then
			local outfit = db.actor:get_current_outfit()
			if outfit and string.find(outfit:section(), "specops_outfit") then
				amk.start_timer("blockpost_propusk_timer", 120, db.actor:character_community())
				amk.start_timer("actor_set_military_timer", 10)
				amk.send_tip("propusk_msg", "Sidorovich", 5, 20, "trader")
				TB3D_Services.give_info("actor_propusk_info")
				TB3D_Services.give_info("actor_uaz_input_info")
			end
		end
	end
end

-- check for beryl
function specops_outfit_have()
	if TB3D_Services.is_collector(919) then
		return true
	else
		return amk_utils.inventory_search("specops_outfit",1) ~= false
	end
end

-- spawn near the farm machinery
function blockpost_quest_spawn()
	if TB3D_Services.is_collector(920) == false then
		alife():create("vehicle_uaz_fsb",vector():set(1.253,2.480,72.038),278071,89)
	end
end

-- give a license and car keys
function give_certificate_and_key(first_speaker, second_speaker)
    dialogs.relocate_item_section(second_speaker, "item_certificate","in")
	dialogs.relocate_item_section(second_speaker, "car_key","in")
end

-- pick up the license and car keys
function give_items_blockpost_quest(first_speaker, second_speaker)
    sak.out_item_namber("item_certificate", 1)
	sak.out_item_namber("car_key", 1)
end

------------------------------------------------------------------------------------------------------------------------
-- Playing sound from the object
-- Author - Gun12 and Charsi
function use_sound_items(obj)
local sound_table = {
    ['bread'] = [[inventory\inv_food]],
    ['kolbasa'] = [[inventory\inv_food]],
    ['conserva'] = [[inventory\inv_food]],
    ['vodka'] = [[inventory\inv_vodka]],
    ['antirad'] = [[inventory\inv_medic]],
    ['medkit'] = [[inventory\inv_medic]],
    ['medkit_army'] = [[inventory\inv_medic]],
    ['medkit_scientic'] = [[inventory\inv_medic]],
    ['energy_drink'] = [[inventory\inv_drinking]],
    ['bandage'] = [[inventory\inv_bandage]],
    -- Saltwort
    ['sandwich'] = [[inventory\inv_food]],
    ['beer_a'] = [[inventory\inv_drinking]],
    ['flaska'] = [[inventory\inv_drinking]],
    ['sweetness'] = [[inventory\inv_food]],
    ['matras'] = [[inventory\inv_sleeping]],
    ['suvorotka'] = [[inventory\inv_pills]],
    ['shaxter_tele'] = [[inventory\inv_drinking]],
    ['snotvornoe_tele'] = [[inventory\inv_drinking]],
    ['bezoar'] = [[inventory\inv_food]],
    ['mozg'] = [[inventory\inv_food]],
    ['vorona_egg'] = [[inventory\inv_food]],
    ['mushroom'] = [[inventory\inv_food]],
	['antizombie'] = [[inventory\inv_medic]],
    -- DMX MOD
    ['pivo'] = [[inventory\inv_drinking]],
    ['irp-b'] = [[inventory\inv_food]],
    ['voda'] = [[inventory\inv_drinking]],
    ['tuchenka'] = [[inventory\inv_food]],
    ['yantar'] = [[inventory\inv_food]],
    ['sardina'] = [[inventory\inv_food]],
    ['ogursi'] = [[inventory\inv_food]],
    ['sholad'] = [[inventory\inv_food]],
    ['kolbasadmx'] = [[inventory\inv_food]],
    ['olives'] = [[inventory\inv_food]],
    ['nuts'] = [[inventory\inv_food]],
    ['absolut_vodka'] = [[inventory\inv_vodka]],
    ['nemiroff_vodka'] = [[inventory\inv_vodka]],
    ['smirnoff_vodka'] = [[inventory\inv_vodka]],
    ['mineral_water'] = [[inventory\inv_drinking]],
    ['energy_stalker'] = [[inventory\inv_drinking]],
    ['energy_non_stop'] = [[inventory\inv_drinking]],
    ['energy_ad_rush'] = [[inventory\inv_drinking]],
    ['energy_red_bull'] = [[inventory\inv_drinking]],
    ['pivo_baltika'] = [[inventory\inv_drinking]],
    ['sok'] = [[inventory\inv_drinking]],
    ['syh_pay_gde_3'] = [[inventory\inv_food]],
    ['syh_pay_spp5'] = [[inventory\inv_food]],
    ['pervitin'] = [[inventory\inv_drugs]],
    ['amfetamin'] = [[inventory\inv_drugs]],
    ['zhgut'] = [[inventory\inv_bandage]],
    ['antiseptic'] = [[inventory\inv_bandage]],
    ['medkit_elite'] = [[inventory\inv_medic]],
    ['bandage_dmx'] = [[inventory\inv_bandage]],
    ['tab'] = [[inventory\inv_pills]],
    ['razgruzka'] = [[inventory\inv_razgruzka]],
	['psy_blockade'] = [[inventory\inv_medic]],
	['barvinok'] = [[inventory\inv_medic]],
	['gercules'] = [[inventory\inv_drinking]]}
    local snd = sound_table[obj:section()]
    if snd then
        local snd_obj = xr_sound.get_safe_sound_object(snd)
        snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
    end
end
------------------------------------------------------------------------------------------------------------------------
-- The device is accurate measurement of radiation
-- The idea comes from fashion LWR
function use_radiation_detector(obj)
    if obj:section() == "radiation_detector" then
	    play_sound([[inventory\inv_radiation_detector]])
        local rad = math.floor(db.actor.radiation * 600)
        news_manager.send_tip(db.actor, "Present state of contamination ["..rad.."/600] Baer", nil, "detector", 15000)
        amk.spawn_item_in_inv("radiation_detector")
    end
end

-----dmx135-----------------------------------------------------------------------------------------------------------
-- Author - OGSE Team
function encyclopedy_news(group, name)
	--TB3D_Services.packet_alert("dmx mod: encyclopedy_news group["..group.."] name["..name.."]")
	if group == "Diary" then
		news_manager.send_encyclopedy("diary", group)								--TB3D - ONLY DIARY IS USED in news_manager!!!!
		--news_manager.amk_send_tip_id(name, "journal_article", nil, 7, "encyclopedy_icon")
	elseif group == "Mutants" then
		--news_manager.send_encyclopedy("encyclopedy", group)
		news_manager.amk_send_tip_id(name, "intel_mutant", nil, 7, "encyclopedy_icon")
	elseif group == "Social" then
		--news_manager.send_encyclopedy("encyclopedy", group)
		news_manager.amk_send_tip_id(name, "intel_group", nil, 7, "encyclopedy_icon")
	elseif group == "Artifacts" then
		--news_manager.send_encyclopedy("encyclopedy", group)
		news_manager.amk_send_tip_id(name, "intel_art", nil, 7, "encyclopedy_icon")
	elseif group == "Anomalies" then
		--news_manager.send_encyclopedy("encyclopedy", group)
		news_manager.amk_send_tip_id(name, "intel_anom", nil, 7, "encyclopedy_icon")
	elseif group == "Locations" then
		--news_manager.send_encyclopedy("encyclopedy", group)
		news_manager.amk_send_tip_id(name, "intel_local", nil, 7, "encyclopedy_icon")
	elseif group == "Zone-story" then
		--news_manager.send_encyclopedy("encyclopedy", group)
		news_manager.amk_send_tip_id(name, "zone_history", nil, 7, "encyclopedy_icon")
	elseif group == "Stories" then
		--news_manager.send_encyclopedy("encyclopedy", group)
		news_manager.amk_send_tip_id(name, "local_lore", nil, 7, "encyclopedy_icon")
	elseif group == "memuars" then
		--news_manager.send_encyclopedy("encyclopedy", group)
		news_manager.amk_send_tip_id(name, "pers_note", nil, 7, "encyclopedy_icon")
	elseif group == "Vehicles" then
		--news_manager.send_encyclopedy("encyclopedy", group)
		news_manager.amk_send_tip_id(name, "intel_transport", nil, 7, "encyclopedy_icon")
	elseif group == "Found_PDA" then
		--news_manager.send_encyclopedy("encyclopedy", group)
		news_manager.amk_send_tip_id(name, "data_downloaded", nil, 7, "encyclopedy_icon")
	elseif group == "st_operation_agroprom" or group == "LabX18_information" or group == "aes_military_task" then
		--news_manager.send_encyclopedy("encyclopedy", group)
		news_manager.amk_send_tip_id(name, "mil_secret", nil, 7, "encyclopedy_icon")
	elseif group == "tb3d_journal" then
		news_manager.amk_send_tip_id(name, "tb3d_journal_entry", nil, 7, "encyclopedy_icon")
	end
end

local blood = 255
function blood_hud_will(victim)
	if amk.load_variable("option_hud",-1) > 1 then --and TB3D_Modders.blood_enable == true then
		if db.actor:see(victim) and db.actor:position():distance_to(victim:position()) < 5 and not get_hud():GetCustomStatic("blood_hud_static") then
			get_hud():AddCustomStatic("blood_hud_static", true):wnd():InitTexture("hud\\hud_blood_"..math.random(7))
			amk.start_timer("blood_hud_timer", 8)
			blood = 255
		end
	end
end

function blood_hud_update()
	if amk.load_variable("option_hud",-1) > 1 then --and TB3D_Modders.blood_enable == true then
		local custom_static = get_hud():GetCustomStatic("blood_hud_static")
		if custom_static and blood > 0 then
			custom_static:wnd():SetColor(GetARGB(blood,255,255,255))
			blood = blood - 3
		end
	end
end

-- Author - SkyLoader
local dead, dead_timer, cam_inert = false, 0, 0
function actor_killed()
	if not db.actor:alive() then
		if dead then
			if time_global() > dead_timer then
				get_console():execute("cam_inert "..cam_inert)
				level.add_pp_effector("deadcity_wake.ppe", 4467, false)
				level.enable_input()
				dead_timer = time_global() + 1000
			end
		else
			local dir = device().cam_dir
			db.actor:set_actor_direction(dir.x, dir.y, 0)
			cam_inert = get_console():get_float("cam_inert")
			get_console():execute("cam_inert 0")
			level.add_cam_effector("camera_effects\\surge_02.anm", 2532, false, "")
			level.add_pp_effector("surge_fade.ppe", 2011, false)
			level.disable_input()
			level.hide_indicators()
			if dmx_pda_buttons.OrganizerMenu then dmx_pda_buttons.OrganizerMenu:OrganizerQuit() end
			dead_timer = time_global() + 1750
			dead = true
		end
	end
end

-- Author - Charsi
function string_lower(s)
	local lower = ""
	local a = [[éöóêåíãøùçõúôûâàïðîëäæýÿ÷ñìèòüáþqwertyuiopasdfghjklzxcvbnm]]
	local A = [[ÉÖÓÊÅÍÃØÙÇÕÚÔÛÂÀÏÐÎËÄÆÝß×ÑÌÈÒÜÁÞQWERTYUIOPASDFGHJKLZXCVBNM]]
	for i = 1, #s do
		local character = string.sub(s, i, i)
		for j = 1, #A do
			if character == string.sub(A, j, j) then character = string.sub(a, j, j) break end
		end
		lower = lower..character
	end
	return lower
end

-- Author - Charsi
function string_declension(n, a, b, c)
	return (n%10 == 1 and n%100 ~= 11) and (tostring(n).." "..a) or (n%10 >= 2 and n%10 <= 4 and (n%100 < 10 or n%100 >= 20) and (tostring(n).." "..b) or (tostring(n).." "..c))
end

-- Author - Charsi
function visual_fix(obj)
	if obj:clsid() == clsid.equ_stalker_s or obj:clsid() == clsid.equ_exo then
		local outfit = db.actor:get_current_outfit()
		if outfit and outfit:id() ~= obj:id() then
			db.actor:transfer_item(outfit, db.actor)
		end
	end
end

-------------------------------------------dmx135-------------
-- Generator flame mixture
-- Author - Charsi
function use_item_ammo_flame_transfer(obj)
	if TB3D_Services.is_collector(921) == false then
		if obj:section() == "item_ammo_flame_transfer" then
			amk.spawn_item_in_inv("item_ammo_flame_transfer")
			play_sound([[device\pda\pda_sos]])
			local flame=db.actor:object("wpn_flame")
				if flame then
				local ballon=db.actor:object("amk_ballon")
				local kanistra=db.actor:object("amk_kanistra")
					if ballon and kanistra then
					local ammo_elapsed = flame:get_ammo_in_magazine() + 150
						if ammo_elapsed > 1150 then -- kabzdets flamethrower
						amk.remove_item(flame)
						local pos=db.actor:position():add(db.actor:direction():mul(1)) -- spawns details
						local lv=db.actor:level_vertex_id()
						local gv=db.actor:game_vertex_id()
						alife():create("gorelka",pos,lv,gv)
						alife():create("manometr",pos,lv,gv)
						alife():create("trubka",pos,lv,gv)
						alife():create("flamethrower_bad",pos,lv,gv)
						db.actor.health = -0.3 -- downgrade HP
						rx_utils.get_sound([[weapons\t_f1_explosion]]):play_no_feedback(db.actor,sound_object.s2d,0,vector(),1.0) -- bang
						level.add_cam_effector("camera_effects\\fusker.anm",959,false,"") -- kameffektor hit in the face
					else
					if ammo_elapsed > 1000 then news_manager.amk_send_tip_id("flame_tip1","important_msg", 2, 25, "pda_icon") end
						amk.remove_item(ballon)
						amk.remove_item(kanistra)
						flame:set_ammo_elapsed(ammo_elapsed)
					end
				else
					news_manager.amk_send_tip_id("flame_tip2","important_msg", 2, 25, "pda_icon")
				end
			else
				news_manager.amk_send_tip_id("flame_tip3","important_msg", 2, 25, "pda_icon")
			end
		end
	end
end 
------------------------------------------------------------------------------------------------------------------------
-- Bag with silencers
function use_silencers_box(obj)	-- added new silencer's - aleks1970
    if obj:section() == "silencers_box" then
        amk.spawn_item_in_inv("wpn_addon_silencer")
		amk.spawn_item_in_inv("wpn_9mm_nato_silencer")
		amk.spawn_item_in_inv("wpn_addon_silencer_pistol")
		amk.spawn_item_in_inv("wpn_addon_sil_9_p")
		amk.spawn_item_in_inv("wpn_addon_sil_45")
		amk.spawn_item_in_inv("wpn_addon_sil_86x70")
		amk.spawn_item_in_inv("wpn_addon_sil_9x39")
		amk.spawn_item_in_inv("wpn_addon_sil_545_ar")
		amk.spawn_item_in_inv("wpn_addon_sil_556_ar")
		amk.spawn_item_in_inv("wpn_addon_sil_762_p")
		amk.spawn_item_in_inv("wpn_addon_sil_762_ar")
		amk.spawn_item_in_inv("wpn_addon_sil_762x39")
		amk.spawn_item_in_inv("wpn_addon_sil_762_pms")
		amk.spawn_item_in_inv("wpn_addon_sil_1143_p")
		amk.spawn_item_in_inv("wpn_addon_9x39silencer")
		amk.spawn_item_in_inv("wpn_upg_556_silencer")
		amk.spawn_item_in_inv("wpn_addon_silencer_usp")
		amk.spawn_item_in_inv("wpn_addon_sil_bramit")
		amk.spawn_item_in_inv("wpn_tgp-a_silencer")
		amk.spawn_item_in_inv("wpn_addon_sil_tmp")
		amk.spawn_item_in_inv("wpn_addon_sil_57")
		amk.spawn_item_in_inv("wpn_sil74")
    end
end

-- Box with screws
function use_bolt_box(obj)
    if obj:section() == "bolt_box" then
        local tab_items = {{[10]="fake_bolt"}}
        local tab_where = "actor"
        this.SpawnToNpcOrToLocation(tab_items,tab_where)
    end
end

-- Explosion at weapons heavy wear
-- Author - OGSE Team, adaptation - Charsi
local stored_ammo_num = nil
local stored_it_id = nil
function wpn_explode_update()
    local aitem = db.actor:active_item()
	local aslot = db.actor:active_slot()
    if aitem and (aslot==1 or aslot==2) and isWeapon(aitem) then
        local it_id = aitem:id()
        local ammo_num = aitem:get_ammo_in_magazine()
        if stored_it_id ~= nil and stored_ammo_num ~= nil then
			if TB3D_Modders.guns_can_explode == true then
				if stored_it_id == it_id and ammo_num < stored_ammo_num and aitem:condition() < 0.25 and math.random()*0.5 > aitem:condition() then
					fx_snd = xr_sound.get_safe_sound_object("weapons\\t_f1_explosion") -- verify, whether there is sound
					if fx_snd then fx_snd:play_no_feedback(aitem, sound_object.s3d, 0, aitem:position(), 1) end
					fx_particle = particles_object("amik\\explosion\\explosion_f1") -- verify, there partikl
					if fx_particle then fx_particle:play_at_pos(aitem:position()) end
					if TB3D_Modders.default_hit == true then TB3D_hit_styles.explode(db.actor, db.actor, 0.2, 0.6, vector():set(0,0,0)) end
					alife():release(alife():object(aitem:id()), true) -- Remove the object
				end
			end
			stored_ammo_num = ammo_num
			stored_it_id = it_id
		else
			stored_ammo_num = nil
			stored_it_id = nil
		end
    end
end
------------------------------------------------------------------------------------------------------------------------
-- Red bildovsky effect wound
-- Author - Shadows
local def_health = 0
function red_effect()
    if def_health>db.actor.health+0.008 then
	    --level.add_cam_effector("camera_effects\\hit_back.anm", 1975, false, "")
	    level.add_pp_effector("fire_hit.ppe", 1974, false) 
    end
    def_health = db.actor.health
end
------------------------------------------------------------------------------------------------------------------------
-- Reports of an impending emissions
-- Author - Shadows
function blowout_phrases()
	local phrase = math.random(1,4)
    local snd_sms = sound_object("ambient\\blowout_sms_"..tostring(math.random(1,6)))  
    snd_sms:play_at_pos(db.actor,vector():set(0,0,0),0,sound_object.s2d)
	if phrase == 1 then
		news_manager.amk_send_tip_id("blow_phrase1", "important_msg", nil, 20, "blowout_sms")
	elseif phrase == 2 then
		news_manager.amk_send_tip_id("blow_phrase2", "important_msg", nil, 20, "blowout_sms")
	elseif phrase == 3 then
		news_manager.amk_send_tip_id("blow_phrase3", "important_msg", nil, 20, "blowout_sms")
	else
		news_manager.amk_send_tip_id("blow_phrase4", "important_msg", nil, 20, "blowout_sms")
	end
end
------------------------------------------------------------------------------------------------------------------------
-- Reproduce the sound
-- Author - Real Wolf
function play_sound(sound,obj)
	if _g.is_disconnecting then	return end
	if obj == nil then obj = db.actor end
	snd = xr_sound.get_safe_sound_object(sound)
	snd:play_no_feedback(obj, sound_object.s2d, 0, vector(), 1.0)
	--TB3D_Services.info_alert("Sound: ["..sound.."]")
end
------------------------------------------------------------------------------------------------------------------------
-- Throw an object from a slot in your inventory
function drop_item_to_inventory(number)
	if TB3D_Modders.use_inventory_message == true then TB3D_Services.info_alert("dmx_mod: drop item to inventory from slot["..utils.to_str(number).."]") end
    local item = db.actor:item_in_slot(number)
    if item then
		if TB3D_Modders.use_inventory_message == true then
			TB3D_Services.packet_alert("dmx_mod: drop item to inventory item sect["..utils.to_str(item:section()).."]")
		end
        db.actor:drop_item(item)
		amk.spawn_in_inv(item:section(), 1)
        alife():release(item,true)
    end
	if TB3D_Modders.use_inventory_message == true then TB3D_Services.info_alert("dmx_mod: drop item to inventory done") end
end
------------------------------------------------------------------------------------------------------------------------
-- Draw the desired static thin over suits
-- Author - Charsi
function hidden_static()			--startup and suit changes
	--TB3D_Services.packet_alert("dmx mod: hidden static")
	local hud = get_hud()
	local cs_names = {"caption_medkit", "caption_antirad", "caption_bandage", "caption_vodka", "caption_button",
				"caption_value_1", "caption_value_2", "caption_value_3", "caption_value_4"}
	for k,v in pairs(cs_names) do
		if hud:GetCustomStatic(v) then
			hud:RemoveCustomStatic(v)
		end
	end
	cs_names = {"hud_show_time", "hud_show_compass", "hud_show_delta", "inv_weight_static", "sleep_static", "dmx_speedometr", "car_equalize",
						"anabiotic_static", "radioprotector_static", "psy_blockade_static", "hud_show_timer", "hud_show_enemy"}
	for k,v in pairs(cs_names) do
		if hud:GetCustomStatic(v) then
			hud:RemoveCustomStatic(v)
			hud:AddCustomStatic(v)
		end
	end
	TB3D_Services.show_medkits()
	biodetector.biodetectorRemove()
end
------------------------------------------------------------------------------------------------------------------------
-- Versatile spawn
-- Author - erlik
function SpawnToNpcOrToLocation(tab_items,tab_where)
    local count = 0
    local pos, lvid, gvid, id, obj
    local function Compare(id) obj = alife():object(id) return obj and obj.profile_name and obj:profile_name() == tab_where end
    for k, v in pairs(tab_items) do
        if type(tab_where)=='table' then
            for k, v in pairs (tab_items[k]) do
                count = k
                for i=1, count do
                    alife():create(v,vector():set(tab_where['x'],
                    tab_where['y'],tab_where['z']),
                    tab_where['lv'],tab_where['gv'])
                end
            end
        elseif type(tab_where)=='string' then
            if tab_where =="actor" then
                obj = alife():actor()
            else
                for i=first_object, last_object do
                    if Compare(i) then
                        break
                    end
                end
            end
        if obj == nil then return end
            for k, v in pairs (tab_items[k]) do
                count = k
                for i=1, count do
                    alife():create(v, obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id)
                end
            end
        elseif type(tab_where)=='number' then
            obj = level_object_by_sid(tab_where)
            if obj ~= nil then
                id, pos, lvid, gvid= obj:id(), obj:position(), obj:level_vertex_id(), obj:game_vertex_id()
            elseif obj == nil then
                obj = alife():story_object(tab_where)
                id, pos, lvid, gvid = obj.id, obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id
                for k, v in pairs (tab_items[k]) do
                    count = k
                    for i=1, count do
                        alife():create(v, pos, lvid, gvid, id)
                    end
                end
            end
        end
    end
end
------------------------------------------------------------------------------------------------------------------------
-- Sleep indicator
function hud_sleep_static(is_scope)
local hud = get_hud()
    if is_scope == true then hud:RemoveCustomStatic("sleep_static")
    elseif hud:GetCustomStatic("sleep_static")==nil and amk.load_variable("gg_need_sleep",0)>300 then
        hud:AddCustomStatic("sleep_static", true)
    end
end
------------------------------------------------------------------------------------------------------------------------
-- To check the multiplicity of binoculars
-- Author - Charsi
-- 37.125\5.625 (min\max)
local st
function zoom_update()
    local item = db.actor:active_item()
    if item and (item:section()=="wpn_binoc" or item:section()=="wpn_arm_binoc") then
        if not fov then fov=device().fov end
	    local z=fov/device().fov
        if st then
	        if z>1.01 then z=z+0.05
		        local t=math.floor(z)
		        local r=math.floor((z-t)*10)
		        st:SetText("fov="..fov.." df="..device().fov)
	        end
	        if z<1.01 then st:SetText("") end
        else
	        st=CUIStatic()
	        st:Init(winx/2,-300+winy/2,200,200)	-- coordinates of where to draw
	        st:Show(true)
	        get_hud():AddDialogToRender(st)
        end
    end
end
------------------------------------------------------------------------------------------------------------------------
--p_dest_dir vector form
--(z,x,y) = (u,s,e) counterclockwise right hand coords
--this equates to Upness, South to East

-- Level changer
-- Author - singapur22
function create_level_changer(
    p_story_id,   -- STORY_ID new level_changer (We shall need later)
    p_position,   -- vector coordinates, which will be located in the center of a new level_changer
    p_lvertex_id, -- level_vertext_id - identify the level at which to make level_changer
    p_gvertex_id, -- game_vertext_id 
    p_dest_lv,    -- level_vertex_id - identify the level at will to throw the player 
    p_dest_gv,    -- game_vertex_id
    p_dest_pos,   -- coordinates of the point at which the new level will be a player
    p_dest_dir,   -- napravrenie view player
    p_dest_level, -- level name, such as "L11_Pripyat"
    p_silent,     -- should be set to 1 to suppress the question of changing the level (automatic transfer)
    p_spot,	  		-- 0 = make mapspot
	p_hint			--text hint for spot
	)
    local obj = alife():create("level_changer", p_position, p_lvertex_id, p_gvertex_id)
    local packet = net_packet()
    obj:STATE_Write(packet)
    -- properties cse_alife_object
    local game_vertex_id = packet:r_u16()
    local cse_alife_object__unk1_f32 = packet:r_float()
    local cse_alife_object__unk2_u32 = packet:r_u32()
    local level_vertex_id = packet:r_u32()
    local object_flags = packet:r_u32()
    local custom_data = packet:r_stringZ()
    local story_id = packet:r_u32()
    local spawn_story_id = packet:r_u32()
    -- properties cse_shape
    local shape_count = packet:r_u8()
    for i=1,shape_count do
		local shape_type = packet:r_u8()
		if shape_type == 0 then
			-- sphere
			local center = packet:r_vec3()
			local radius = packet:r_float()
		else
			-- box
			local axis_x_x = packet:r_float()
			local axis_x_y = packet:r_float()
			local axis_x_z = packet:r_float()
			local axis_y_x = packet:r_float()
			local axis_y_y = packet:r_float()
			local axis_y_z = packet:r_float()
			local axis_z_x = packet:r_float()
			local axis_z_y = packet:r_float()
			local axis_z_z = packet:r_float()
			local offset_x = packet:r_float()
			local offset_y = packet:r_float()
			local offset_z = packet:r_float()
		end
    end
    -- properties cse_alife_space_restrictor
    local restrictor_type = packet:r_u8()
    -- properties cse_level_changer
    local dest_game_vertex_id = packet:r_u16() 
    local dest_level_vertex_id = packet:r_u32() 
    local dest_position = packet:r_vec3()
    local dest_direction = packet:r_vec3()
    local dest_level_name = packet:r_stringZ()
    local dest_graph_point = packet:r_stringZ()
    local silent_mode = packet:r_u8()
    packet:w_begin(game_vertex_id) -- game_vertex_id
    packet:w_float(cse_alife_object__unk1_f32)
    packet:w_u32(cse_alife_object__unk2_u32) 
    packet:w_u32(level_vertex_id) -- level_vertex_id
    packet:w_u32( bit_not(193) )  -- object_flags = -193 = 0xFFFFFF3E
    packet:w_stringZ(custom_data)
    packet:w_u32(p_story_id) -- story_id
    packet:w_u32(spawn_story_id)
    packet:w_u8(1)    -- number of pieces
    packet:w_u8(1)    -- body type: box
    packet:w_float(2) -- axis_x_x
    packet:w_float(0) -- axis_x_y
    packet:w_float(0) -- axis_x_z
    packet:w_float(0) -- axis_y_x
    packet:w_float(4) -- axis_y_y
    packet:w_float(0) -- axis_y_z
    packet:w_float(0) -- axis_z_x
    packet:w_float(0) -- axis_z_y
    packet:w_float(4) -- axis_z_z
    packet:w_float(0) -- offset_x
    packet:w_float(0) -- offset_y
    packet:w_float(0) -- offset_z
    packet:w_u8(3)    -- restrictor_type
    packet:w_u16(p_dest_gv)   -- destination game_vertex_id
    packet:w_u32(p_dest_lv)   -- destination level_vertex_id
    packet:w_vec3(p_dest_pos) -- destination position
    packet:w_vec3(p_dest_dir) -- destination direction (gaze direction)
    packet:w_stringZ(p_dest_level) -- destination level name
    packet:w_stringZ("start_actor_99") -- some string, always const
    packet:w_u8(p_silent)     -- 1 for silent level changing
    packet:r_seek(0)
    obj:STATE_Read(packet, packet:w_tell())
    if p_spot == 0 and level.map_has_object_spot(obj.id, "level_changer") == 0 then
		if not p_hint then p_hint = "" end
		level.map_add_object_spot(obj.id, "level_changer", p_hint)
		--news_manager.send_tip(db.actor, "added spot: "..utils.to_str(obj.id), nil, nil, 30000)
	end
	return obj
end

function get_lc_data(obj)
	local packet = net_packet()
	obj:STATE_Write(packet)
	local t={}
	t.game_vertex_id = packet:r_u16()
	t.distance = packet:r_float()
	t.direct_control = packet:r_s32()
	t.level_vertex_id = packet:r_s32()
	t.object_flags = packet:r_s32()
	t.custom_data = packet:r_stringZ()
	t.story_id = packet:r_s32()
	t.spawn_story_id = packet:r_s32()
    -- properties cse_shape
    local shape_count = packet:r_u8()
    for i=1,shape_count do
		local shape_type = packet:r_u8()
		if shape_type == 0 then
			-- sphere
			local center = packet:r_vec3()
			local radius = packet:r_float()
		else
			-- box
			local axis_x_x = packet:r_float()
			local axis_x_y = packet:r_float()
			local axis_x_z = packet:r_float()
			local axis_y_x = packet:r_float()
			local axis_y_y = packet:r_float()
			local axis_y_z = packet:r_float()
			local axis_z_x = packet:r_float()
			local axis_z_y = packet:r_float()
			local axis_z_z = packet:r_float()
			local offset_x = packet:r_float()
			local offset_y = packet:r_float()
			local offset_z = packet:r_float()
		end
    end
	t.restrictor_type = packet:r_u8()
	t.dest_game_vertex_id = packet:r_u16()
	t.dest_level_vertex_id = packet:r_s32()
	t.dest_position = packet:r_vec3()
	t.dest_direction = packet:r_vec3()
	t.dest_level_name = packet:r_stringZ()
	t.dest_graph_point = packet:r_stringZ()
	t.silent_mode = packet:r_u8()
	if packet:r_elapsed() ~= 0 then
		if TB3D_Modders.use_abort_message == true then TB3D_Services.abort_alert("DMX get lc data: left= "..packet:r_elapsed()) end
	end
	return t
end

function set_lc_data(t,obj)
	local packet = net_packet()
	obj:STATE_Write(packet)
	packet:w_begin(t.game_vertex_id)
	packet:w_float(t.distance)
	packet:w_s32(t.direct_control)
	packet:w_s32(t.level_vertex_id)
	packet:w_s32(t.object_flags)
	packet:w_stringZ(t.custom_data)
	packet:w_s32(t.story_id)
	packet:w_s32(t.spawn_story_id)
    packet:w_u8(1)    -- number of pieces
    packet:w_u8(1)    -- body type: box
    packet:w_float(2) -- axis_x_x
    packet:w_float(0) -- axis_x_y
    packet:w_float(0) -- axis_x_z
    packet:w_float(0) -- axis_y_x
    packet:w_float(4) -- axis_y_y
    packet:w_float(0) -- axis_y_z
    packet:w_float(0) -- axis_z_x
    packet:w_float(0) -- axis_z_y
    packet:w_float(4) -- axis_z_z
    packet:w_float(0) -- offset_x
    packet:w_float(0) -- offset_y
    packet:w_float(0) -- offset_z
	packet:w_u8(t.restrictor_type)
	packet:w_u16(t.dest_game_vertex_id)
	packet:w_s32(t.dest_level_vertex_id)
	packet:w_vec3(t.dest_position)
	packet:w_vec3(t.dest_direction)
	packet:w_stringZ(t.dest_level_name)
	packet:w_stringZ(t.dest_graph_point)
	packet:w_u8(t.silent_mode)
	packet:r_seek(0)
	obj:STATE_Read(packet, packet:w_tell())
end

----------------------------------------------------------------------------------------

--/SHADOWS From the central to eastern Pripyat
function pripyat_to_cop_pripyat()
	local obj = alife():story_object(97115)
	if not obj then
		--TB3D_Services.info_alert("DMX mod: pcp spawn")
		create_level_changer(97115, vector():set(189.497,-2.115,233.149),259791,2149, -- where the transition
		176155,3760, vector():set(-15.765,-0.496,307.323), -- to move
		vector():set(0.0,0.0,-1.0), -- line of sight with the appearance of
		"pripyat",0,0,"to_eprip") -- at any locus and the request (0 - will issue, 1 - automatic transition)
		news_manager.amk_send_tip_id("path_cop_ep", "path_new", 2, 25, "pda_icon")
	end
end

--/AMK MOD On the eastern side of the central number 1
function pripyat_cop_to_pripyat_1()
	local obj = alife():story_object(97116)
	if not obj then
		--TB3D_Services.info_alert("DMX mod: pcp1 spawn")
		create_level_changer(97116, vector():set(-22.476,-0.491,306.534),167535,3760, -- where the transition
		257147,2149, vector():set(180.800,-2.205,233.571), -- to move
		vector():set(0.0,0.0,-1.0), -- line of sight with the appearance of
		"l11_pripyat",0,0,"to_pripyat_n") -- at any locus and the request (0 - will issue, 1 - automatic transition)
	end
end

--/AMK MOD On the eastern side of the central number 2
function pripyat_cop_to_pripyat_2()
	local obj = alife():story_object(97117)
	if not obj then
		--TB3D_Services.info_alert("DMX mod: pcp2 spawn")
		create_level_changer(97117, vector():set(-158.014,-0.435,-395.872),48713,3753, -- where the transition
		145457,2269, vector():set(35.081,-2.281,-291.484), -- to move
		vector():set(0.0,0.0,-1.0), -- line of sight with the appearance of
		"l11_pripyat",0,0,"to_pripyat_s") -- at any locus and the request (0 - will issue, 1 - automatic transition)
	end
end

--[[DMX MOD From east to Pripyat X-8, 109998 use button
function pripyat_cop_to_lab_x8(is_silent)
	local obj = alife():story_object(97118)
	if not obj then
		--TB3D_Services.info_alert("DMX mod: cp-x8 spawn")
		create_level_changer(97118, vector():set(-78.298,0.303,100.377),111629,3754, -- where the transition
		3750,3838, vector():set(-77.974,-7.753,94.387), -- to move
		vector():set(0.0,0.0,-1.0), -- line of sight with the appearance of
		"labx8",0,0,"labx8") -- at any locus and the request (0 - will issue, 1 - automatic transition)
		if is_silent and is_silent == true then
			--don't report
		else
			news_manager.amk_send_tip_id("path_ep_x8", "path_new", 2, 25, "pda_icon")
		end
	end
end]]--

--/AMK MOD From X-8 in eastern Pripyat, 109998 moved slightly
function lab_x8_to_pripyat_cop()
	local obj = alife():story_object(97119)
	if not obj then
		--TB3D_Services.info_alert("DMX mod: labx8-cp spawn")
		create_level_changer(97119, vector():set(-77.880,-7.896,101.591),3766,3838, -- where the transition
		112273,3754, vector():set(-77.719,0.400,96.113), -- to move
		vector():set(0.0,0.0,-1.0), -- line of sight with the appearance of
		"pripyat",0,0,"to_eprip") -- at any locus and the request (0 - will issue, 1 - automatic transition)
	end
end

-------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------
--  dAVROs level changers for the treasure hunt

--/dAVROs Red Forest to Dead City
function create_level_changer_redforest_to_dcity()
	local obj = alife():story_object(98010)
	if not obj then
		create_level_changer(98010, vector():set(-204.395,0.136,-332.527),292,3231, 	-- where the transition is
		445515,3652, vector():set(95.231,1.468,8.239), 								-- destination
		vector():set(0,-2.0,0), 								-- y coord range is + pi - pi 1.0 is about 300deg -1.0 is about 60deg
		"dead_city",0,0,"to_deadcity") 																	-- at any locus and the request (0 - will issue, 1 - automatic transition)
		news_manager.amk_send_tip_id("path_rf_dc", "path_new", 2, 25, "pda_icon")
	end
end

--/dAVROs Zaton to Jupiter
function create_level_changer_zat_to_jup()
	local obj = alife():story_object(98000)
	if not obj then
	create_level_changer(98000, vector():set(429.968,28.972,-431.634),1670437,3694, 	-- where the transition is
    1405036,3742, vector():set(434.620,2.768,471.921), 								-- destination
    vector():set(0,3.0,0), 								-- y coord range is + pi - pi 1.0 is about 300deg -1.0 is about 60deg
	"jupiter",0,0,"jupiter") 																	-- at any locus and the request (0 - will issue, 1 - automatic transition)
	news_manager.amk_send_tip_id("path_bw_jp", "path_new", 2, 25, "pda_icon")
	end
end

--/dAVROs Jupiter to East Pripyat
function create_level_changer_jup_to_eprip()
	local obj = alife():story_object(98001)
	if not obj then
	create_level_changer(98001, vector():set(-456.989,0.068,-346.228),6,3702,	--109988  (-468.035,0.006,-346.117),11732,3702, 	
    420311,3765, vector():set(324.485,-0.507,-259.430), 							
    vector():set(0.0,1.5,0), 													
	"pripyat",0,0,"to_eprip") 																	
	--news_manager.amk_send_tip_id("path_jp_ep", "path_new", 2, 25, "pda_icon")
	end
end

--/dAVROs East pripyat Dock to Jupiter NWest Rail station
function create_level_changer_eprip_to_jup()
	local obj = alife():story_object(98002)
	if not obj then
	create_level_changer(98002, vector():set(329.172,-8.536,286.850),486353,3769, 	
    111766,3703, vector():set(-373.499,4.431,381.461), 							
    vector():set(0.0,0,0), 													
	"jupiter",0,0,"jupiter") 																	
	news_manager.amk_send_tip_id("path_ep_jp", "path_new", 2, 25, "pda_icon")
	end
end

-- /dAVROs and TB3D Jupiter elevator to Jupiter Underground elevator
function create_level_changer_jup_to_jupunder(is_silent)
	local pspot = 0
	if is_silent then pspot = 1 end
	local obj = alife():story_object(98003)
	if not obj then
	create_level_changer(98003, vector():set(326.335,13.888,-329.930),1243399,3745, 	
    1475,3772, vector():set(-44.722,8.012,444.343), 							
    vector():set(0.0,3.14,0), 												
	"jupiter_underground",1,pspot,"jupiter_underground") 													
	if not is_silent then news_manager.amk_send_tip_id("path_jp_jpu", "path_new", 2, 25, "pda_icon") end
	end
end

-- /dAVROs and TB3D Jupiter Underground elevator to Jupiter elevator
function create_level_changer_jupunder_to_jup(is_silent)
	local pspot = 0
	if is_silent then pspot = 1 end
	local obj = alife():story_object(97115)
	if not obj then
	create_level_changer(97115, vector():set(-50.187,8.008,458.433),805,3772, 	
    1252688,3745, vector():set(335.816,21.220,-329.225), 							
    vector():set(0.0,3.14,0), 												
	"jupiter",0,pspot,"jupiter") 													
	if not is_silent then news_manager.amk_send_tip_id("path_jpu_jp", "path_new", 2, 25, "pda_icon") end
	end
end

--/dAVROs   Pripyat to npp1
function create_level_changer_prip_to_npp1()
	local obj = alife():story_object(98996)
	if not obj then
		create_level_changer(98996, vector():set(96.352,-1.958,-94.684),205364,2259, 	
		404843,2400, vector():set(918.358,-0.101,-398.646), 							
		vector():set(0.0,0.0,-1.0), 												
		"l11_pripyat",0,0,"to_aes") 													
		news_manager.amk_send_tip_id("path_pripyat_npp1", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D  Jupiter Underground to Limansk tunnel - outside level boundaries!!!!
function create_level_changer_jupunder_to_limansk()
	local obj = alife():story_object(98006)
	if not obj then
	create_level_changer(98006, vector():set(0.980,8.805,-135.721),13527,3794, 	
    47735,3003, vector():set(152.636,-3.966,190.433), 							
    vector():set(0.0,0.0,-1.0), 												
	"limansk",0,0,"to_limansk") 													
	news_manager.amk_send_tip_id("path_jpu_lm", "path_new", 2, 25, "pda_icon")
	end
end

--/dAVROs or storm  Jupiter Oasis to Yantar lake
function create_level_changer_jup_to_yantar()
	local obj = alife():story_object(98008)
	if not obj then
	create_level_changer(98008, vector():set(-14.676,17.085,-323.212),691049,3710, 	
    20942,1454, vector():set(-53.111,-12.054,-259.159), 							
    vector():set(0.0,0.0,-1.0), 												
	"l08_yantar",0,0,"to_yantar") 													
	news_manager.amk_send_tip_id("path_jp_yn", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D and XR EFFECTS   wishgranter to bar
function create_level_changer_sarc_to_bar()
	local obj = alife():story_object(98999)
	if not obj then
	create_level_changer(98999, vector():set(76.406,67.662,-15.765),6321,2417, 	
    20307,1245, vector():set(1.858,1.975,238.087), 							
    vector():set(0.0,0.0,-1.0), 												
	"l05_bar",0,0,"bar_rostok") 													
	news_manager.amk_send_tip_id("path_sc_bar", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D and XR EFFECTS  sarc_bottom to chaes
function create_level_changer_sarc_to_chaes()
	local obj = alife():story_object(98998)
	if not obj then
	create_level_changer(98998, vector():set(23.533,-4.733,2.552),4684,2424, 	
    477334,2280, vector():set(1076.195,0.148,-28.033), 							
    vector():set(0.0,0.0,-1.0), 												
	"l12_stancia",0,0,"to_aes") 													
	news_manager.amk_send_tip_id("path_sc_chs", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D ====================== new levels =======================================

function create_level_changer_dv_to_ds()
	local obj = alife():story_object(481)
	if not obj then
		create_level_changer(481, vector():set(188.358,0.689,-293.518),386445,936, 	
			48446,4600, vector():set(-402.361,1.208,619.188), 							
			vector():set(0.0,0.0,-1.0), 												
			"k01_darkscape",0,0,"to_darkscape") 													
		news_manager.amk_send_tip_id("path_dv_ds", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_ds_to_esc()
	local obj = alife():story_object(266)
	if not obj then
		create_level_changer(266, vector():set(-607.021,-2.275,-394.941),660,4596, 	
			578349,250, vector():set(325.198,18.299,269.204), 							
			vector():set(0.0,0.0,-1.0), 												
			"l01_escape",0,0,"to_escape") 													
		news_manager.amk_send_tip_id("path_ds_esc", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_ds_to_poli()
	local obj = alife():story_object(267)
	if not obj then
		create_level_changer(267, vector():set(441.816,-1.869,-498.166),936289,4647, 	
			131487,5390, vector():set(-43.697,-9.202,50.423), 							
			vector():set(0.0,0.0,-1.0), 												
			"l01_poligon",0,0,"to_poli") 													
		news_manager.amk_send_tip_id("path_ds_poli", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_bar_to_ww()
	local obj = alife():story_object(609)
	if not obj then
		create_level_changer(609, vector():set(-26.144,0.965,322.052),21537,1245, 	
			1555660,4666, vector():set(425.768,9.197,-428.468), 							
			vector():set(0.0,0.0,-1.0), 												
			"dark_forest",0,0,"to_darkforest") 													
		news_manager.amk_send_tip_id("path_bar_ww", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(203)
	if not obj then
		create_level_changer(203, vector():set(438.334,7.424,-432.964),1571763,4666, 	
			21537,1245, vector():set(-10.017,-0.927,314.675), 							
			vector():set(0.0,0.0,-1.0), 												
			"l05_bar",0,0,"to_rostok") 													
		--news_manager.amk_send_tip_id("path_ww_bar", "path_new", 2, 25, "pda_icon")
	end
end

function create_f1_level_changers()
	local obj = alife():story_object(6004)
	if not obj then
		create_level_changer(6004, vector():set(476.675,35.068,50.613),1742264,3693, 	
		369132,4679, vector():set(71.882,29.999,-264.536), 							
		vector():set(0.0,0.0,-1.0), 												
		"level_f-1",0,0,"to_f1") 													
		news_manager.amk_send_tip_id("path_zat_f1", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98009)--/East Pripyat ladder to Jupiter Underground ladder
	if not obj then
		create_level_changer(98009, vector():set(185.539,-14.040,-259.770),415470,3765, 	
		40755,3827, vector():set(81.901,4.021,-222.572), 							
		vector():set(0.0,0.0,-1.0), 												
		"jupiter_underground",1,0,"jupiter_underground") 													
		news_manager.amk_send_tip_id("path_ep_jpu", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98004)--  Jupiter Underground ladder to East Pripyat ladder entrance
	if not obj then
		create_level_changer(98004, vector():set(82.617,32.694,-222.547),40755,3827, 	
		415473,3765, vector():set(185.360,-0.523,-258.448),
		vector():set(0.710,0.000,0.705), 												
		"pripyat",0,0,"to_eprip") 													
		--news_manager.amk_send_tip_id("path_jp_ep", "path_new", 2, 25, "pda_icon")
	end
end

function create_jupu_level_changers()
	local obj = alife():story_object(98028)--/TB3D   jupu to x10
	if not obj then
		create_level_changer(98028, vector():set(12.271,9.557,444.525),21323,3791, 	
			8336,2773, vector():set(15.372,-23.556,19.247), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l10u_bunker",0,0,"to_labx10") 													
		--news_manager.amk_send_tip_id("path_jupu_x10", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98029)--/TB3D   x10 to jupu
	if not obj then
		create_level_changer(98029, vector():set(20.162,-23.524,16.630),8597,2773, 	
			17068,3791, vector():set(5.306,8.065,434.309), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"jupiter_underground",0,0,"to_jupunder") 													
		--news_manager.amk_send_tip_id("path_x10_jupu", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98026)--/TB3D   vokzal to limansk
	if not obj then
		create_level_changer(98026, vector():set(-44.995,-0.171,-27.339),1894,5342, 	
			54135,3015, vector():set(57.485,-6.002,47.833), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"limansk",0,0,"to_limansk") 													
		news_manager.amk_send_tip_id("path_vok_lim", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98027)--/TB3D   limansk to vokzal
	if not obj then
		create_level_changer(98027, vector():set(71.384,-6.003,45.992),57322,3015, 	
			966,5342, vector():set(-50.962,-0.703,-19.613), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l05_vokzal",0,0,"to_vokzal") 													
		--news_manager.amk_send_tip_id("path_lim_vok", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_jupu_to_x14()
	local obj = alife():story_object(98016)
	if not obj then
		create_level_changer(98016, vector():set(7.035,4.287,-135.804),17553,3794, 	
			3231,5386, vector():set(34.832,-34.484,-36.981), 							
			vector():set(0.0,0.0,-1.0), 												
			"lab_x14",0,0,"to_labx14") 													
		--news_manager.amk_send_tip_id("path_jupu_x14", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98015)
	if not obj then
		create_level_changer(98015, vector():set(-70.692,-23.857,63.808),5041,3849, 	
			3408,5388, vector():set(36.132,-34.483,15.206), 							
			vector():set(0.0,0.0,-1.0), 												
			"lab_x14",0,0,"to_labx14") 													
		--news_manager.amk_send_tip_id("path_x8_x14", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98014)
	if not obj then
		create_level_changer(98014, vector():set(-113.065,-11.054,-225.994),80591,3752, 	
			3408,5388, vector():set(36.132,-34.483,15.206), 							
			vector():set(0.0,0.0,-1.0), 												
			"lab_x14",0,0,"to_labx14") 													
		--news_manager.amk_send_tip_id("path_eprip_x14", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(284)
	if not obj then
		alife():create(17769)
	end
	obj = alife():story_object(6017)
	if not obj then
		alife():create(17770)
	end
	obj = alife():story_object(6018)
	if not obj then
		alife():create(17798)
	end
end

function create_digger_level_changers_1()
	local obj = alife():story_object(209)
	if not obj then
		create_level_changer(209, vector():set(-32.285,-2.392,-184.010),66792,2134, 	
			9882,5340, vector():set(10.885,-7.377,61.225), 							
			vector():set(0.0,0.0,-1.0), 												
			"l05_vokzal",0,0,"to_vokzal") 													
		news_manager.amk_send_tip_id("path_prip_vok", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(277)
	if not obj then
		create_level_changer(277, vector():set(10.603,-7.369,68.999),9753,5340, 	
			66803,2134, vector():set(-32.436,-2.399,-175.055), 							
			vector():set(0.0,0.0,-1.0), 												
			"l11_pripyat",0,0,"to_pripyat") 													
		--news_manager.amk_send_tip_id("path_vok_prip", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98034)
	if not obj then
		create_level_changer(98034, vector():set(155.659,12.644,-382.917),468134,4995,		--109980, (-129.360,21.485,-253.939),5176,4693, 
			661323,3121, vector():set(279.361,9.470,-78.920), 							
			vector():set(0.0,0.0,-1.0), 												
			"generators",0,0,"to_generators") 													
		news_manager.amk_send_tip_id("path_prom_gen", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98035)
	if not obj then
		create_level_changer(98035, vector():set(297.179,11.230,-71.039),683906,3121, 	
			456690,4995, vector():set(144.654,15.087,-383.299),								--109980, 7714,4693, vector():set(-125.238,22.360,-246.067), 							
			vector():set(0.0,0.0,-1.0), 												
			"promzone",0,0,"to_prom") 													
		--news_manager.amk_send_tip_id("path_gen_prom", "path_new", 2, 25, "pda_icon")
	end
end

function create_digger_level_changers_2()
	local obj = alife():story_object(6020)--/TB3D   tech to hole
	if not obj then
		create_level_changer(6020, vector():set(8.25,20,-263.7),208967,4829, 	-- dAVROs - chgd 22April14 for extended Collector
			23,5350, vector():set(-22,-1.5,5), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"digger_stash",0,0,"to_digger") 													
		news_manager.amk_send_tip_id("path_tech_hole", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(6015)--/TB3D   tech to hole
	if obj then alife():release(obj, true) end
	create_level_changer(6015, vector():set(-21,6,5),29,5350, 	-- dAVROs - chgd 22April14 for extended Collector
		216402,4829, vector():set(11.666,22.037,-257.626), 							
	vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
	"digger_stash",0,0,"to_digger") 													
end

function create_npp1_level_changers()
	local obj = alife():story_object(98020)--/TB3D   npp1 to npp2
	if not obj then
		create_level_changer(98020, vector():set(852.322,-0.099,12.346),370690,2296, 	
			220789,2634, vector():set(849.953,-0.099,72.739), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l12_Stancia_2",0,0,"to_north_aes") 													
		news_manager.amk_send_tip_id("path_npp1_npp2", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98021)--/TB3D   npp2 to npp1
	if not obj then
		create_level_changer(98021, vector():set(850.218,-0.080,67.129),220789,2634, 	
			370014,2296, vector():set(850.939,-0.002,-8.644), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l12_Stancia",0,0,"to_aes") 													
		--news_manager.amk_send_tip_id("path_npp2_npp1", "path_new", 2, 25, "pda_icon")
	end
end

function create_npp1_research_level_changer()			--110004
	local obj = alife():story_object(97000)
	if not obj then
		create_level_changer(97000, vector():set(843.808,-0.099,464.161),214460,2654, 	
			354353,4364, vector():set(64,4.19999980926514,-274), 							
			vector():set(0.0,0.0,-1.0), 												
			"yantar_old",0,0,"to_yanold") 													
		news_manager.amk_send_tip_id("path_npp2_rs", "path_new", 2, 25, "pda_icon")
	end
end

function create_research_level_changers()
	local obj = alife():story_object(98007)--/East Pripyat monolith alter to Bar outskirts
	if not obj then
		create_level_changer(98007, vector():set(-176.911,0.545,-343.560),36488,3753, 	
		29183,1243, vector():set(80.077,-0.002,161.026), 							
		vector():set(0.0,0.0,-1.0), 												
		"l05_bar",0,0,"bar_rostok") 													
		news_manager.amk_send_tip_id("path_ep_bar", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98030)--/TB3D   recon to npp1
	if not obj then
		create_level_changer(98030, vector():set(451.774,37.561,250.975),1691912,2906, 	
			404957,2401, vector():set(919.089599609375,0.000268459320068359,-292.599273681641), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l12_stancia",0,0,"to_aes") 													
		news_manager.amk_send_tip_id("path_recon_npp1", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(6001)		--exit_to_pripyat_from_st1
	if obj then
		alife():release(obj)
	end
	obj = alife():story_object(98031)--/TB3D   npp1 to recon
	if not obj then
		create_level_changer(98031, vector():set(917.929626464844,-0.0999432504177094,-404.117004394531),112702,2273, 	
			1650477,2906, vector():set(430.769,36.704,250.772), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"aver",0,0,"to_aver") 													
		--news_manager.amk_send_tip_id("path_npp1_recon", "path_new", 2, 25, "pda_icon")
	end
end

function create_jup_level_changers()
	local obj = alife():story_object(6005)
	if not obj then
		create_level_changer(6005, vector():set(-320.786,40.706,-421.890),307410,3669, 	
			1380155,3742, vector():set(420.232,-5.473,460.006), 							
			vector():set(0.0,0.0,-1.0), 												
			"jupiter",0,0,"to_jupiter") 													
		news_manager.amk_send_tip_id("path_zat_jup", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(210)
	if not obj then
		create_level_changer(210, vector():set(428.046,0.329,472.493),1392865,3742, 	
			323588,3669, vector():set(-312.284,40.622,-424.441), 							
			vector():set(0.0,0.0,-1.0), 												
			"zaton",0,0,"to_zaton") 													
		--news_manager.amk_send_tip_id("path_jup_zat", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(834)--/TB3D   prip to east prip, 109978
	if not obj then
		create_level_changer(834, vector():set(132.427,-2.225,-70.468),235048,2241, 	
		1154,3748, vector():set(-242.462,-0.511,-242.840), 							
		vector():set(0.0,0.0,-1.0), 												
		"pripyat",0,0,"to_eprip") 													
		news_manager.amk_send_tip_id("path_prip_eprip", "path_new", 2, 25, "pda_icon")
	end
end

function create_eprip_to_prip()--/TB3D   eprip to prip, 109978
	local obj = alife():story_object(4500)
	if not obj then
		create_level_changer(4500, vector():set(-251.485,-0.508,-244.041),175,3748, 	
		231394,2241, vector():set(125.959,-2.222,-70.704), 							
		vector():set(0.0,0.0,-1.0), 												
		"l11_pripyat",0,0,"to_pripyat") 													
	end
end

function create_level_changer_zat_to_prip()
	local obj = alife():story_object(6007)
	if not obj then
		create_level_changer(6007, vector():set(429.882,28.893,-432.311),1670437,3694, 	
			179995,2265, vector():set(68.073,1.570,422.030), 							
			vector():set(0.0,0.0,-1.0), 												
			"l11_pripyat",0,0,"to_pripyat") 													
		news_manager.amk_send_tip_id("path_zat_prip", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_prip_to_jup()
	local obj = alife():story_object(6008)
	if not obj then
		create_level_changer(6008, vector():set(-75.110,-2.195,-83.506),31312,2258, 	
			1401609,3741, vector():set(433.332,27.671,-162.978), 							
			vector():set(0.0,0.0,-1.0), 												
			"jupiter",0,0,"to_jupiter") 													
		--news_manager.amk_send_tip_id("path_prip_jup", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(214)
	if not obj then
		create_level_changer(214, vector():set(450.310,27.674,-161.960),1430635,3741, 	
			38871,2258, vector():set(-63.751,-2.160,-83.666), 							
			vector():set(0.0,0.0,-1.0), 												
			"l11_pripyat",0,0,"to_pripyat") 													
		news_manager.amk_send_tip_id("path_jup_prip", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_prip_to_zat()
	local obj = alife():story_object(6009)
	if not obj then
		create_level_changer(6009, vector():set(30.9278087615967,-0.681343078613281,456.90966796875),141177,2158, 	
			1671705,3694, vector():set(430.177,30.551,-419.804), 							
			vector():set(0.0,0.0,-1.0), 												
			"zaton",0,0,"to_zaton") 													
		--news_manager.amk_send_tip_id("path_prip_zat", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_eprip_to_kras()
	local obj = alife():story_object(6010)
	if not obj then
		create_level_changer(6010, vector():set(174.983,-0.424,419.248),405302,3769, 	
			82980,5272, vector():set(132.500,5.563,-36.291), 							
			vector():set(0.0,0.0,-1.0), 												
			"l01_krasivay",0,0,"to_kras") 													
		news_manager.amk_send_tip_id("path_eprip_kras", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_esc_to_ds()
	local obj = alife():story_object(12502)
	if not obj then
		create_level_changer(12502, vector():set(337.177,19.743,267.275),584058,250, 	
			1050,4596, vector():set(-600.019,-2.241,-401.829), 							
			vector():set(0.0,0.0,-1.0), 												
			"k01_darkscape",0,0,"to_darkscape") 													
		news_manager.amk_send_tip_id("path_esc_ds", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_esc_to_fr()
	local obj = alife():story_object(12503)
	if not obj then
		create_level_changer(12503, vector():set(-123.298,-26.319,-475.104),129146,11, 	
			78564,5390, vector():set(-125.465,-9.138,89.590), 							
			vector():set(0.0,0.0,-1.0), 												
			"l01_poligon",0,0,"to_poli") 													
		news_manager.amk_send_tip_id("path_esc_fr", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_vil_to_zat()
	local obj = alife():story_object(12504)
	if not obj then
		create_level_changer(12504, vector():set(124.646,9.353,-21.337),48988,3336, 	
			307348,3665, vector():set(-320.977,19.352,614.738), 							
			vector():set(0.0,0.0,-1.0), 												
			"zaton",0,0,"to_zaton") 													
		news_manager.amk_send_tip_id("path_vil_zat", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(6006)
	if not obj then
		create_level_changer(6006, vector():set(-324.095,19.497,628.965),302414,3665, 	
			47701,3336, vector():set(115.547,6.615,-18.120), 							
			vector():set(0.0,0.0,-1.0), 												
			"lost_village",0,0,"to_lostvillage") 													
		--news_manager.amk_send_tip_id("path_zat_vil", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_gen_to_dm()			--109954 changed sid, 109980 chgd pos
	local obj = alife():story_object(11521)			--remove NS gen to hosp lc
	if obj then alife():release(obj, true) end
	obj = alife():story_object(98521)
	if not obj then
		create_level_changer(98521, vector():set(81.109,24.145,-23.029),431566,3119, 	
			1750860,4398, vector():set(277.168,6.777,67.212), 							
			vector():set(0.0,0.0,-1.0), 												
			"swamp_old",0,0,"to_swampold") 													
		news_manager.amk_send_tip_id("path_gen_dm", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_gen_to_rs()
	local obj = alife():story_object(11523)
	if not obj then
		create_level_changer(11523, vector():set(232.679,20.077,-100.495),604930,3147, 	
			592876,4384, vector():set(276,5.5,-265), 							
			vector():set(0.0,0.0,-1.0), 												
			"yantar_old",0,0,"to_yanold") 													
		news_manager.amk_send_tip_id("path_gen_rs", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_hosp_to_tunnels(is_silent)		--109984, fixed target
	local pspot = 0
	if is_silent then pspot = 1 end
	local obj = alife():story_object(6022)
	if not obj then
		create_level_changer(6022, vector():set(-63.3486709594727,19.2402877807617,561.971435546875),7863,3075, 	
			1258,3857, vector():set(71.726,-16.127,96.718),
			vector():set(0.0,0.0,-1.0), 												
			"cs_agroprom_underground",0,pspot,"to_tunnels") 													
		if not is_silent then news_manager.amk_send_tip_id("path_hosp_tunnels", "path_new", 2, 25, "pda_icon") end
	end
end

function create_level_changer_rsch_to_hole()
	local obj = alife():story_object(6021)
	if not obj then
		local sobj = create_level_changer(6021, vector():set(-72.231,-13.827,182.428),207428,4384, 	
			142,5360, vector():set(7.5,-1.70000004768372,0.300000011920929), 							
			vector():set(0.0,0.0,-1.0), 												
			"digger_stash",0,1,"to_digger") 													
		news_manager.amk_send_tip_id("path_rsch_hole", "path_new", 2, 25, "pda_icon")
		if sobj then
			if level.map_has_object_spot(sobj.id, "crlc_biggest") == 0 then
				level.map_add_object_spot(sobj.id, "crlc_biggest", "zep_doc_18_hint")
			end
			--TB3D_Services.give_info("tb3d_digger_start")
		end
	end
end

function create_level_changer_rsch_to_wait()
	local obj = alife():story_object(98012)
	if not obj then
		create_level_changer(98012, vector():set(195.106,4.276,279.122),504124,4375, 	
			1171263,4027, vector():set(153.528,8.561,-21.516), 							
			vector():set(0.0,0.0,-1.0), 												
			"predbannik",0,0,"to_pred") 													
		news_manager.amk_send_tip_id("path_rsch_wait", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_rsch_to_prom()
	local obj = alife():story_object(368)
	if not obj then
		create_level_changer(368, vector():set(-279.299987792969,6.50362586975098,35),496,4339, 	
			247093,4865, vector():set(26.384,6.256,-623.706), 							
			vector():set(0.0,0.0,-1.0), 												
			"promzone",0,0,"to_prom") 													
		news_manager.amk_send_tip_id("path_rsch_tech", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_tech_to_broken()
	local obj = alife():story_object(257)
	if not obj then
		create_level_changer(257, vector():set(-126,21,-4),7011,4696, 	
			1046246,4592, vector():set(412.581,-0.077,96.606), 							
			vector():set(0.0,0.0,-1.0), 												
			"hiding_road",0,0,"to_hiding") 													
		news_manager.amk_send_tip_id("path_tech_broken", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D   chaes to backwater
function create_level_changer_chaes_to_zat(is_silent)
	local pspot = 0
	if is_silent then pspot = 1 end
	local obj = alife():story_object(98997)
	if not obj then
		create_level_changer(98997, vector():set(1061.978,-0.098,-2.998),472711,2280, 	
		311466,3669, vector():set(-318.693,40.698,-421.770), 							
		vector():set(0.0,0.0,-1.0), 												
		"zaton",0,pspot,"to_zaton") 													
		if not is_silent then news_manager.amk_send_tip_id("path_sc_zat", "path_new", 2, 25, "pda_icon") end
	end
end

--/TB3D   dist ctr to dead marshes
function create_level_changer_kras_to_dm()
	local obj = alife():story_object(272)
	if not obj then
		create_level_changer(272, vector():set(204.411,9.787,-6.786),94955,5271, 	
		453753,4386, vector():set(-321.601,2.262,68.229), 							
		vector():set(0.0,0.0,-1.0), 												
		"swamp_old",0,0,"to_swampold") 													
		news_manager.amk_send_tip_id("path_kras_dm", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_dc_to_cem()
	local obj = alife():story_object(6013)
	if not obj then
		create_level_changer(6013, vector():set(-68.667,-10.243,392.379),278918,3626, 	
			23027,5334, vector():set(11.593,0.001,-130.282), 							
			vector():set(0.0,0.0,-1.0), 												
			"l04_pogost",0,0,"to_pogost") 													
		--news_manager.amk_send_tip_id("path_dc_cem", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(6012)
	if not obj then
		create_level_changer(6012, vector():set(16.762,-0.009,-137.659),23020,5334, 	
		274071,3626, vector():set(-72.816,-10.080,387.278), 							
			vector():set(0.0,0.0,-1.0), 												
			"dead_city",0,0,"to_deadcity") 													
		news_manager.amk_send_tip_id("path_cem_dc", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D  dcity to gen
function create_level_changer_dcity_to_gen()
	local obj = alife():story_object(98017)
	if not obj then
		create_level_changer(98017, vector():set(237.496,-10.904,168.114),533057,3658, 	
		410525,3117, vector():set(63.672,32.730,-551.895), 							
		vector():set(0.0,0.0,-1.0), 												
		"generators",0,0,"to_generators") 													
		news_manager.amk_send_tip_id("path_dcity_gen", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98018)--/TB3D   gen to dcity
	if not obj then
		create_level_changer(98018, vector():set(63.674,32.938,-558.229),410516,3117, 	
			528170,3658, vector():set(225.146,-10.925,160.659), 							
		vector():set(0.0,0.0,-1.0), 												
		"dead_city",0,0,"to_dcity") 													
		--news_manager.amk_send_tip_id("path_gen_dcity", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D   mil to npp1
function create_level_changer_mil_to_npp1()
	local obj = alife():story_object(98019)
	if not obj then
		create_level_changer(98019, vector():set(113.081,-8.897,51.181),401225,1558, 	
			404957,2401, vector():set(919.089599609375,0.000268459320068359,-292.599273681641), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l12_Stancia",0,0,"to_aes") 													
		news_manager.amk_send_tip_id("path_mil_npp1", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D   tech to wait
function create_level_changer_tech_to_wait()
	local obj = alife():story_object(258)
	if not obj then
		create_level_changer(258, vector():set(88,7,514),372963,4941, 	
			74002,3877, vector():set(-571.023,18.857,414.774), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"predbannik",0,0,"to_pred") 													
		news_manager.amk_send_tip_id("path_tech_wait", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D   wait to broken
function create_level_changer_wait_to_broken()
	local obj = alife():story_object(241)
	if not obj then
		create_level_changer(241, vector():set(199.24885559082,-29.237434387207,510.039459228516),1216397,4029, 	
			979642,4578, vector():set(332.866,0.002,435.201), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"hiding_road",0,0,"to_hiding") 													
		news_manager.amk_send_tip_id("path_wait_broke", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D   dead marshes to tech and back
function create_level_changer_dm_to_tech()
	local obj = alife():story_object(98022)
	if not obj then
		create_level_changer(98022, vector():set(282.578,4.523,285.959),1760211,4393, 	
			8823,4693, vector():set(-123.635,21.287,-252.708), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"promzone",0,0,"to_prom") 													
		news_manager.amk_send_tip_id("path_dm_tech", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98023)--/TB3D   tech to dead marshes
	if not obj then
		create_level_changer(98023, vector():set(-129.686,21.558,-254.180),5176,4693, 	
			1742030,4393, vector():set(273.235,2.734,285.045), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"swamp_old",0,0,"to_swampold") 													
		--news_manager.amk_send_tip_id("path_tech_dm", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D   black market to dist and back
function create_level_changer_bm_to_dist()
	local obj = alife():story_object(98024)
	if not obj then
		create_level_changer(98024, vector():set(-20.390,-0.756,-45.199),8068,5312, 	
			2158,5280, vector():set(-66.961,-1.180,76.718), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l01_krasivay",0,0,"to_kras") 													
		news_manager.amk_send_tip_id("path_bm_kras", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98025)--/TB3D   dist to black market
	if not obj then
		create_level_changer(98025, vector():set(-78.688,-1.713,74.842),982,5280,
			8083,5312, vector():set(-20.282,-0.506,-34.170), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l03_rinok",0,0,"to_rinok") 													
		--news_manager.amk_send_tip_id("path_kras_bm", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D   gen to hosp
function create_level_changer_gen_hosp()
	local obj = alife():story_object(11521)
	if not obj then
		create_level_changer(11521, vector():set(78.6242141723633,25.8780784606934,-7.34956836700439),428337,3119, 	
			7339,3070, vector():set(-74.7672271728516,28.6663703918457,861.699340820313), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"hospital",0,0,"to_hospital") 													
		news_manager.amk_send_tip_id("path_gen_hosp", "path_new", 2, 25, "pda_icon")
	end
end

--/TB3D   radar to red forest
function create_level_changer_rad_red()
	local obj = alife():story_object(14091)
	if not obj then
		create_level_changer(14091, vector():set(384.514343261719,-52.8748245239258,-360.6728515625), 113746, 2067,	
			24245,3253, vector():set(-58.5255355834961,1.89999991562217e-005,96.357780456543), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"red_forest",0,0,"to_redforest") 													
		--news_manager.amk_send_tip_id("path_rad_red", "path_new", 2, 25, "pda_icon")
		TB3D_Services.give_info("info_way_arhara_radar_forest")
	end
end

--/TB3D   research to rostok
function create_level_changer_res_ros()
	local obj = alife():story_object(98032)
	if not obj then
		create_level_changer(98032, vector():set(249.766,3.922,-5.446),564445,4383,	
			69221,1274, vector():set(324.230,4.409,-65.961), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l05_bar",0,0,"to_bar") 													
		news_manager.amk_send_tip_id("path_res_ros", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98033)
	if not obj then
		create_level_changer(98033, vector():set(327.201,5.010,-50.553),69226,1274,	
			557670,4383, vector():set(243.862,4.248,-8.405), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"yantar_old",0,0,"to_yanold") 													
		--news_manager.amk_send_tip_id("path_res_ros", "path_new", 2, 25, "pda_icon")
	end
end

function create_level_changer_ww_vill()
	local obj = alife():story_object(201)
	if not obj then
		create_level_changer(201, vector():set(-447.68701171875,0,-467.567993164063),9015,4675,	
			30090,3361, vector():set(-231.69677734375,0.269413977861404,444.110717773438), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"marsh",0,0,"to_marsh") 													
	end
	obj = alife():story_object(200)
	if not obj then
		create_level_changer(200, vector():set(-113,-0.699999988079071,421),602562,4658,	
			28593,3331, vector():set(49.356128692627,4.22816610336304,94.2022323608398), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"lost_village",0,0,"to_lostvillage") 													
	end
end

function create_level_changer_hospital_agroprom()
	local obj = alife():story_object(97104)
	if not obj then
		create_level_changer(97104, vector():set(-65.475,19.128,564.144),7863,3075,	
			406637,692, vector():set(198.168823242188,0.69904363155365,-238.110443115234), 							
		vector():set(0,-2,0), 												
		"l03_agroprom",0,0,"to_agroprom") 													
	end
end

function create_level_changer_marsh_yantar()
	local obj = alife():story_object(98036)
	if not obj then
		create_level_changer(98036, vector():set(55.827,10.646,530.034),169339,3484,	
			13909,1487, vector():set(-71.148,-0.913,-348.157), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l08_yantar",0,0,"to_yantar") 													
	end
end

function create_level_changer_dv_npp1()
	local obj = alife():story_object(98994)		--npp1 to dv
	if not obj then
		create_level_changer(98994, vector():set(998.191,-0.101,-318.105),420500,2401,	
			338266,911, vector():set(140.190,-1.973,80.522), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l04_darkvalley",0,0,"to_darkvalley") 													
	end
	obj = alife():story_object(98995)			--dv to npp1
	if not obj then
		create_level_changer(98995, vector():set(147.441,-2.362,89.665),347219,911,	
			420500,2401, vector():set(988.172,-0.101,-317.682), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l12_stancia",0,0,"to_aes") 													
	end
end

function create_level_changer_tunnels_tech()
	local obj = alife():story_object(98993)
	if not obj then
		create_level_changer(98993, vector():set(103.693,-19.394,11.675),2608,3867,	
			134517,4785, vector():set(-33.216,21.643,-89.481), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"promzone",0,1,"to_prom") 													
	end
end

function create_level_changer_prom_jup()
	local obj = alife():story_object(98991)
	if not obj then
		create_level_changer(98991, vector():set(-114.572,1.175,521.038),18039,4706,
			938805,3728, vector():set(130.000,-2.969,439.370),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"jupiter",0,0,"to_jupiter")
	end
	obj = alife():story_object(98992)
	if not obj then
		create_level_changer(98992, vector():set(131.082,-3.269,450.301),940028,3728,
			25598,4716, vector():set(-107.684,0.922,512.913),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"promzone",0,0,"to_prom")
	end
end

function create_level_changer_jup_cem()
	local obj = alife():story_object(98989)
	if not obj then
		create_level_changer(98989, vector():set(477.116,-5.858,-29.440),1468934,3744,
			5,5338, vector():set(-83.018,0.009,-140.435),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l04_pogost",0,0,"to_pogost")
		news_manager.amk_send_tip_id("path_jup_cem", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98990)
	if not obj then
		create_level_changer(98990, vector():set(-83.428,0.009,-104.344),46,5338,
			1468949,3744, vector():set(477.088,-5.935,-23.353),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"jupiter",0,0,"to_jupiter")
	end
end

function create_level_changer_cem_gen()
	local obj = alife():story_object(98987)
	if not obj then
		create_level_changer(98987, vector():set(36.226,0.001,-150.856),22228,5332,
			125673,3088, vector():set(-182.702,46.591,-559.591),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"generators",0,0,"to_generators")
		news_manager.amk_send_tip_id("path_cem_gen", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98988)
	if not obj then
		create_level_changer(98988, vector():set(-187.703,45.926,-566.271),120141,3088,
			22228,5332, vector():set(33.503,0.002,-144.798),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l04_pogost",0,0,"to_pogost")
	end
end

function create_level_changer_ww_hos()
	local obj = alife():story_object(98985)
	if not obj then
		create_level_changer(98985, vector():set(-452.388,4.915,333.835),2241,4678,
			4958,3066, vector():set(-79.545,35.851,554.877),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"hospital",0,0,"to_hospital")
		news_manager.amk_send_tip_id("path_ww_hos", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98986)
	if not obj then
		create_level_changer(98986, vector():set(-88.113,36.597,550.038),3028,3066,
			12445,4678, vector():set(-446.198,5.350,329.906),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"dark_forest",0,0,"to_darkforest")
	end
end

function create_level_changer_hos_f1()
	local obj = alife():story_object(98983)
	if not obj then
		create_level_changer(98983, vector():set(-103.804,33.774,903.771),462,3038,
			26883,4679, vector():set(-245.133,13.877,-270.652),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"level_f-1",0,0,"to_f1")
		news_manager.amk_send_tip_id("path_hos_f1", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98984)
	if not obj then
		create_level_changer(98984, vector():set(-251.835,14.574,-279.448),19965,4679,
			1972,3038, vector():set(-77.963,32.101,901.170),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"hospital",0,0,"to_hospital")
	end
end

function create_level_changer_hr_dm()
	local obj = alife():story_object(98981)
	if not obj then
		create_level_changer(98981, vector():set(-263.058,-0.077,112.026),73426,4414,
			736819,4386, vector():set(-191.819,-6.428,163.994),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"swamp_old",0,0,"to_swampold")
		news_manager.amk_send_tip_id("path_hr_dm", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98982)
	if not obj then
		create_level_changer(98982, vector():set(-190.637,-6.441,173.634),739859,4386,
			102403,4414, vector():set(-234.992,-0.077,123.839),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"hiding_road",0,0,"to_hiding")
	end
end

function create_level_changer_resrch_eprip()
	local obj = alife():story_object(98979)
	if not obj then
		create_level_changer(98979, vector():set(-235.224,18.617,114.199),31415,4345,
			481065,3770, vector():set(308.077,-0.509,157.377),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"pripyat",0,0,"to_eprip")
		news_manager.amk_send_tip_id("path_rsch_eprip", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98980)
	if not obj then
		create_level_changer(98980, vector():set(315.477,-0.477,153.146),483085,3770,
			40177,4345, vector():set(-227.653,18.618,109.871),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"yantar_old",0,0,"to_yanold")
	end
end

function create_level_changer_eprip_npp1()
	local obj = alife():story_object(98977)
	if not obj then
		create_level_changer(98977, vector():set(189.241,-0.505,-79.383),419044,3768,
			388363,2400, vector():set(-27.074,-0.101,-361.010),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l12_stancia",0,0,"to_aes")
		news_manager.amk_send_tip_id("path_eprip_npp1", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98978)
	if not obj then
		create_level_changer(98978, vector():set(-41.325,-0.101,-361.503),388363,2400,
			411391,3766, vector():set(181.399,-0.511,-78.597),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"pripyat",0,0,"to_eprip")
	end
end

function create_level_changer_zat_eprip()
	local obj = alife():story_object(98975)
	if not obj then
		create_level_changer(98975, vector():set(567.577,-7.392,-187.127),1838570,3696,
			730,3749, vector():set(-246.119,-0.508,-83.164),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"pripyat",0,0,"to_eprip")
		news_manager.amk_send_tip_id("path_eprip_zaton", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(98976)
	if not obj then
		create_level_changer(98976, vector():set(-254.789,-0.510,-82.706),11,3749,
			1835226,3696, vector():set(560.948,-7.400,-189.748),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"zaton",0,0,"to_zaton")
	end
end

function create_level_changer_npp2_x14()
	local obj = alife():story_object(99030)
	if not obj then
		create_level_changer(99030, vector():set(200.798,-0.101,383.703),50137,2538,
			2767,5380, vector():set(18.256,-34.500,-23.915),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 	--faces north											
		"lab_x14",0,0,"to_labx14")
		news_manager.amk_send_tip_id("path_npp2_x14", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(99031)
	if not obj then
		create_level_changer(99031, vector():set(-0.016,-34.570,-4.893),1996,5377,
			50137,2538, vector():set(206.838,-0.100,377.046),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 				---43.560,-0.103,-77.855),10114,2371								
		"l12_stancia_2",0,1,"to_north_aes")
	end
	obj = alife():story_object(99034)					--109980, gate south of viaduct on tracks to ne ds
	if not obj then
		create_level_changer(99034, vector():set(369.062,0.150,-404.876),389488,2400,
			655223,4630, vector():set(238.976,-2.373,652.449),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 	--faces north											
		"k01_darkscape",0,0,"to_darkscape")
		news_manager.amk_send_tip_id("path_dark_npp", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(99035)
	if not obj then
		create_level_changer(99035, vector():set(239.752,-2.741,662.589),655959,4630,
			389488,2400, vector():set(369.264,0.150,-391.710),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l12_stancia",0,0,"to_aes")
	end
	obj = alife():story_object(99036)					--109980, far west around fence
	if not obj then
		create_level_changer(99036, vector():set(-87.726,-0.002,-154.629),386473,2400,
			54580,2538, vector():set(149.666,0.149,331.501),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 	--faces north											
		"l12_stancia_2",0,0,"to_north_aes")
	end
	obj = alife():story_object(99037)
	if not obj then
		create_level_changer(99037, vector():set(143.250,0.149,336.971),54580,2538,
			386473,2400, vector():set(-89.656,-0.000,-168.756),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l12_stancia",0,0,"to_aes")
	end
end

function create_level_changer_npp2_npp1()		--110004, for gold chunks and diary quests
	local obj = alife():story_object(99043)														--109998, west gate npp1 to npp2
	if not obj then
		create_level_changer(99043, vector():set(-43.049,-0.101,-69.817),10377,2371,
			10118,2517, vector():set(-41.458,-0.038,68.393),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 	--faces north											
			"l12_stancia",0,0,"to_north_aes") 													
	end
end

function create_level_changer_radar_ros()		--109980, when talked to Max about Cube
	local obj = alife():story_object(99032)
	if not obj then
		create_level_changer(99032, vector():set(116.783,3.406,-87.193),48427,1875,
			783,1340, vector():set(-285.427,0.099,192.574),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 	--faces north											
		"l06_rostok",0,0,"to_rostok")
		news_manager.amk_send_tip_id("path_radar_rostok", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(99033)
	if not obj then
		create_level_changer(99033, vector():set(-289.796,0.098,192.582),295,1340,
			47737,1875, vector():set(114.094,0.664,-82.640),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l10_radar",0,0,"to_radar")
	end
end

function create_level_changer_jupu_tunnels()		--109982, when x14 done
	local obj = alife():story_object(99038)
	if not obj then
		create_level_changer(99038, vector():set(-8.108,0.077,70.424),8133,3784,				--small tunnel off main room to southern tunnels
			1374,3858, vector():set(73.854,-16.122,99.230),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 	--faces north											
			"cs_agroprom_underground",0,0,"to_tunnels") 													
		news_manager.amk_send_tip_id("path_jupu_tunnels", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(99039)
	if not obj then
		create_level_changer(99039, vector():set(74.631,-16.117,104.100),1395,3858,				--w. end of flood tunnel
			10926,3784, vector():set(-3.164,0.073,62.599),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"jupiter_underground",0,0,"to_jupu")
	end
end

function create_level_changer_tunnels_to_red_forest(is_silent)		--109984, fixed target
	local pspot = 0
	if is_silent then pspot = 1 end
	local obj = alife():story_object(99040)
	if not obj then
		create_level_changer(99040, vector():set(-99.792,0.761,29.000),12285,3240,				--tunnel by camp
			1536,3868, vector():set(81.072,-20.404,-181.405), 							
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 	--faces north											
			"cs_agroprom_underground",0,pspot,"to_tunnels") 													
		if not is_silent then news_manager.amk_send_tip_id("path_redf_tunnels", "path_new", 2, 25, "pda_icon") end
	end
	obj = alife():story_object(6014)
	if not obj then
		create_level_changer(6014, vector():set(85.695,-16.928,-189.877),1579,3868,				--tunnel with fire
			11416,3240, vector():set(-104.958,0.638,22.358),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"red_forest",0,0,"to_redforest")
	end
end

function create_level_changer_npp1_to_radar()													--109982, hunt lc stash 14
	local obj = alife():story_object(99041)
	if not obj then
		create_level_changer(99041, vector():set(116.663,-0.100,-76.573),61738,2376,			--hunt lc to radar
			41971,1946, vector():set(94.869,2.475,86.134),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 	--faces north											
			"l10_radar",0,0,"to_radar") 													
		news_manager.amk_send_tip_id("path_npp1_radar", "path_new", 2, 25, "pda_icon")
	end
	obj = alife():story_object(99042)
	if not obj then
		create_level_changer(99042, vector():set(92.214,6.541,94.695),40936,1947,				--far corner break in wall
			66129,2376, vector():set(131.427,-0.101,-75.964),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 												
		"l12_stancia",0,0,"to_aes")
	end
end

function create_level_changer_ff_to_rf()													--110000, puzir_level_changer_red_forest
	local obj = alife():story_object(11528)
	if not obj then
		create_level_changer(11528, vector():set(-220.088,-0.002,47.390),14129,2881,			--e. rocks
			155179,3321, vector():set(257.117,-1.451,-311.102),
		vector():set(-2.02234588186911e-007,-1.08743614427812e-015,-5.37710276304892e-009), 	--faces north											
			"red_forest",0,0,"to_redforest") 													
	end
end

--[cs_agroprom_underground]: (85.695,-16.928,-189.877),1579,3868)
--[cs_agroprom_underground]: (83.660,-20.232,-186.914),1579,3868)

--[jupiter_underground]: (55.961,19.181,257.618),33364,3799)			--big tunnel right before north exits to ???
--[jupiter_underground]: (48.390,15.113,257.678),33364,3799)
--[cs_agroprom_underground]: (121.710,-16.127,61.468),4584,3869)		--e. end of flood tunnel
--[cs_agroprom_underground]: (114.998,-16.100,59.063),3848,3863)

--/=====================================================================================================================================
