-- TB3D 1.1.0.0.1.0 population controller and respawn services, gar_dolg and x18_ chgd, cleanup, has item, atp, val_krovosos,
-- atp_brigada5, military_neytral_respawn, clsids, new levels, labx8, dead city, labx8, village respawns in cordon, dog_rush,
-- false spawns, factory snorks, gar_se, scope, rostok dogs, esc_ respawns, agro final, cleanup, dont_spawn_online, predbannik,
-- l02_dd, yantar cleanup, pol_ respawns, pred, controller2_1, harsh environment, warehouses after storm, av_peshera, optimized,
-- pri_monolith_10, vampire, specnaz_dead, generators, esc2_ respawns, is_spawner, sepaerate can_go_online for monsters and stalkers,
-- radar, get_level_index, dead city, harsh env spawns, dcity_obmorok, predbannik_trader, cat and pilgrim in bar, warehouse respawns,
-- m_polt in mw, stalk_hosp, bandit stroyka
function my_ver() return "1.1.0.0.1.0" end
-----over population control----
local string_find = string.find
local string_sub = string.sub

local removed_count = 0

local stalkers = 0
local dogs = 0
local cats = 0
local rats = 0
--local crows = 0							--109989, crows spawn after fixer
local pseudodogs = 0
local tushkanos = 0
local snorks = 0
local boars = 0
local tarakans = 0
local flesh = 0
local zombies = 0
local scelets = 0
local ghouls = 0
local bibliotekar = 0
local fractures = 0
local burers = 0
local gigants = 0
local bloodsuckers = 0
local werewolves = 0
local chimera = 0
local controllers = 0
local poltergeist = 0
local phantoms = 0
local obj_name

function population_control(obj, sect)
	local is_fixed = false
	if sect == "respawn" then
		if obj.amk_name then obj_name = obj.amk_name else obj_name = obj:name() end
	else
		obj_name = sect
	end
	if obj_name then
		--if TB3D_Modders.use_population_report == true then TB3D_Services.packet_alert("tb3d pop control: object["..utils.to_str(obj_name).."] sect["..utils.to_str(sect).."]") end
		if string_find(obj_name, "^stalker")
		  or sect == "m_barman" or sect == "m_osoznanie" then
				stalkers = stalkers + 1
		elseif string_find(obj_name, "^psy_dog") then
			if pseudodogs + 1 > TB3D_Modders.max_pseudodogs then
				is_fixed = true
			else
				pseudodogs = pseudodogs + 1
			end
		elseif string_find(obj_name, "^pseudodog") then
			if pseudodogs + 1 > TB3D_Modders.max_pseudodogs then
				is_fixed = true
			else
				pseudodogs = pseudodogs + 1
			end
		elseif string_find(obj_name, "^dog_") then
			if dogs + 1 > TB3D_Modders.max_dogs then
				is_fixed = true
			else
				dogs = dogs + 1
			end
		elseif string_find(obj_name, "^cat_")
		  or string_find(obj_name, "^kot_") then
			if cats + 1 > TB3D_Modders.max_cats then
				is_fixed = true
			else
				cats = cats + 1
			end
		elseif string_find(obj_name, "^rat_")
		  or string_find(obj_name, "^ratstrong")
		  or string_find(obj_name, "^ratnormal")
		  or string_find(obj_name, "^ratweak") then
			if rats + 1 > TB3D_Modders.max_rats then
				is_fixed = true
			else
				rats = rats + 1
			end
		elseif string_find(obj_name, "^tushkano") then
			if tushkanos + 1 > TB3D_Modders.max_tushkanos then
				is_fixed = true
			else
				tushkanos = tushkanos + 1
			end
		elseif string_find(obj_name, "^snork") then
			if snorks + 1 > TB3D_Modders.max_snorks then
				is_fixed = true
			else
				snorks = snorks + 1
			end
		elseif string_find(obj_name, "^boar") then
			if boars + 1 > TB3D_Modders.max_boars then
				is_fixed = true
			else
				boars = boars + 1
			end
		elseif string_find(obj_name, "^tarakan") then
			if tarakans + 1 > TB3D_Modders.max_tarakans then
				is_fixed = true
			else
				tarakans = tarakans + 1
			end
		elseif string_find(obj_name, "^flesh") then
			if flesh + 1 > TB3D_Modders.max_flesh then
				is_fixed = true
			else
				flesh = flesh + 1
			end
		elseif string_find(obj_name, "^zombie") then		
			if zombies + 1 > TB3D_Modders.max_zombies then
				is_fixed = true
			else
				zombies = zombies + 1
			end
		elseif string_find(obj_name, "^scelet") then		
			if scelets + 1 > TB3D_Modders.max_scelets then
				is_fixed = true
			else
				scelets = scelets + 1
			end
		elseif string_find(obj_name, "^ghoul") then		
			if ghouls + 1 > TB3D_Modders.max_ghouls then
				is_fixed = true
			else
				ghouls = ghouls + 1
			end
		elseif sect == "bibliotekar" then		
			if bibliotekar + 1 > TB3D_Modders.max_bibliotekar then
				is_fixed = true
			else
				bibliotekar = bibliotekar + 1
			end
		elseif string_find(obj_name, "^fracture") then		
			if fractures + 1 > TB3D_Modders.max_fractures then
				is_fixed = true
			else
				fractures = fractures + 1
			end
		elseif string_find(obj_name, "^burer") then		
			if burers + 1 > TB3D_Modders.max_burers then
				is_fixed = true
			else
				burers = burers + 1
			end
		elseif string_find(obj_name, "^gigant") then		
			if gigants + 1 > TB3D_Modders.max_gigants then
				is_fixed = true
			else
				gigants = gigants + 1
			end
		elseif string_find(obj_name, "^bloodsucker") then		
			if bloodsuckers + 1 > TB3D_Modders.max_bloodsuckers then
				is_fixed = true
			else
				bloodsuckers = bloodsuckers + 1
			end
		elseif string_find(obj_name, "^werewolf") then		
			if werewolves + 1 > TB3D_Modders.max_werewolves then
				is_fixed = true
			else
				werewolves = werewolves + 1
			end
		elseif string_find(obj_name, "^chimera")
		  or string_find(obj_name, "^electro") then		
			if chimera + 1 > TB3D_Modders.max_chimera then
				is_fixed = true
			else
				chimera = chimera + 1
			end
		elseif string_find(obj_name, "^m_controller") then		
			if controllers + 1 > TB3D_Modders.max_controllers then
				is_fixed = true
			else
				controllers = controllers + 1
			end
		elseif string_find(obj_name, "^m_poltergeist") then		
			if poltergeist + 1 > TB3D_Modders.max_poltergeist then
				is_fixed = true
			else
				poltergeist = poltergeist + 1
			end
		elseif string_find(obj_name, "phantom") then		
			if phantoms + 1 > TB3D_Modders.max_phantoms then
				is_fixed = true
			else
				phantoms = phantoms + 1
			end
		end
	end
	if is_fixed == true then
		if TB3D_Modders.use_population_report == true then TB3D_Services.packet_alert("tb3d pop control: object["..utils.to_str(obj_name).."] removed") end
		removed_count = removed_count + 1
	end
	return is_fixed
end

function population_report()
	if TB3D_Modders.use_population_report == true then
		TB3D_Services.packet_alert("tb3d population control: detailed population report")
		TB3D_Services.packet_alert("tb3d population control: stalkers["..utils.to_str(stalkers).."]")
		TB3D_Services.packet_alert("tb3d population control: dogs["..utils.to_str(dogs).."]")
		TB3D_Services.packet_alert("tb3d population control: cats["..utils.to_str(cats).."]")
		TB3D_Services.packet_alert("tb3d population control: rats["..utils.to_str(rats).."]")
		TB3D_Services.packet_alert("tb3d population control: pseudodogs["..utils.to_str(pseudodogs).."]")
		TB3D_Services.packet_alert("tb3d population control: tushkanos["..utils.to_str(tushkanos).."]")
		TB3D_Services.packet_alert("tb3d population control: snorks["..utils.to_str(snorks).."]")
		TB3D_Services.packet_alert("tb3d population control: boars["..utils.to_str(boars).."]")
		TB3D_Services.packet_alert("tb3d population control: tarakans["..utils.to_str(tarakans).."]")
		TB3D_Services.packet_alert("tb3d population control: flesh["..utils.to_str(flesh).."]")
		TB3D_Services.packet_alert("tb3d population control: zombies["..utils.to_str(zombies).."]")
		TB3D_Services.packet_alert("tb3d population control: scelets["..utils.to_str(scelets).."]")
		TB3D_Services.packet_alert("tb3d population control: ghouls["..utils.to_str(ghouls).."]")
		TB3D_Services.packet_alert("tb3d population control: bibliotekar["..utils.to_str(bibliotekar).."]")
		TB3D_Services.packet_alert("tb3d population control: fractures["..utils.to_str(fractures).."]")
		TB3D_Services.packet_alert("tb3d population control: burers["..utils.to_str(burers).."]")
		TB3D_Services.packet_alert("tb3d population control: gigants["..utils.to_str(gigants).."]")
		TB3D_Services.packet_alert("tb3d population control: bloodsuckers["..utils.to_str(bloodsuckers).."]")
		TB3D_Services.packet_alert("tb3d population control: werewolves["..utils.to_str(werewolves).."]")
		TB3D_Services.packet_alert("tb3d population control: chimera["..utils.to_str(chimera).."]")
		TB3D_Services.packet_alert("tb3d population control: controllers["..utils.to_str(controllers).."]")
		TB3D_Services.packet_alert("tb3d population control: poltergeist["..utils.to_str(poltergeist).."]")
		TB3D_Services.packet_alert("tb3d population control: phantoms["..utils.to_str(phantoms).."]")
	end
	TB3D_Services.info_alert("tb3d population control: trimmed["..utils.to_str(removed_count).."] from population")
end

------------------------------ offline alife ------------------
local maps={	"zaton",	--(1) default for get_rnd_level()
				--(3) after agro documents
				 "l02_garbage", "l03_agroprom",
				--(7) after DV
				"l01_escape", "l04_darkvalley", "peshera", "dark_forest",
				--(12) after yantar
				"l06_rostok", "l08_yantar", "l04u_labx18", "l03u_agr_underground", "red_forest",
				--(18) after radar
				"l07_military", "l10_radar", "l11_pripyat", "l10u_bunker", "labx8", "marsh",
				--(23) after npp1 
				"pripyat", "l12_stancia", "warlab", "l08u_brainlab", "atp_for_test22",
				--(29) after generators activated 
				"generators", "lost_village", "aver", "puzir", "av_peshera", "jupiter",
				--(33) after backwater
				 "l12_stancia_2", "l12u_control_monolith", "l12u_sarcofag", "dead_city",
				--(38) collector freeplay (1)
				 "jupiter_underground", "limansk", "hospital", "k01_darkscape", "123_final_battle",
				--(49) collector freeplay (2)
				"l05_bar", "cs_agroprom_underground", "predbannik", "yantar_old", "swamp_old",
				"hiding_road", "level_f-1", "promzone", "l01_krasivay", "l02_dd", "l03_rinok",
				--(54) collector freeplay (3+)
				"l04_pogost", "l05_vokzal", "digger_stash", "lab_x14", "l01_poligon"
		}
		
function get_rnd_level()	--off_line_alife
	local table_range = 1				-- start, use zaton for dummy fill
	if TB3D_Modders.open_alife_in_SOC == true or has_alife_info("tb3d_respawn_level2") then
		table_range = 54				-- all places open, still in dev
	elseif extended_levels == true then
		local levelnum = TB3D_Services.get_level_up() 
		if levelnum > 2 then
			table_range = 54				-- freeplay level 3+
		elseif levelnum > 1 then
			table_range = 49				-- freeplay level 2
		else
			table_range = 38				-- freeplay level 1
		end
	elseif has_alife_info("vkluchit_generator_done") then
		table_range = 33				-- after backwater
	elseif has_alife_info("tb3d_teleport_zaton") then
		table_range = 29				-- after generators activated
	elseif has_alife_info("tb3d_wish_granted") then
		table_range = 23				-- after wish granter
	elseif has_alife_info("bar_deactivate_radar_done") then
		table_range = 18				-- after radar deactivated
	elseif has_alife_info("bar_rescue_research_done") then
		table_range = 12				-- after yantar first time
	elseif has_alife_info("val_x18_conclusion_info") then
		table_range = 7				-- after dv first time
	elseif has_alife_info("agroprom_military_case_done") then
		table_range = 3				-- after agro docs
	end
	return maps[math.random(table_range)]
end

function get_clsid(name)	--for creatures in respawner with object but no clsid
	local cls_id = nil
	if string_find(name, "cat_") or string_find(name, "_cat")then
		cls_id = clsid.cat_s
	elseif string_find(name, "ghoul") then
		cls_id = clsid.zombie_s
	elseif string_find(name, "bloodsucker") or string_find(name, "krovosos") then
		cls_id = clsid.bloodsucker_s
	elseif string_find(name, "tush") or string_find(name, "tarakan") or string_find(name, "rat_") or string_find(name, "_rat") then
		cls_id = clsid.tushkano_s
	elseif string_find(name, "snork") then
		cls_id = clsid.snork_s
	elseif string_find(name, "gigant") or string_find(name, "giant") then
		cls_id = clsid.gigant_s
-- ---------------------109999 test for the minimap spot icon - aleks1970 ----------------------------
	elseif string_find(name, "werewolf") or string_find(name, "deathclaw") then
		cls_id = clsid.chimera_s	--clsid.werewolf_s 
	elseif string_find(name, "bibliotekar") then
		cls_id = clsid.fracture_s	--clsid.bibliotekar_s
-- ------------------- test for the minimap spot icon -END- - aleks1970 ------------------------
	elseif string_find(name, "himera") then
		cls_id = clsid.chimera_s
	elseif string_find(name, "fracture") then
		cls_id = clsid.fracture_s
	elseif string_find(name, "scelet") or string_find(name, "zomb") then
		cls_id = clsid.zombie_s
	elseif string_find(name, "boar") or string_find(name, "kaban") then
		cls_id = clsid.boar_s
	elseif string_find(name, "flesh") then
		cls_id = clsid.flesh_s
	elseif string_find(name, "controller") or string_find(name, "controler") then
		cls_id = clsid.controller_s
	elseif string_find(name, "burer") then
		cls_id = clsid.burer_s
	elseif string_find(name, "poltergeist") then
		cls_id = clsid.poltergeist_s
	elseif string_find(name, "pseudodog") then
		cls_id = clsid.pseudodog_s
	elseif string_find(name, "psy_dog_p") then
		cls_id = clsid.psy_dog_phantom_s
	elseif string_find(name, "psy_dog") then
		cls_id = clsid.psy_dog_s
	elseif string_find(name, "dog") then
		cls_id = clsid.dog_s
	end
	return cls_id
end

function can_start_respawn(obj)			--called by se_respawn, creatures only from amk_respawns
	local result = false
	if obj and db.actor then
		if (obj.m_game_vertex_id > 3850 and obj.m_game_vertex_id < 4658)						--wasted woodland ok
		  or obj.m_game_vertex_id > 4678 then													--ignore new levels in stalker
			result = TB3D_Services.is_collector(80) or TB3D_Modders.open_alife_in_SOC
		else
			result = true
		end
		if TB3D_Modders.use_respawn_message then TB3D_Services.packet_alert("tb3d pop control: can_start_respawn["..utils.to_str(obj:name()).."] ["..utils.to_str(obj.m_game_vertex_id).."] ["..utils.to_str(result).."]") end
	end
	return result
end

local hdr6 = "      "
local hdr5 = "     "
local hdr4 = "    "
local hdr3 = "   "
local dont_spawn_online = false
function check_respawn(lnum)			--110000
	if hdr4 == "esc_" then
		if lnum == 1 then
			if has_alife_info("dark_btr1_spawn") then result = true else dont_spawn_online = true end
		else
			result = true			--puzir, garbage, agro, bar and dv
		end
	elseif hdr5 == "esc2_" then			--109994
		if has_alife_info("dark_btr1_spawn") then result = true else dont_spawn_online = true end
	elseif hdr4 == "val_" then
		if extended_levels == true then
			if lnum ~= 1 then result = true end
		else
			if string_find(obj_name, "_bandit_") then
				if lnum == 1 then
					if has_alife_info("esc_darklab_documents_read") then				--keep them out until cordon story quests are done
						result = true
					end
				elseif lnum == 30 then
					if has_alife_info("dyak_help_done") then							--keep them out until church is done
						result = true
					end
				end
			else
				result = true
			end
		end
	elseif hdr4 == "yan_" then
		if lnum == 9 then
			if string_find(obj_name, "yan_respawn")
			  or string_find(obj_name, "yan_ecolog") then
				if has_alife_info("sahar_sumka_done") then								--keep them out until military done
					result = true
				end
			else
				result = true
			end
		elseif lnum == 5 then
			if string_find(obj_name, "ecolog_respawn_2") then						--2 dead scientists by chopper in dv
				result = true
			end
		elseif lnum == 13 then
			if string_find(obj_name, "ecolog_respawn_2") then						--dead scientist with usb
				result = true
			end
		else
			dont_spawn_online = true
		end
	elseif hdr4 == "mil_" or hdr6 == "milita" then
		if string_find(obj_name, "barier_") then							--109988, not during storm, mil_freedom_barier_respawn
			if lnum == 11 then
				if has_alife_info("tb3d_sms_storm") and not has_alife_info("tb3d_block_1") then
					dont_spawn_online = true
				else
					result = true
				end
			else
				dont_spawn_online = true
			end
		--elseif string_find(obj_name, "_freedom_") then			--110008 freedom_respawn (hq guards and bridge guard)
			--if lnum == 11 then
				--if string_find(obj_name, "respawn_") then
					--if has_alife_info("tb3d_sms_storm") then		--never come back after storm
						--dont_spawn_online = true
					--else
						--result = true
					--end
				--else
					--result = true
				--end
			--else
				--dont_spawn_online = true
			--end
		--elseif string_find(obj_name, "_neytral_") then			--110008 stalkers near bar exit
			--if lnum == 11 then
				--if has_alife_info("tb3d_give_storm_info") then		--never come back after storm
					--dont_spawn_online = true
				--else
					--result = true
				--end
			--else
				--dont_spawn_online = true
			--end
		elseif string_find(obj_name, "blockpost_") then			--110008 mil_blockpost_freedomstalker001, monster_rush
			if lnum == 11 then
				--if has_alife_info("tb3d_give_storm_info") then		--never come back after storm
					--dont_spawn_online = true
				--else
					result = true
				--end
			else
				dont_spawn_online = true
			end
		else
			result = true
		end
	elseif hdr3 == "ds_" then
		if string_find(obj_name, "bandit_2") or string_find(obj_name, "bandit_3") then			--marsh remont
			if lnum == 43 or lnum == 30 then
				result = true
			end
		elseif lnum == 43 then
			result = true
		end
	elseif hdr4 == "atp_" then
		if lnum == 19 then result = true end
	elseif hdr5 == "lost_" or hdr6 == "villag" then
		if lnum == 29 then result = true end
	elseif hdr6 == "dcity_"	or hdr5 == "dead_" then									--also used by dav
		if extended_levels then
			result = true
		elseif lnum == 31 then
			result = true
		end
	elseif hdr5 =="city_"											--dcity_lastday_respawn_
	  or string_find(obj_name, "dead_city") then
		if lnum == 31 then result = true end
	elseif hdr4 == "pred" then										--bar_free, sold_baza_omon, vdv, kpp, army
		if lnum == 38 then result = true end
	elseif hdr6 == "promz_" then									--mil_smart_terrain
		if lnum == 46 then result = true end
	elseif hdr6 == "warlab" then
		if lnum == 27 then result = true end
	elseif hdr6 == "genera"				--orly, flesh1, gigant, tushkano, kaban, snork, svoboda, chimera
	  or hdr6 == "gener_"				--kaban_two
	  or hdr6 == "black_" then			--generators
		if lnum == 26 then result = true end
	elseif hdr6 == "after_"											--after_doctor_
	  or hdr6 == "hospit" then										--hospital_black_
		if lnum == 25 then result = true end
	elseif hdr6 == "swamp_" then									--baza_killer
		if lnum == 41 then result = true end
	elseif hdr6 == "forest"
	  or string_find(obj_name, "_forest_") then
		if lnum == 28 then result = true end
	elseif hdr4 == "ros_" then
		if lnum == 8 then result = true else dont_spawn_online = true end
		--if string_find(obj_name, "killer_respawn_4") then				--ros_killer_respawn_4, james guards
			--result = true
		--end
	elseif hdr5 == "land_"									--land_arhara_sniper_respawn_
	  or hdr6 == "zimovi"									--zimovie_stalker_respawn_1, zimovie_stalker_respawn_2
	  or hdr5 == "aver_" then								--hunter, kaban_gulag, arhara_sniper_mikrogulag1
		if lnum == 22 then result = true end
	elseif hdr4 == "agr_"				--pseudodog 
	  or hdr5 == "agr2_" then			--nii_flesh, dog, boars
		if string_find(obj_name, "_bandit_") then
			if lnum == 30 then
				if has_alife_info("dyak_help_done") then							--keep them out until church is done
					result = true
				end
			elseif lnum == 3 then
				result = true
			else
				dont_spawn_online = true
			end
		end
	elseif hdr4 =="pri_" then
		if lnum == 13 and has_alife_info("pri_undeground_respawn_start") then result = true else dont_spawn_online = true end
	elseif hdr4 =="pol_" then
		if lnum == 56 then result = true else dont_spawn_online = true end
	elseif string_find(obj_name, "2_respawn_dolg")
	  or string_find(obj_name, "stalker_respawn")
	  or string_find(obj_name, "soldier_respawn")
	  or string_find(obj_name, "dolg_respawn") then
			if has_alife_info("sahar_sumka_done") then				--keep them out until military done
				result = true
			end
	elseif string_find(obj_name, "neytral_respawn")	then				--military_neytral_respawn_1, _2
			--if has_alife_info("sahar_sumka_done") then				--keep them out until military done
				result = true
			--end
	elseif string_find(obj_name, "monolith_") then					--creatures and several npc
		if has_alife_info("tb3d_chaes_done") then					--110004, after guntlet
			result = true
		end
	else
		result = true
	end
	return result
end

function check_specific(lnum)				--110000
	if hdr5 == "agr_r" and lnum ~= 3 then			--road_patrol
		dont_spawn_online = true
	elseif hdr4 == "red_" and lnum ~= 28 then		--snork
		dont_spawn_online = true
	elseif hdr4 == "bun2" and lnum ~= 18 then		--110008
		dont_spawn_online = true
	elseif hdr4 == "atp_" and lnum ~= 19 then		--110005
		dont_spawn_online = true
	elseif hdr5 == "aver_" and lnum ~= 22 then		--snork, dog
		dont_spawn_online = true
	elseif hdr6 == "puzir_" and lnum ~= 21 then		--snork
		dont_spawn_online = true
	elseif (hdr6 == "gener_" or hdr4 == "gen_" or hdr6 == "genera") and lnum ~= 26 then		--109989, forest_chimera_x_ray1,2, snork, gen_bloodsucker_na_krushe  TODO: need fix black_doc
		dont_spawn_online = true
	elseif hdr6 == "forest" and lnum ~= 28 then		--forest_chimera_x_ray1,2
		dont_spawn_online = true
	elseif hdr6 == "yan_ol" and lnum ~= 40 then		--yan_old_st_fracture
		dont_spawn_online = true
	elseif ((hdr6 == "gar_se" and string_find(obj_name, "wff")) or hdr5 == "pred_" or hdr4 == "pre_") and lnum ~= 38 then		--pred_st_dog, flesh, snork, zombie, gar_seriywff
		dont_spawn_online = true
	elseif hdr6 == "villag" and lnum ~= 29 then		--village_flesh
		dont_spawn_online = true
	elseif hdr6 == "promz_" and lnum ~= 46 then		--promz_bloodsucker, dog, flesh, burer, zombie
		dont_spawn_online = true
	elseif hdr4 == "l04_"  and lnum ~= 51 then		--hr_cat, dog, snork, boar, tushkano, flesh, chimera, bloodsucker, gigant
		dont_spawn_online = true
	elseif hdr3 == "hr_"  and lnum ~= 42 then		--hr_cat, dog, snork, boar, tushkano, flesh, chimera, bloodsucker, gigant
		dont_spawn_online = true
	elseif hdr3 == "f1_"  and lnum ~= 45 then		--f1_st_chimera, bloodsucker, gigant
		dont_spawn_online = true
	elseif hdr3 == "df_" and lnum ~= 43 then		--df_gigant, chimera
		dont_spawn_online = true
	elseif hdr6 == "pesher" and lnum ~= 20 then		--peshera_
		dont_spawn_online = true
	elseif hdr6 == "dcity_" and lnum ~= 31 then
		dont_spawn_online = true
	elseif hdr6 == "m_polt" then					--110008, causes freeze in xrgame.dll if no smart
		if not (lnum == 9 or lnum == 10 or lnum == 12 or lnum == 13 or lnum == 40) then
			dont_spawn_online = true
		end
	end
	return dont_spawn_online		--will be false if not found
end

function stalker_can_go_online(obj)		--110000, called by se_stalker
	if db.actor == nil then return false end
	local result = true
	if obj and obj.name then
		if is_spawner then									-- _g.is_spawner set by ui_si spawn menu
			is_spawner = false
			result = true
		else
			local is_report = false
			local extended_levels = TB3D_Services.is_collector(81)
			local sect = get_section(obj)			--110000
			local lname = level.name()
			local lnum = get_level_index(lname)		--110004
			obj_name = obj:name()
			dont_spawn_online = false
			if TB3D_Modders.use_setup_message and string_find(obj_name, TB3D_Modders.npc_to_log) then is_report = true end
			hdr6 = string_sub(obj_name, 1, 6)
			hdr5 = string_sub(hdr6, 1, 5)
			hdr4 = string_sub(hdr5, 1, 4)
			hdr3 = string_sub(hdr4, 1, 3)
			if TB3D_Services.is_instorm(lname) then
				if (hdr6 == "tb3dm_"
				  or hdr4 == "amk_")
				  and string_find(obj_name, "zombie") then								--110007, hell hour and zombies only
					result = true
				end
			elseif string_sub(sect, 1, 5) == "zone_" or sect == "inventory_box" then
				result = true
			elseif hdr4 == "amk_" or hdr5 == "tb3d_" or hdr6 == "tb3dm_" or hdr6 == "dogfre" or hdr6 == "turret" then		--all levels
				result = true
			elseif hdr3 == "ldk" and hdr4 ~= "ldk_" then								--dav unique ldk1_ thru ldk9_
				if string_sub(hdr5, 5, 1) == "_" then
					if extended_levels then
						result = true
					else
						dont_spawn_online = true
					end
				else
					if extended_levels then
						--if has_alife_info("tb3d_dm_deserters") then					--109954 old ldk respawns to be used in levelup 3
							result = true
						--else
							--dont_spawn_online = true
						--end
					else
						dont_spawn_online = true
					end
				end
			elseif hdr4 == "dav_" or hdr4 == "ldk_" then								--new ldk
				if extended_levels then
					result = true
				else
					dont_spawn_online = true
				end
			elseif hdr6 == "stalk_" then
				if string_find(obj_name, "_hos") and lnum ~= 25 then					--110009, spawn in garbage
					dont_spawn_online = true
				else
					result = true
				end
			elseif check_specific(lnum) then
				result = false
			elseif sect == "respawn" or string_find(obj_name, "respawn") then			--respawners in the all.spawn
				result = check_respawn(lnum)
			--------------------------------------- level spawns --------------------------------------------
			elseif lnum == 1 then
--[[				if hdr6 == "esc_fo" then
					result = true
				else
					dont_spawn_online = true
				end]]
				if hdr4 == "esc_"							--short circuit known spawns
				  or hdr4 == "ens_"
				  or hdr4 == "sak_"
				  or hdr5 == "esc2_"
				  or hdr6 == "escape"
				  or hdr6 == "zapasn"		--zapasnoy_foto_muzhik
				  or hdr6 == "mill_s"		--mill_sniper_nick, harris, jonn, croker
				  or hdr6 == "zvezd_"		--zvezd_after_warl
				  or hdr6 == "kordon"
				  or hdr6 == "snip_e"		--snip_esc1 thru 13
				  or hdr6 == "xalyav" then	--xalyava, xalyava_naem1 thru 7
					if string_find(obj_name, "esc_vagon_wounded")				--tolik
					  or string_find(obj_name, "father_pant")						--father panther
					  or string_find(obj_name, "pantera_bomba")						--panther
					  or string_find(obj_name, "stalk_shuher")						--Nix
					  or string_find(obj_name, "provodnik") then					--guide
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				elseif hdr6 == "doktor"	then										--doktor1
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_" then											--see if allowed simulation
					if string_find(obj_name, "esc_arh")
					  or string_find(obj_name, "podmoga_bandit") then
						if extended_levels then
							dont_spawn_online = true
						else
							if has_alife_info("esc_darklab_documents_read") then					--keep them out until cordon story quests are done
								result = true
							end
						end
					end
				elseif hdr4 == "gar_" then											--bandits, novice
					if string_find(obj_name, "sniper_bandit")
					  or string_find(obj_name, "bandit_post")
					  or string_find(obj_name, "stalker_0009") then
						if extended_levels then
							dont_spawn_online = true
						elseif has_alife_info("esc_darklab_documents_read") then					--keep them out until cordon story quests are done
							result = true
						end
					elseif string_find(obj_name, "stalker_0007") then					--109989, Vampire
						if has_alife_info("agroprom_military_case_done") and not has_alife_info("sniper_begin_vosem") then		--109991
							result = true
						else
							dont_spawn_online = true
						end
					elseif string_find(obj_name, "wounded_bandit") then								--stole the pda
						if extended_levels then
							dont_spawn_online = true
						else																	--must go online as may have task spot
							result = true
						end
					elseif string_find(obj_name, "bandit_") then									--109994, gar_bandit_agr_, gar_bandit_seryi_
						if extended_levels then
							dont_spawn_online = true
						elseif has_alife_info("esc_darklab_documents_read") then					--keep them out until cordon story quests are done
							result = true
						end
					else
						result = true											--novice
					end
				elseif hdr4 == "val_" then
					if string_find(obj_name, "bandit_krisyk") then				--the rat
						if extended_levels then
							dont_spawn_online = true
						else
							--if has_alife_info("esc_darklab_documents_read") then		--prevent clash between rat and gar_wounded_bandit
								result = true
							--end
						end
					elseif string_find(obj_name, "kocherga") then						--allow to accompany gar_wounded_bandit
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						dont_spawn_online = true
					end
				elseif hdr5 == "dead_" then
					if string_find(obj_name, "dead_military_esc") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						--if has_alife_info("bar_deactivate_radar_done") then
							result = true
						--end
					end
				end
			elseif lnum == 2 then
				if hdr4 == "gar_"			--short circuit known spawns
				  or hdr4 == "sak_"
				  or hdr4 == "amk_"			--109987, vitek_voron the trader, amk_artem_kulinar
				  or hdr6 == "garbag"
				  or hdr6 == "svalka"
				  or hdr6 == "tamaz_" then
					if string_find(obj_name, "_dm_")
					  or string_find(obj_name, "tamaz_ohr") then
					  --or string_find(obj_name, "_seryi")
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "stalker_0007") then					--109989, Vampire
						if has_alife_info("agroprom_military_case_done") and not has_alife_info("sniper_begin_vosem") then		--109991
							result = true
						else
							dont_spawn_online = true
						end
					elseif string_find(obj_name, "bandit_stroyka") then					--110010, bandits by swamp quest now given by barman
						if has_alife_info("agroprom_military_case_done") then
							result = true
						else
							dont_spawn_online = true
						end
					else
						result = true
					end
				elseif hdr4 == "agr_" then		--factory defense and dogs
					if string_find(obj_name, "factory_defence_stalker5_") then		--sched errors
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "val_" then		--escort captive, nap1, dogs, rats and bandits
					result = true
				elseif hdr4 == "esc_" then
					if string_find(obj_name, "kostya")
					  or string_find(obj_name, "_fox") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				elseif hdr4 == "sim_" then									--see if allowed simulation
					if string_find(obj_name, "novice_neumeha")
					  or string_find(obj_name, "general_upir")				--Vitamin
					  or string_find(obj_name, "_gusarov")					--gar graveyard after val chase
					  or string_find(obj_name, "bandit_veteran") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				else
					--dont_spawn_online = true
					result = true
				end
			elseif lnum == 3 then
				if hdr4 == "sak_" then			--short circuit known spawns
					result = true					--mil trader
				elseif hdr4 == "gar_" then
					if string_find(obj_name, "stalker_0007") then					--109989, Vampire
						if has_alife_info("agroprom_military_case_done") and not has_alife_info("sniper_begin_vosem") then		--109991
							result = true
						else
							dont_spawn_online = true
						end
					else
						result = true
					end
				elseif hdr4 == "esc_" then
					dont_spawn_online = true
				elseif hdr5 == "agro_"
				  or hdr4 == "agr_" then
					if string_find(obj_name, "piyn_") then							--clash with gek and chuck
						if extended_levels or has_alife_info("kuzy_artmodifikator_done") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "_adrenalin")							--keep the trader
					  or string_find(obj_name, "_military")
					  or string_find(obj_name, "road_patrol")
					  or string_find(obj_name, "_krot")								--109975, mole
					  or string_find(obj_name, "_tower")
					  or string_find(obj_name, "_zone")
					  or string_find(obj_name, "ratcatcher")						--109989, deserter in trailor
					  or string_find(obj_name, "_nii_") then
						result = true
					elseif string_find(obj_name, "zastava1_soldier") then			--109989, interfere with Mole rescue
						if not has_alife_info("agr_find_gunslinger_cache_found") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "factory_defence_stalker") then		--109975, fight with exit guards
						if has_alife_info("agr_find_gunslinger_cache_found") and not has_alife_info("agroprom_military_case_done") then
							dont_spawn_online = true
						else
							result = true
						end
					end
				elseif hdr3 == "gek"
				  or hdr4 == "chuk" then
					if extended_levels or has_alife_info("kot_agro_mono_fail") then		--110000
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "trezv_" then		--110000
					if extended_levels or has_alife_info("kuzy_artmodifikator_done") then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "mono_a" then		--110000
					if extended_levels or has_alife_info("kot_agro_mono_done") or has_alife_info("kot_agro_mono_fail") then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "sniper"
				  or hdr6 == "yakut_"								--arhara
				  or hdr6 == "piyan_"
				  or hdr6 == "kapita"
				  or hdr6 == "final_"
				  or hdr6 == "kuzhet" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 4 then
				result = true
			elseif lnum == 5 then
				if hdr4 == "val_" then			--short circuit known spawns
					if string_find(obj_name, "red_")
					  or string_find(obj_name, "watchtower")
					  or (string_find(obj_name, "lager_bandit") and not string_find(obj_name, "borov"))
					  or string_find(obj_name, "exit_base_bandit") then
						result = true
					elseif string_find(obj_name, "raid_g") or string_find(obj_name, "escort")
					  or string_find(obj_name, "prisoner_captive")
					  or string_find(obj_name, "val_stalker") then
						if  extended_levels or has_alife_info("tb3d_skip_group1") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "yan_ec" then
					result = true
				elseif hdr4 == "dar_" or hdr4 == "gar_" or hdr4 == "agr_" or hdr6 == "mil_bo" then
					if string_find(obj_name, "gar_seriy") then												--110007, does not belong here
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "dark_b" 		--dark btr
				  or hdr6 == "dark_s" 			--dark btr soldiers
				  or hdr6 == "bland_" 			--belong only in DV
				  or hdr4 == "sak_" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "arhara_green_regular")
					  or string_find(obj_name, "_kocherga")
					  or string_find(obj_name, "_fraer") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				elseif string_find(obj_name, "agr_krot")						--Mole
				  or string_find(obj_name, "korchagin_") then					--dead_korchagin_military
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 6 then
				if hdr4 == "x18_"			--short circuit known spawns
				  or hdr4 == "lab_"
				  or hdr4 == "dar_"
				  or hdr4 == "sak_" then
					if string_find(obj_name, "_stalker0000") then				--dead scientists
						if has_alife_info("tb3d_skip_group1") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 7 then
				if hdr4 == "bar_" then									--bar_stalker_0005 = arena fight 1, _0006 = fight 2, 7 & 8 = 3, 9 - 13 = 4, 14 & 15 = 5, 16 - 21 = 6, 22 = 7, 23 - 26 = 8
					if string_find(obj_name, "^bar_visitor_") then		--109989, bar_visitor_2,3,4,5,7,8,10,12,13,15	around campfires
						if TB3D_Modders.reduce_bar_visitors then
							if string_find(obj_name, "visitor_2")
							  or string_find(obj_name, "visitor_5")
							  or string_find(obj_name, "visitor_8")
							  or string_find(obj_name, "visitor_12")
							  or string_find(obj_name, "visitor_15") then
								dont_spawn_online = true
							else
								result = true
							end
						else
							result = true
						end
					elseif string_find(obj_name, "_attackers_") then			--110007, remove after humback mission
						if extended_levels or has_alife_info("naemn_shturm_poluch_done") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "stalker_0001") then			--109989, Barin wandering around warehouse exit
						if extended_levels then
							dont_spawn_online = true
						elseif has_alife_info("naemn_shturm_poluch_done") then		-- after humback mission
							result = true
						else
							dont_spawn_online = true
						end
					elseif string_find(obj_name, "house_stalker")					--110003, reduce npc after level up
					  or string_find(obj_name, "angar_zoneguard")
					  or string_find(obj_name, "zastava_guard_2")
					  or string_find(obj_name, "dolg_regular_1")
					  or string_find(obj_name, "bar_visitors_") --1_2")
					  --or string_find(obj_name, "bar_visitors_2_1")
					  --or string_find(obj_name, "bar_visitors_3_2")
					  --or string_find(obj_name, "bar_visitors_3_3")
					  --or string_find(obj_name, "bar_visitors_3_4")
					  or string_find(obj_name, "bunker_2")
					  or string_find(obj_name, "bunker_3")
					  or string_find(obj_name, "bunker_4")
					  or string_find(obj_name, "bunker_0002") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					--elseif string_find(obj_name, "barman") then					--for testing
						--dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "gar_st"			--gar_stalker_general
				  or hdr6 == "prapor"			--prapor
				  or hdr6 == "dolgov"			--dolgovazyi
				  or hdr4 == "aem_"				--arny, arena
				  or hdr4 == "sak_" then
					result = true
				elseif hdr4 == "bkot" then			--110008, feral cat in bar
					if extended_levels then
						dont_spawn_online = true
					elseif has_alife_info("kot_need_next_done") then
						result = true
					end
				elseif hdr5 == "kluk_"			--kluk_bar - canine
				  or hdr6 == "piligr" then		--piligrim_bar
					if extended_levels then								--110008
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "esc_fo" or hdr6 == "esc_ko" then		--fox and kostya
						result = true
				elseif hdr6 == "stalke" then
					if string_find(obj_name, "_green_") then
						result = true
					end
				elseif hdr6 == "rostok" then
					if string_find(obj_name, "_stalker") then
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "arhara_green_regular")
					  or string_find(obj_name, "_barin")
					  or string_find(obj_name, "_gusarov")					--gar graveyard before val chase
					  or string_find(obj_name, "_umnik")
					  or string_find(obj_name, "_vorobey")
					  or string_find(obj_name, "_prapor")
					  or string_find(obj_name, "_stalker_novice")
					  then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				end
			elseif lnum == 8 then
				if hdr4 == "ros_"			--ros_sniper1, 2, 3, 4, 
				  or hdr5 == "naem_"		--naem_zahar1, 2, 3, 4, 5, 6, 
				  or hdr5 == "rost_" then	--rost_naemnik_koster, 1, 2, 3, rost_siv, rost_siv_ohr1, 2
					if string_find(obj_name, "sniper2") and has_alife_info("zahar_naemnik_begin") then					--bad path 110004
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "bar_" then			--bar_rostok_james
					if string_find(obj_name, "ambush")
					  or string_find(obj_name, "freedom_attacker")
					  or string_find(obj_name, "spy") then
						if extended_levels or has_alife_info("tb3d_skip_group1") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "stalker_0004") then			--109975, interferes with after x16 bandits
						if has_alife_info("bar_x16_documents_done") then
							result = true
						end
					else
						result = true
					end
				elseif hdr6 == "bandit" then
					if string_find(obj_name, "after_x16") then
						result = true
					end
				elseif hdr6 == "naem_z" then				--zahar
					result = true
				elseif hdr6 == "rostok"	then
					if string_find(obj_name, "stalker_0000") then			--rostok_stalker_0000 (has iglo)
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "stalker_000") then			--rostok_stalker_0001, 2, 3, 4
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "_naemnik") then			--rostok_naemnik1_grup1, _naemnik2_, _naemnik3_, _naemnik4_, _naemnik5_
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "dead_stalker_0") then		--rostok_dead_stalker_01, 02, 03, rostok_dead_stalker_0000
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "stalker_zombied") then	--rostok_stalker_zombied, _0000, 1, 3, 4, 5, 6
						if extended_levels then --or has_alife_info("tb3d_skip_group1") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "_bandit")	then		--rostok_bandit1_koster, 2, 3
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				elseif hdr4 == "sak_" then
					if extended_levels then
						if string_find(obj_name, "_koster")
						  or string_find(obj_name, "ros_") then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "arhara_green_regular")
					  or string_find(obj_name, "ros_")
					  or string_find(obj_name, "killer_general") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "stalker_prapor") then				--109975 sparrow, interferes with after_x16 bandits
						if has_alife_info("bar_x16_documents_done") then
							result = true
						end
					else
						result = true
					end
				elseif hdr4 == "gar_" then
					dont_spawn_online = true
				elseif hdr6 == "genera" then				--109989
					dont_spawn_online = true
				elseif string_find(obj_name, "mil_dolg_stalker")
				  or string_find(obj_name, "military_neytral_stalk1") then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 9 then
				if hdr4 == "yan_" then			--short circuit known spawns
					if string_find(obj_name, "scientist_help")
					  or string_find(obj_name, "old_st") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "specnaz_dead") then				--109992, wait for task from mil
						if has_alife_info("mil_lukash_dolg_task") and not has_alife_info("mil_lukash_heal_reward") then
							result = true
						end
					else
						result = true
					end
				elseif hdr4 == "sak_"
				  or hdr6 == "cherno" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "arhara"	then								--ecolog guards
					--if extended_levels then
						--dont_spawn_online = true
					--else
						result = true
					--end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "_prapor") then
						if extended_levels then
							dont_spawn_online = true
						else
							if has_alife_info("sahar_sumka_done") then						--keep them out until military done
								result = true
							end
						end
					elseif string_find(obj_name, "soldier_specnaz") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				elseif hdr6 == "yantar" then
					if string_find(obj_name, "stalker_zombied") then
						if extended_levels then
							dont_spawn_online = true
						elseif string_find(obj_name, "_zombied_0027")
						  or string_find(obj_name, "_zombied_0029")
						  or string_find(obj_name, "_zombied_0030") then				--in tunnel
							if has_alife_info("yan_has_ghost_pda")
							  and not has_alife_info("yan_kill_brain_done") then
								result = true
							else
								dont_spawn_online = true
							end
						elseif string_find(obj_name, "_zombied_003")
						  or string_find(obj_name, "_zombied_004") then
							--if has_alife_info("tb3d_skip_group1") then
								--dont_spawn_online = true
							if has_alife_info("yan_find_scientist_done") then
								result = true
							else
								dont_spawn_online = true
							end
						elseif string_find(obj_name, "_zombied_0000")
						  or string_find(obj_name, "_zombied_0013")
						  or string_find(obj_name, "_zombied_0014") then
							if has_alife_info("yan_scientist_return_to_bunker") then
								result = true
							else
								dont_spawn_online = true
							end
						else
							result = true
						end
					elseif string_find(obj_name, "stalk_ranen") then
						if has_alife_info("yan_has_ghost_pda") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "dead_scientist_01") then		--109972
						if has_alife_info("yan_has_ghost_pda") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "chernomor") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "_semenov") then
						if extended_levels then
							dont_spawn_online = true
						elseif has_alife_info("yan_kill_brain_done") then
							result = true
						end
					elseif string_find(obj_name, "gulag_zombies")
					  or string_find(obj_name, "kontroller_yazva") then					--keep away until research complete
						if has_alife_info("yan_find_scientist_done") then -- and not has_alife_info("tb3d_skip_group1") then
							result = true
						end
					else
						result = true
					end
				elseif hdr6 == "bandit" then
					if has_alife_info("yan_has_ghost_pda") then
						dont_spawn_online = true
					else
						result = true
					end
				elseif string_find(obj_name, "ekolog_zombi") then
					if extended_levels then --or has_alife_info("tb3d_skip_group1") then
						dont_spawn_online = true
					elseif has_alife_info("yan_has_ghost_pda") then
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 10 then
				if hdr6 == "x16_m_" then										--controller
					if extended_levels or has_alife_info("tb3d_skip_group1") then
						dont_spawn_online = true
					else
						--dont_spawn_online = true
						result = true
					end
				elseif hdr4 == "x16_" then										--short circuit known spawns
					if string_find(obj_name, "zombied") then
						if extended_levels then --or has_alife_info("tb3d_skip_group1") then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 11 then
				if hdr4 == "sak_"				--short circuit known spawns
				  or hdr6 == "milita"			--military_
				  or hdr6 == "m_cont"
				  or hdr6 == "stalke" then					--109983
					result = true
				elseif hdr6 == "yakut_"			--yakut_agro2
				  or hdr6 == "tamaz_"
				  or hdr6 == "piligr"
				  or hdr6 == "francu"
				  or hdr6 == "scromn"
				  or hdr6 == "gener_"			--110007, gener_shlagbaum_freedom
				  or hdr6 == "djoker"
				  or hdr5 == "kluk_" then
					if extended_levels then					--109983
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_"										--see if allowed simulation: prut, master_diador, master_master
				  or hdr4 == "esc_"											--esc_fox
				  or hdr6 == "milit_"
				  or hdr4 == "mil_" then
					if string_find(obj_name, "freedom_member0021") then			--trader - use in collector?
						result = true
					elseif string_find(obj_name, "freedom_stalker0026") then	--the cook - use in collector?
						result = true
					elseif string_find(obj_name, "military_")
					  or string_find(obj_name, "patrol_stalker")			--ambushed mil
					  or string_find(obj_name, "_leshii")
					  or string_find(obj_name, "fotomuzhik")				--photo restrs and npc
					  or string_find(obj_name, "freedom_member00")			--arms guard 0010, causes ctd from no restrictor in collector
					  or string_find(obj_name, "stalker_monolith_")
					  or string_find(obj_name, "naemnik_")
					  or string_find(obj_name, "kostya")
					  or string_find(obj_name, "arhara_naemnik")
					  or string_find(obj_name, "dolg_stalker0004")				--109954  path errors
					  or string_find(obj_name, "gavr_bodyguard")
					  or string_find(obj_name, "blockpost_freedomstalker")
					  or string_find(obj_name, "_ara")							--in camp when come from wild territory
					  then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "dolg_stalker0001") then			--109975, gets in front of skull at start
						if has_alife_info("mil_lukash_guard_talked") or has_alife_info("mil_sniper_payment") then
							result = true
						end
					else
						--dont_spawn_online = true
						result = true
					end
				else
					result = true
					--dont_spawn_online = true
				end
			elseif lnum == 12 then
				if hdr4 == "rad_"			--short circuit known spawns
				  or hdr4 == "new_"
				  or hdr6 == "radar_"
				  or hdr4 == "sak_" then
					if string_find(obj_name, "radar_vitamin")
					  or string_find(obj_name, "radar_svoboda_") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "freedom_vs_duty")
					  or string_find(obj_name, "tramplin_")
					  or string_find(obj_name, "road_kamper")
					  or string_find(obj_name, "road_patroler")
					  or string_find(obj_name, "after_valley")
					  or string_find(obj_name, "ambush")
					  or string_find(obj_name, "stalker_zombied")
					  or string_find(obj_name, "stalker_dolg")
					  or string_find(obj_name, "road_guard") then
						if extended_levels then
							dont_spawn_online = true
						elseif not has_alife_info("rad_task_aes") and (obj.alive and obj:alive()) then					--TODO: notanumber needs define
							result = true
						else
							dont_spawn_online = true
						end
					elseif string_find(obj_name, "antenna_")
					  --or string_find(obj_name, "antenna_sniper4")						--crashes if spawn before radar done
					  or string_find(obj_name, "curve_road_")
					  or string_find(obj_name, "ambush_") then
						if extended_levels then
							dont_spawn_online = true
						elseif not has_alife_info("bar_deactivate_radar_done") and (obj.alive and obj:alive()) then
							result = true
						else
							dont_spawn_online = true
						end
					elseif string_find(obj_name, "new_prizrak") then					--ghost, 109954
						if extended_levels then
							dont_spawn_online = true
						else
							--if not has_alife_info("bar_deactivate_radar_done") then
								result = true
							--end
						end
					else
						result = true
					end
				elseif hdr5 == "rad2_" then
						--rad2_stalker_zombied
						--rad2_stalker_zombied_0000
						--rad2_stalker_zombied_0001
						--rad2_military
						--rad2_stalker
						--rad2_stalker_0000
						--rad2_stalker_0001
						--rad2_stalker_0002
						--rad2_stalker_0003
						--rad2_stalker_0004
					if has_alife_info("bar_deactivate_radar_done") and (obj.alive and obj:alive()) then		--110002, need reduce npc after lab
						result = true
					else
						dont_spawn_online = true
					end
				else
					result = true
				end
			elseif lnum == 13 then
				if hdr4 == "pri_"			--short circuit known spawns
				  or hdr5 == "prip_"			--monolith
				  or hdr6 == "pripya"			--pripyat_
				  or hdr4 == "sak_" then
					if string_find(obj_name, "followers_") 
					  or string_find(obj_name, "_wave") then
						if extended_levels then
							dont_spawn_online = true
						elseif not has_alife_info("pri_corner_end") then
							result = true
						end
					elseif string_find(obj_name, "dok_arh")
					  or string_find(obj_name, "_w1")
					  or string_find(obj_name, "camper_n")									--pri_monolith_camper_n_1
					  or string_find(obj_name, "mono_")										--prip_mono_after_mina
					  or string_find(obj_name, "radist")
					  or string_find(obj_name, "_roof") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "stadium_") then
						if extended_levels then
							dont_spawn_online = true
						elseif string_find(obj_name, "help") then						--109960 stalker1, stalker2 - cause ctds
							dont_spawn_online = true
						elseif not has_alife_info("aes_arrive_to") then					--109960 snipers, lair_
							result = true
						end
					elseif string_find(obj_name, "sideway_") then
						if not has_alife_info("aes_arrive_to") then
							result = true
						end
					elseif string_find(obj_name, "depot_") then
						if not has_alife_info("aes_arrive_to") then
							result = true
						end
					elseif string_find(obj_name, "monolith_10") then									--109991, pri_monolith_10 gets innaccesable vertex errors
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "doktor" or hdr6 == "radist" or hdr6 == "rad_pr"
					or hdr6 == "rad_af" or hdr6 == "rad_am" or hdr6 == "mil_st" then					--the doktor, rad_prip_teleport_cache_quard, rad_after
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
				elseif hdr6 == "bar_st" or hdr6 == "mil_do" or hdr6 == "sadik1" or hdr6 =="kot_ha"
					or hdr6 == "sadik_" or hdr6 == "marsh_" or hdr6 == "mil_fr" then					--bar_stalker, mil_dolg, sadik1_mono_valker, marsh_arhara_controller, mil_freedom_respawn_
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "monolith_specnaz")
					  then result = true
					end
				elseif hdr4 == "mil_" then
					if string_find(obj_name, "blockpost_") then			--mil_blockpost_freedomstalker001
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 14 then
				if hdr4 == "aes_"			--short circuit known spawns
				  or hdr4 == "sak_" then
					if string_find(obj_name, "aes_Soldier_commander") then					--has sakharov's med bag
						if has_alife_info("sahar_sumka_start") then result = true else dont_spawn_online = true end
					elseif extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "chaes1" then								--109998, ghost
					if string_find(obj_name, "_prizrak") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				else
					result = true
				end
			elseif lnum == 15 then
				if hdr5 == "sarc_" then			--109998, short circuit known spawns
						result = true			--zombied monolith
				elseif hdr4 == "sar_" then		--monolith and sklad, NS storyline
					if extended_levels and not has_alife_info("tb3d_started_as_collector") then				--109998, might as well use them otherwise
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "nevid_" then	--monolit, NS storyline
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr5 == "aes2_" then
					if string_find(obj_name, "monolit_stalker") then
						if not has_alife_info("tb3d_chaes_done") then
							result = true
						end
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 16 then
				if hdr4 == "mon_"			--short circuit known spawns
				  or hdr6 == "molniy"
				  or hdr4 == "sak_"
				  or hdr6 == "m_osoz" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 17 then
				if hdr6 == "chaes2"			--chaes2_mono_fugas
				  or hdr6 == "monoli"		--monolit_truba
				  or hdr5 == "kluk_"		--kluk_chaes2 (Canine)
				  or hdr4 == "sak_" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr5 == "aes2_" then
					if string_find(obj_name, "monolit_stalker") then
						if not has_alife_info("tb3d_chaes_done") then
							result = true
						end
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 18 then
				if hdr4 == "bun_"			--short circuit known spawns
				  or hdr4 == "rad_"
				  or hdr4 == "sak_" then
					if extended_levels then
						dont_spawn_online = true
					else
						if string_find(obj_name, "stalker_monolith") then
							if not has_alife_info("rad_start_monolith_vs_military") then				--prevent return after first visit
								result = true
							end
						else
							result = true
						end
					end
				elseif hdr4 == "bun2" then
					if extended_levels then
						dont_spawn_online = true
					else
						if has_alife_info("rad_start_monolith_vs_military") then			--wait til next visit
							result = true
						end
					end
				else
					result = true
				end
			elseif lnum == 19 then
				if hdr4 == "atp_"			--short circuit known spawns
				  or hdr6 == "arhara"
				  or hdr4 == "sak_" then
					if string_find(obj_name, "shurer")
					  or string_find(obj_name, "_voyka")
					  or string_find(obj_name, "mobil_torgovetz")
					  or string_find(obj_name, "bandit_shnura")
					  or string_find(obj_name, "_gonets")
					  or string_find(obj_name, "_soldat_attakker")
					  or string_find(obj_name, "_trupak_disk")
					  or string_find(obj_name, "_presled_last")
					  or string_find(obj_name, "_monolit")
					  or string_find(obj_name, "_bandit17")						--assertion error on 12x70 buck
					  or string_find(obj_name, "_kalinin")
					  or string_find(obj_name, "_sedoy_heli")
					  or string_find(obj_name, "_brigada") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif not string_find(obj_name, "brigada5") then			--causes path error on spawn 109934
						result = true
					end
				elseif hdr4 == "yan_" then										--yan_old migrations
						dont_spawn_online = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "monolith_specnaz")
					  or string_find(obj_name, "monolith_regular")
					  or string_find(obj_name, "monolith_master")
					  or string_find(obj_name, "atp_")
					  then result = true end
				else
					result = true
				end
			elseif lnum == 20 then
				result = true
			elseif lnum == 21 then
				result = true
			elseif lnum == 22 then
				if hdr5 == "aver_"			--short circuit known spawns
				  or hdr4 == "sak_" then
					result = true
				elseif hdr4 == "gar_" then								--109989, vampire
					dont_spawn_online = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "arhara_zimovie")
					  or string_find(obj_name, "aver_")
					  or string_find(obj_name, "land_arhara_sniper") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				else
					result = true
				end
			elseif lnum == 23 then
				if hdr3 == "av_"			--short circuit known spawns
				  or hdr6 == "blood_"			--av_peshera only
				  or hdr4 == "sak_" then
					if string_find(obj_name, "labirint_shade")		--path errors
					  or string_find(obj_name, "_peshera_mono")
					  or string_find(obj_name, "_chasovoi")
					  or string_find(obj_name, "_monolit_shahter")
					  or string_find(obj_name, "av_mono") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "av_") then
						result = true
					end
				else
					result = true
				end
			elseif lnum == 24 then
				if hdr4 == "lim_"			--short circuit known spawns
				  or hdr4 == "sak_"
				  or hdr6 == "stalk_"
				  or hdr6 == "zombie"
				  or hdr6 == "freedo"
				  or hdr6 == "m_cont" then
					result = true
				elseif hdr6 == "blizn_"
				  --or hdr5 == "borm_"
				  or hdr6 == "borman" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if extended_levels then
						dont_spawn_online = true
					else
						if string_find(obj_name, "borm_lima")
						  then result = true end
					end
				elseif hdr6 == "rad_pr" then										--109981, rad_prip_teleport_
					dont_spawn_online = true
				else
					result = true
				end
			elseif lnum == 25 then
				if hdr4 == "hos_"			--short circuit known spawns
				  or hdr6 == "hospit"
				  or hdr6 == "muha_h"
				  or hdr6 == "black_"
				  or hdr5 == "hosp_"
				  or hdr4 == "sak_" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "monolith_specnaz")
					  or string_find(obj_name, "monolith_regular")
					  or string_find(obj_name, "hospital_") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				else
					result = true
				end
			elseif lnum == 26 then
				if hdr4 == "gen_"			--short circuit known spawns
				  or hdr6 == "gener_"
				  or hdr6 == "genera" then
					if extended_levels then								--110003
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr5 == "metka"
				  or hdr5 == "frits"
				  or hdr6 == "zemlyk"
				  or hdr6 == "anders"						--andersen
				  or hdr6 == "solvad"						--solvador
				  --or hdr6 == "monoli"						--monolit_shlagbaum at gate to dm
				  or hdr6 == "black_"
				  or hdr6 == "odnono"						--odnonogiy_stalk - Maximillian
				  or hdr4 == "sak_" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "generators_")
					  or string_find(obj_name, "gener_") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				else 
					result = true
				end
			elseif lnum == 27 then
				if hdr4 == "war_"			--short circuit known spawns
				  or hdr6 == "warlab"
				  or hdr6 == "panter"
				  or hdr6 == "body1_"
				  or hdr6 == "body2_"
				  or hdr6 == "sheste"
				  or hdr5 == "bodi_"
				  or hdr4 == "sak_" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "warlab_") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				else
					result = true
				end
			elseif lnum == 28 then
				if hdr4 == "red_"			--short circuit known spawns
				  or hdr6 == "redfor"
				  or hdr6 == "forest"
				  or hdr6 == "shadow"
				  or hdr6 == "stalk_"
				  or hdr6 == "contr_"
				  or hdr4 == "for_"
				  or hdr4 == "sak_"
				  or hdr4 == "psy_" then
					if string_find(obj_name, "lesnik")
					  or string_find(obj_name, "lastday")
					  or string_find(obj_name, "stalk_forest")
					  or string_find(obj_name, "ohotnik")
					  or string_find(obj_name, "contr_forest")
					  or string_find(obj_name, "shadowman")
					  or string_find(obj_name, "forest_wound") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "killer_master")
					  or string_find(obj_name, "killer_general")
					  or string_find(obj_name, "killer_veteran")
					  or string_find(obj_name, "stalker_veteran") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 29 then
				if hdr5 == "lost_"			--short circuit known spawns
				  or hdr6 == "after_"
				  or hdr4 == "sak_" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if extended_levels then
						dont_spawn_online = true
					elseif string_find(obj_name, "village_") then
						result = true
					end
				else
					result = true
				end
			elseif lnum == 30 then
				if hdr6 == "marsh_"
				  or hdr6 == "boloto" then				  				
					if string_find(obj_name, "controller")				--nw village
					  or string_find(obj_name, "_dan")					--dan
					  or string_find(obj_name, "sych_")					--stalk1,2,3,4
					  or string_find(obj_name, "kosoi_")				--ne village
					  or string_find(obj_name, "_provodnik")			--boloto_provodnik
					  or string_find(obj_name, "ohotnik")				--hunters
					  or string_find(obj_name, "pantera") then			--panther
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true			--atakker_vert_bandit1,2,3,4,5,6,7,8
					end
				elseif hdr5 == "rad_n"		--rad_nebo_
				  or hdr5 == "val_b"		--val_bandit_
				  or hdr5 == "agr_n"		--agr_nebo_
				  or hdr4 == "sak_"
				  or hdr5 == "boev_"
				  or hdr6 == "prip_n"		--prip_nebo_
				  or hdr6 == "m_trad"
				  or hdr4 == "dyak"			--in shack at cordon south exit
				  or hdr5 == "baza_"		--nebo in cs base
				  or hdr5 == "mitya"
				  or hdr5 == "grab_"
				  or hdr5 == "snip_"
				  or hdr6 == "clear_"
				  or hdr6 == "kalmya"
				  or hdr6 == "syslov" then
					result = true
				elseif hdr5 == "nebo_"										--_exit1,2,3
				  or hdr6 == "esc_sa"										--esc_saha (prisoner at church)
				  or hdr6 == "kashei"
				  or hdr3 == "kot"
				  or hdr4 == "pre_"										--lager_stalker_ukastrika, guard
				  or hdr4 == "gar_"										--seriywff
				  or hdr5 == "brat_"									--brat_luis and freinds
				  or hdr6 == "blizn_"									--_krug1,2
				  or hdr6 == "ferma_" then								--_band1,2,3,4,5,6,7
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "val_ko" then 							--val_kocherga = Poker
					if extended_levels then
						dont_spawn_online = true
					else
						if has_alife_info("dyak_help_done") or has_alife_info("dyak_help_fail") then
							result = true
						end
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "stalker_general")					--kill trader task
					  or string_find(obj_name, "stalker_veteran")				--kill the stalker
					  or string_find(obj_name, "marsh_")
					  or string_find(obj_name, "bandit_general")
					  or string_find(obj_name, "bandit_veteran")
					  or string_find(obj_name, "stalker_novice")
					  then
						result = true
					else
						dont_spawn_online = true
					end
				else
					result = true
				end
			elseif lnum == 31 then
				if hdr3 == "mg_" then			--short circuit known spawns
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "last_n"		--last_nevid_kultorg1,2,3
				  or hdr5 == "city_"						--city_starshoy, city_tema_likvidator (final)
				  or hdr4 == "last"
				  or hdr6 == "sniper"						--sniper1_krusha1, sniper2_1_krusha1, sniper2_2_krusha1 on roof of hdqtrs in final
				  or hdr6 == "dcity2"						--dcity2_dok2_bolot2_vid
				  or hdr6 == "dead_c" then	--panther
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "dcity_" then
					if extended_levels then
						dont_spawn_online = true
					elseif string_find(obj_name, "kontr") then							--110005
						--if has_alife_info("portal_na_mg_done") then
							--dont_spawn_online = true
						--else
							result = true
						--end
					elseif (string_find(obj_name, "last") or string_find(obj_name, "parfumer")) then			--110004, final
						result = true
					--elseif has_alife_info("portal_na_mg_done") then											--110007, stops obmorok from spawning
						--dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sak_"
				  or hdr5 == "stab_"
				  or hdr6 == "dsity_"						--dsity_rasstrel1,2
				  or hdr5 == "vxod_"
				  or hdr6 == "shtab_"
				  or hdr6 == "chasov"
				  or hdr6 == "parfum"
				  or hdr6 == "pregul"						--dcity final
				  or hdr6 == "val_x1"
				  or hdr6 == "kultor"
				  or hdr6 == "patrul" then
					if extended_levels or has_alife_info("spawn_city_last_zentr") then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "dcity_")
					  or string_find(obj_name, "mg_bandit_") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				else
					result = true
				end
			elseif lnum == 32 then
				result = true
			elseif lnum == 33 then
				result = true
			elseif lnum == 34 then
				result = true
			elseif lnum == 35 then
				result = true
			elseif lnum == 36 then
				result = true
			elseif lnum == 37 then
				result = true
			elseif lnum == 38 then
				if hdr5 == "pred_" then													--109998, redone
					if string_find(obj_name, "karatel") then							--109998, friendly (possible quest target)
					  if has_alife_info("predbannik_obmorok_dead") then
						result = true
					  --else
						--dont_spawn_online = true
					  end
					--elseif string_find(obj_name, "baza_army_") or string_find(obj_name, "baza_omon_") then
						--dont_spawn_online = true
					--elseif string_find(obj_name, "baza_vdv_") or string_find(obj_name, "baza_kpp_") then
						--dont_spawn_online = true
					elseif string_find(obj_name, "obmorok")								--110007, tent above cave
					  or string_find(obj_name, "gory_bandit_0002")						--two exo'd bandits with him
					  or string_find(obj_name, "gory_bandit_0003") then
						if has_alife_info("tb3d_obmorok_start") then
							result = true
						--else
							--dont_spawn_online = true
						end
					elseif string_find(obj_name, "smoker") then							--110007
						--dont_spawn_online = true
						if has_alife_info("tb3d_obmorok_start") then
							result = true
						end
					elseif string_find(obj_name, "ohrana")
					  or string_find(obj_name, "_loc")
					  or string_find(obj_name, "seriy")									--also seriywff
					  or string_find(obj_name, "ivancov") then
						--if has_alife_info("tb3d_obmorok_start") then
							result = true
						--else
							--dont_spawn_online = true
						--end
					elseif string_find(obj_name, "baza_com_") then						--freedom (nuetral) comm ctr operators
						if has_alife_info("tb3d_pred_comm") then
							result = true
						--else
							--dont_spawn_online = true
						end
					elseif string_find(obj_name, "baza_vdv_smart") then					--helipad ant. guard and bar/camp
							result = true
					elseif string_find(obj_name, "baza_kpp_smart6") then				--helipad guard post, military
						if has_alife_info("tb3d_pred_comm") then
							result = true
						--else
							--dont_spawn_online = true
						end
					elseif string_find(obj_name, "baza_omon_smart") then
						if has_alife_info("tb3d_spawn_omon") then
							result = true
						end
					elseif string_find(obj_name, "baza_army_smart") then
						if has_alife_info("tb3d_spawn_army") then
							result = true
						end
					else
						result = true
					end
				elseif hdr4 == "pred"			--short circuit known spawns
				  or hdr4 == "sak_"
				  or hdr4 == "pre_"
				  or hdr6 == "esc_st"
				  or hdr6 == "soldie" then
						--TB3D_Services.abort_alert("pred: ["..obj_name.."] !!!!")
					if string_find(obj_name, "killers_baza_killer_guard")
					  or string_find(obj_name, "pre_killers_baza_killer_walk_") then
						if has_alife_info("tb3d_pred_attack") then
							result = true
						else
							dont_spawn_online = true
						end
					elseif string_find(obj_name, "stalker_zombied") then
							--dont_spawn_online = true
						if has_alife_info("tb3d_obmorok_start") then
							result = true
						end
					elseif string_find(obj_name, "gory_bandit_") then
							--dont_spawn_online = true
						--if has_alife_info("tb3d_pred_attack") then
							result = true
						--end
					elseif string_find(obj_name, "bar_free_") then
							--dont_spawn_online = true
						--if has_alife_info("tb3d_pred_attack") then
							result = true
						--end
					elseif string_find(obj_name, "bar_visitors_") then
							--dont_spawn_online = true
						--if has_alife_info("tb3d_pred_attack") then
							result = true
						--end
					elseif string_find(obj_name, "_barman") then
						result = true												--110007
					elseif string_find(obj_name, "_specnaz") then					--nw guard post towers and entry
							--dont_spawn_online = true
							result = true
					elseif string_find(obj_name, "blokpost_") then
						--dont_spawn_online = true
						if has_alife_info("tb3d_pred_attack") then
							result = true
						end
					elseif string_find(obj_name, "st_zombie51")
					  or string_find(obj_name, "st_zombie52") then
						--if amk.load_variable("first_started", 0) < 109975 then
							dont_spawn_online = true
						--else
							--result = true
						--end
					else
						result = true
					end
				elseif hdr5 == "pesh_" then
					result = true
					--dont_spawn_online = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "stalker_veteran")
					  or string_find(obj_name, "bandit_general")
					  or string_find(obj_name, "bandit_veteran")
					  or string_find(obj_name, "bandit_novice")
					  or string_find(obj_name, "stalker_general")
					  then result = true end
				end
			elseif lnum == 39 then --old garbage
				--not used
			elseif lnum == 40 then
				result = true
			elseif lnum == 41 then
				if hdr6 == "swamp_"			--short circuit known spawns
				  or hdr6 == "killer"
				  or hdr4 == "sim_"
				  or hdr4 == "sak_" then
					if string_find(obj_name, "baza") then											--village killers
						if (has_alife_info("zep10_have") and not has_alife_info("tb3d_note_08")) or has_alife_info("tb3d_dm_deserters") then
							result = true
						else
							dont_spawn_online = true
						end
					elseif string_find(obj_name, "tunel") then											--tunnel killers
						if (has_alife_info("zep10_have") and not has_alife_info("zep11_have")) or has_alife_info("tb3d_dm_deserters") then
							result = true
						else
							dont_spawn_online = true
						end
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 42 then
				if hdr3 == "hr_"			--short circuit known spawns
				  or hdr4 == "sak_"
				  or hdr6 == "stalke" then
					result = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "stalker_")
					  then result = true end
				else
					result = true
				end
			elseif lnum == 43 then
				if hdr3 == "ds_"			--short circuit known spawns
				  or hdr3 == "df_"
				  or hdr6 == "dar_za"
				  or hdr6 == "darska"
				  or hdr4 == "sak_"
				  or hdr6 == "bandit" then
						result = true
				elseif hdr6 == "darsk_" then										--ctd on going offline
					result = true
				--elseif hdr6 == "fallin" then										--add to fix
					--db.check_car_fix(obj)
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "bandit_") then result = true end
				else
					result = true
				end
			elseif lnum == 44 then
				if hdr3 == "df_"			--short circuit known spawns
				  or hdr6 == "dark_f" 		--belong only in df
				  or hdr4 == "sak_" then
					result = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "stalker_veteran2")
					  or string_find(obj_name, "stalker_veteran1")
					  or string_find(obj_name, "bandit_") then
						result = true
					end
				else
					result = true
				end
			elseif lnum == 45 then
				if hdr3 == "f1_"			--short circuit known spawns
				  or hdr4 == "sak_" then
					result = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "stalker_general2")
					  or string_find(obj_name, "bandit_")
					  then result = true end
				else
					result = true
				end
			elseif lnum == 46 then
				if hdr6 == "swamp_" then		--controller
					dont_spawn_online = true
				else
					result = true
				end
			elseif lnum == 47 then
				--dead_city used instead
			elseif lnum == 48 then
				if hdr4 == "l01_"			--short circuit known spawns
				  or hdr4 == "sak_"
				  or hdr5 == "kras_" then
					result = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "stalker_general")
					  or string_find(obj_name, "bandit_")
					  then result = true end
				else
					result = true
				end
			elseif lnum == 49 then
				if hdr4 == "l02_"			--short circuit known spawns
				  or hdr3 == "dd_"
				  or hdr3 == "dm_"
				  or hdr3 == "ds_"
				  or hdr4 == "sak_" then
					if string_find(obj_name, "l02_zombie_")						--path errors
					  or string_find(obj_name, "zaloj") then					--dd_ds_zaloj1,2				--don't use
						dont_spawn_online = true
					elseif string_find(obj_name, "dm_mil_h1")					--path errors
					  or string_find(obj_name, "dm_mil_h3") then				--wait for snitch
						if not has_alife_info("kras_el_razvvdm") then
							result = true
						end
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "stalker_general")
					  or string_find(obj_name, "bandit_")
					  then result = true end
				else
					result = true
				end
			elseif lnum == 50 then
				if hdr4 == "l03_"			--short circuit known spawns
				  or hdr4 == "sak_" then
					if string_find(obj_name, "stalker_") then
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "bandit_")
					  then result = true end
				else
					result = true
				end
			elseif lnum == 51 then
				if hdr4 == "l04_"			--short circuit known spawns
				  or hdr4 == "sak_" then
					result = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "stalker_general")
					  or string_find(obj_name, "bandit_")
					  then result = true end
				else
					result = true
				end
			elseif lnum == 52 then
				if hdr4 == "l05_"			--short circuit known spawns
				  or hdr4 == "sak_"
				  or hdr6 == "vokzal" then
					result = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "stalker_general")
					  or string_find(obj_name, "bandit_")
					  then
						result = true
					end
				else
					result = true
				end
			elseif lnum == 53 then
				result = true
			elseif lnum == 54 then
				if hdr4 == "x14_"			--short circuit known spawns
				  or hdr4 == "sak_"
				  or hdr4 == "sim_" then
					if string_find(obj_name, "monolith_1") then
						if has_alife_info("x14_glavny_death") then
							result = true
						else
							dont_spawn_online = true
						end
					else
						result = true
					end
				elseif hdr6 =="glavny" then
					if TB3D_Services.targets_killed(2) > 19 then
						result = true
					end
				else
					result = true
				end
			elseif lnum == 55 then --collector22
				--part of x14
			elseif lnum == 56 then
				result = true
			end
			--------------------------------------------- level spawns end -----------------------------------
			if dont_spawn_online then					--collector levels
				obj.dont_spawn_online = true
				result = false
				if is_report or TB3D_Modders.pop_spawn_message then
					TB3D_Services.packet_alert("population control: stalker can go online["..obj_name.."] dont spawn online!!!!")
				end
			elseif is_report then
				if result == true then
					TB3D_Services.packet_alert("population control: stalker can go online["..obj_name.."] [true]")
				else
					TB3D_Services.packet_alert("population control: stalker can go online["..obj_name.."] [false]")
				end
			end
		end						--is_spawner
	else
		TB3D_Services.packet_alert("population control: stalker can go online obj or obj.name nil")
		result = false
	end
	return result
end

function monster_can_go_online(obj)		--110000, called by se_monster
	if db.actor == nil then return false end
	local result = false
	if obj and obj.name then
		if is_spawner then									-- _g.is_spawner set by ui_si spawn menu
			is_spawner = false
			result = true
		else
			local is_report = false
			local extended_levels = TB3D_Services.is_collector(81)
			local sect = get_section(obj)			--110000
			local lname = level.name()
			local lnum = get_level_index(lname)		--110004
			obj_name = obj:name()
			dont_spawn_online = false
			if TB3D_Modders.use_setup_message and string_find(obj_name, TB3D_Modders.npc_to_log) then is_report = true end
			hdr6 = string_sub(obj_name, 1, 6)
			hdr5 = string_sub(hdr6, 1, 5)
			hdr4 = string_sub(hdr5, 1, 4)
			hdr3 = string_sub(hdr4, 1, 3)
			if TB3D_Services.is_instorm(lname) then
				if (hdr6 == "tb3dm_" or hdr4 == "amk_")
				  and (string_find(obj_name, "turret")
					or string_find(obj_name, "zombie")
					or string_find(obj_name, "poltergeist")
					or string_find(obj_name, "psy_dog")) then
						result = true
				end
			elseif string_sub(sect, 1, 5) == "zone_" or sect == "inventory_box" then
				result = true
			elseif hdr4 == "amk_" or hdr5 == "tb3d_" or hdr6 == "tb3dm_" or hdr6 == "dogfre" or hdr6 == "turret" then		--all levels
				result = true
			---------------------------------- RESPAWNS ------------------------------------------
			elseif sect == "respawn" or string_find(obj_name, "respawn") then			--respawners in the all.spawn
				result = check_respawn(lnum)
			-------------------------------- specific spawns --------------------------------
			elseif check_specific(lnum) then
				result = false
			--------------------------------------- level spawns --------------------------------------------
			elseif lnum == 1 then
				if hdr4 == "esc_"							--short circuit known spawns
				  or hdr4 == "ens_"
				  or hdr4 == "sak_"
				  or hdr5 == "esc2_"
				  or hdr6 == "escape"
				  or hdr6 == "zapasn"		--zapasnoy_foto_muzhik
				  or hdr6 == "mill_s"		--mill_sniper_nick, harris, jonn, croker
				  or hdr6 == "zvezd_"		--zvezd_after_warl
				  or hdr6 == "kordon"
				  or hdr6 == "snip_e"		--snip_esc1 thru 13
				  or hdr6 == "xalyav" then	--xalyava, xalyava_naem1 thru 7
					if string_find(obj_name, "tushkano") then
						if has_alife_info("esc_darklab_documents_read") then		--keep them out until cordon story quests are done (esc_return gets removed)
							result = true
						end
					elseif string_find(obj_name, "pseudodog_strong") then		--causes motivator crashes if after fanat_spawn
						if not has_alife_info("esc_fox_thanks") then
							--dont_spawn_online = true
						--else
							result = true
						end
					--elseif string_find(obj_name, "rat") then			--for testing
						--if extended_levels then
							--dont_spawn_online = true
						--else
							--result = true
						--end
					elseif string_find(obj_name, "boar_weak_0006") then			--causes path errors
						dont_spawn_online = true
					elseif string_find(obj_name, "snork")
					  or string_find(obj_name, "fracture") then
						if has_alife_info("bar_deactivate_radar_done") then
							result = true
						end
					elseif string_find(obj_name, "dog_swarm_") then					--still crashes on going offline
						if TB3D_Modders.spawn_esc_dog_rush then
							if has_alife_info("esc_fox_thanks") then
								result = true
							end
						else
							dont_spawn_online = true
						end
					elseif string_find(obj_name, "dog_weak_00") then
					  --or string_find(obj_name, "rat_strong")						--cannot remove restriction with id [5471][esc_zone_witches_galantine]
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				elseif hdr4 == "gar_" then											--bandits, novice
					result = true
				elseif hdr4 == "val_" then
					result = true
				elseif hdr5 == "dead_" then
					result = true
				elseif hdr6 == "rat_st" then
					if string_find(obj_name, "strong412") then	--cannot remove restriction with id [5471][esc_zone_witches_galantine]
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr5 == "boar_k" then								--boar_kachok
					dont_spawn_online = true
				elseif string_find(obj_name, "tushkano") then
					if has_alife_info("esc_darklab_documents_read") then					--keep them out until cordon story quests are done
						result = true
					end
				elseif string_find(obj_name, "snork")
				  or string_find(obj_name, "fracture") then
					if has_alife_info("bar_deactivate_radar_done") then
						--dont_spawn_online = true
						result = true
					end
				elseif string_find(obj_name, "burer") then							--110009, never in cordon
					dont_spawn_online = true
				else
					result = true
				end
			elseif lnum == 2 then
				if hdr4 == "gar_"			--short circuit known spawns
				  or hdr4 == "sak_"
				  or hdr4 == "amk_"			--109987, vitek_voron the trader, amk_artem_kulinar
				  or hdr6 == "garbag"
				  or hdr6 == "svalka"
				  or hdr6 == "tamaz_" then
					if string_find(obj_name, "himera") then		--keep them from effecting robbers and bes quests
						if has_alife_info("agr_find_gunslinger_cache_final") then
							result = true
						else
							dont_spawn_online = true
						end
					else
						result = true
					end
				elseif hdr4 == "agr_" then		--factory defense and dogs
					result = true
				elseif hdr4 == "val_" then		--escort captive, nap1, dogs, rats and bandits
					result = true
				elseif hdr4 == "esc_" then
					result = true
				elseif hdr4 == "sim_" then									--see if allowed simulation
					result = true
				elseif string_find(obj_name, "himera") then		--keep them from effecting robbers and bes quests
					if has_alife_info("agr_find_gunslinger_cache_final") then
						result = true
					end
				else
					result = true
				end
			elseif lnum == 3 then
				if hdr4 == "sak_" then			--short circuit known spawns
					result = true					--mil trader
				elseif hdr4 == "gar_" then
					result = true
				elseif hdr4 == "esc_" then
					dont_spawn_online = true
				elseif hdr5 == "agro_" or hdr4 == "agr_" then
					if string_find(obj_name, "_zone")
					  or string_find(obj_name, "_flesh")
					  or string_find(obj_name, "dog_")
					  or string_find(obj_name, "_nii_") then
						result = true
					elseif string_find(obj_name, "bloodsucker_normal") then				--109961  NEED CHECK BLOODSUCKERS!!!!
						dont_spawn_online = true
					elseif string_find(obj_name, "boar_0001") then
						if has_alife_info("prodaznay_tvar") then						--109955 interferes with agro final
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 4 then
				if hdr4 == "agr_"			--short circuit known spawns
				  or hdr4 == "sim_"
				  or hdr4 == "sak_" then
					if string_find(obj_name, "tarakan_strong") then
						if has_alife_info("agr_u_controller_start") then
							result = true
						end
					elseif string_find(obj_name, "_m_controller_old_0000") then
						if has_alife_info("tb3d_skip_group1a") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif string_find(obj_name, "tarakan_strong") then
					if has_alife_info("agr_u_controller_start") then
						result = true
					end
				else
					result = true
				end
			elseif lnum == 5 then
				if hdr4 == "val_" then			--short circuit known spawns
					result = true
				elseif hdr6 == "yan_ec" then
					result = true
				elseif hdr4 == "dar_" or hdr4 == "gar_" or hdr4 == "agr_" or hdr6 == "mil_bo" then
					if string_find(obj_name, "_boar_") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "m_dog_e_") then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "dark_b" 		--dark btr
				  or hdr6 == "dark_s" 		--dark btr soldiers
				  or hdr6 == "bland_" 		--belong only in DV
				  or hdr4 == "sak_" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr3 == "dt_"			--dark valley only, gigant
				  or hdr3 == "f1_" then			--dark valley only, creatures
					result = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					result = true
				elseif hdr6 == "bloods" then									--109989
					if has_alife_info("bar_deactivate_radar_done") then
						result = true
					else
						dont_spawn_online = true
					end
				else
					result = true
				end
			elseif lnum == 6 then
				if hdr4 == "x18_"			--short circuit known spawns
				  or hdr4 == "lab_"
				  or hdr4 == "dar_"
				  or hdr4 == "sak_" then
					if string_find(obj_name, "m_poltergeist_normal_flame_0000") then				--dead scientists
						if has_alife_info("tb3d_skip_group1") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "fractu" then
					if has_alife_info("dar_codelock1_unlock") then
						result = true
					end
				else
					result = true
				end
			elseif lnum == 7 then
				if hdr6 == "bar_m_" then			--bar_m_dog_
					if has_alife_info("naemn_shturm_poluch_start") and not has_alife_info("gorb_ubit") then			--109998, reduce population during hump quest
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "bar_" then									--bar_stalker_0005 = arena fight 1, _0006 = fight 2, 7 & 8 = 3, 9 - 13 = 4, 14 & 15 = 5, 16 - 21 = 6, 22 = 7, 23 - 26 = 8
					result = true
				elseif hdr4 == "sak_" then
					result = true
				elseif hdr4 == "rat_" then
					if has_alife_info("naemn_shturm_poluch_start") and not has_alife_info("gorb_ubit") then			--109998, reduce population during hump quest
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "fractu" then
					if has_alife_info("naemn_shturm_poluch_start") and not has_alife_info("gorb_ubit") then			--109998, reduce population during hump quest
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "m_cont" then
						if has_alife_info("bar_deactivate_radar_done") then			--too soon for actor to take on
							result = true
						end
				elseif hdr6 == "burer_" then
					if has_alife_info("info_way_arhara_bar_atp") then
						result = true
					end
				elseif hdr6 == "chimer" then			--109999, needed for arena
					result = true
				else
					result = true
				end
			elseif lnum == 8 then
				if hdr6 == "rad_m_" then				--psuedodog
					result = true
				elseif hdr6 == "rostok"	then
					if string_find(obj_name, "stalker_zombied") then	--rostok_stalker_zombied, _0000, 1, 3, 4, 5, 6
						if extended_levels then --or has_alife_info("tb3d_skip_group1") then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "_dog_strong")				--rostok_dog_strong_0000, 1, 2
					  or string_find(obj_name, "_dog_normal") then				--rostok_dog_normal, _0000, 1, 2
						if extended_levels then
							dont_spawn_online = true
						elseif has_alife_info("rostok_band5_spawn") or has_alife_info("tb3d_skip_group1") then		--share ros_heli_dog_home waypoint
							dont_spawn_online = true						--waypoint ok, still unsure what the cause is
						else
							result = true
						end
					elseif string_find(obj_name, "pseudodog") then			--rostok_pseudodog_weak
						if has_alife_info("rostok_band5_spawn") or has_alife_info("tb3d_skip_group1") then		--share ros_heli_dog_home waypoint
							dont_spawn_online = true						--waypoint ok, still unsure what the cause is
						else
							result = true
						end
					elseif string_find(obj_name, "tele_outdoor")			--rostok_m_poltergeist_tele_outdoor, _0000
					  or string_find(obj_name, "bloodsucker")	then		--rostok_bloodsucker_strong
						if has_alife_info("rostok_band5_spawn") or has_alife_info("tb3d_skip_group1") then		--have smart terrains
							dont_spawn_online = true						--has not been investigated
						else
							result = true
						end
					else
						result = true
					end
				elseif hdr6 == "electr" then								--electro_chimera
					if extended_levels then --or has_alife_info("tb3d_skip_group1") then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "gar_" then
					dont_spawn_online = true
				elseif hdr6 == "genera" then				--109989
					dont_spawn_online = true
				elseif hdr6 == "bloods" then				--109989, bloodsucker_effector
					if has_alife_info("yan_find_scientist_done") then
						result = true
					else
						dont_spawn_online = true
					end
				else
					result = true
				end
			elseif lnum == 9 then
				if hdr4 == "yan_" then			--short circuit known spawns
					if string_find(obj_name, "home_snork_") then				--clear the snorks mini quest
						result = true
					else
						result = true
					end
				elseif hdr4 == "sak_"
				  or hdr6 == "cherno" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "factor" then								--snorks
					if extended_levels then --or has_alife_info("tb3d_skip_group1") then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "fractu" or hdr6 == "snork_"
					or hdr6 == "pseudo" or hdr4 == "dog_" then
					if has_alife_info("yan_scientist_return_to_bunker") then
						--dont_spawn_online = true
						result = true
					end
				elseif hdr6 == "bloods" or hdr4 == "rat_" or hdr4 == "cat_" then		--keep them for next trip through tunnel
					if has_alife_info("yan_kill_brain_done") then
						result = true
					else
						dont_spawn_online = true
					end
				elseif hdr6 == "yantar" then
					if string_find(obj_name, "stalker_zombied") then
						if extended_levels then
							dont_spawn_online = true
						elseif string_find(obj_name, "_zombied_0027")
						  or string_find(obj_name, "_zombied_0029")
						  or string_find(obj_name, "_zombied_0030") then				--in tunnel
							if has_alife_info("yan_has_ghost_pda")
							  and not has_alife_info("yan_kill_brain_done") then
								result = true
							else
								dont_spawn_online = true
							end
						elseif string_find(obj_name, "_zombied_003")
						  or string_find(obj_name, "_zombied_004") then
							--if has_alife_info("tb3d_skip_group1") then
								--dont_spawn_online = true
							if has_alife_info("yan_find_scientist_done") then
								result = true
							else
								dont_spawn_online = true
							end
						elseif string_find(obj_name, "_zombied_0000")
						  or string_find(obj_name, "_zombied_0013")
						  or string_find(obj_name, "_zombied_0014") then
							if has_alife_info("yan_scientist_return_to_bunker") then
								result = true
							else
								dont_spawn_online = true
							end
						else
							result = true
						end
					elseif string_find(obj_name, "chernomor") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					elseif string_find(obj_name, "gulag_zombies")
					  or string_find(obj_name, "kontroller_yazva") then					--keep away until research complete
						if has_alife_info("yan_find_scientist_done") then -- and not has_alife_info("tb3d_skip_group1") then
							result = true
						end
					else
						result = true
					end
				elseif hdr6 == "burer_" then
					if has_alife_info("yan_kill_brain_done") then
						result = true
					end
				elseif string_find(obj_name, "ekolog_zombi") then
					if extended_levels then --or has_alife_info("tb3d_skip_group1") then
						dont_spawn_online = true
					elseif has_alife_info("yan_has_ghost_pda") then
						dont_spawn_online = true
					else
						result = true
					end
				elseif string_find(obj_name, "himera") then						--blocks door
					if has_alife_info("yan_kill_brain_done") then
						result = true
					end
				else
					result = true
				end
			elseif lnum == 10 then
				if hdr6 == "x16_m_" then										--controller
					if extended_levels or has_alife_info("tb3d_skip_group1") then
						dont_spawn_online = true
					else
						--dont_spawn_online = true
						result = true
					end
				elseif hdr4 == "x16_" then										--short circuit known spawns
					if string_find(obj_name, "home_snork") then
						if string_find(obj_name, "_0013") then					--ctd on going offline
							dont_spawn_online = true
						elseif extended_levels then
							dont_spawn_online = true
						else
							--dont_spawn_online = true
							result = true
						end
					elseif string_find(obj_name, "zombied") then
						if extended_levels then --or has_alife_info("tb3d_skip_group1") then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				elseif hdr6 == "brainl"			--brainlab_
				  or hdr6 == "saxar_"			--saxar_
				  or hdr6 == "foto_m"			--foto_monolitovets
				  or hdr4 == "dar_"
				  or hdr4 == "sak_" then
					if not string_find(obj_name, "m_poltergeist") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				elseif hdr6 == "fractu" or hdr6 == "snork_" then
					if has_alife_info("yan_kill_brain_done") then
						result = true
					end
				elseif hdr4 == "rat_" then
					result = true
				elseif hdr6 == "burer_" then
					if has_alife_info("yan_kruglov_decoder_have") then
						result = true
					end
				else
					result = true
				end
			elseif lnum == 11 then												--l07_military
				if hdr4 == "sak_"				--short circuit known spawns
				  or hdr6 == "m_cont" then
					result = true
				elseif string_find(obj_name, "bloodsucker_weak") then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
					--dont_spawn_online = true
				end
			elseif lnum == 12 then
				result = true
			elseif lnum == 13 then
				if hdr6 == "taraka" then		--wait til after zep doc 5 in collector
					if extended_levels then
						if has_alife_info("zep05_have") then
							result = true
						else
							dont_spawn_online = true
						end
					else
						result = true
					end
				elseif hdr4 == "rat_" then
					if has_alife_info("aes_arrive_to") then					--109974, what til after stadium as too much going on
						result = true
					else
						dont_spawn_online = true
					end
				else
					result = true
				end
			elseif lnum == 14 then
				result = true
			elseif lnum == 15 then
				result = true
			elseif lnum == 16 then
				if hdr6 == "mon_m_"	then		--polter
					result = true
				else
					result = true
				end
			elseif lnum == 17 then
				if hdr6 == "chaes2"			--chaes2_mono_fugas
				  or hdr6 == "monoli"		--monolit_truba
				  or hdr4 == "sak_" then
					if extended_levels then
						if string_find(obj_name, "snork") then
							result = true
						else
							dont_spawn_online = true
						end
					else
						result = true
					end
				elseif hdr6 == "m_cont"												--110004, after guantlet
				  or hdr6 == "mon_m_" then											--mon_m_poltergeist_normal_flame_0001
					if not has_alife_info("tb3d_chaes_done") then
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 18 then
				if hdr4 == "bun_"			--short circuit known spawns
				  or hdr4 == "rad_"
				  or hdr4 == "sak_" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "bun2" then
					if extended_levels then
						dont_spawn_online = true
					else
						if has_alife_info("rad_start_monolith_vs_military") then			--wait til next visit
							result = true
						end
					end
				else
					result = true
				end
			elseif lnum == 19 then
				result = true
			elseif lnum == 20 then
				if hdr6 == "pesher"			--short circuit known spawns
				  or hdr4 == "sak_" then
					result = true
				elseif hdr6 == "blood_"	then					--av_peshera only
					dont_spawn_online = true
				else
					result = true
				end
			elseif lnum == 21 then
				result = true
			elseif lnum == 22 then
				result = true
			elseif lnum == 23 then
				if hdr3 == "av_"			--short circuit known spawns
				  or hdr6 == "blood_"			--av_peshera only
				  or hdr4 == "sak_" then
					if string_find(obj_name, "effector_av") then		--109989 path errors av1 and av2
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "av_") then
						result = true
					end
				elseif string_find(obj_name, "pseudodog_strong") then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 24 then
				if hdr4 == "lim_"			--short circuit known spawns
				  or hdr4 == "sak_"
				  or hdr6 == "zombie"
				  or hdr6 == "m_cont" then
					result = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr6 == "rad_pr" then										--109981, rad_prip_teleport_
					dont_spawn_online = true
				else
					result = true
				end
			elseif lnum == 25 then
				if hdr4 == "hos_"			--short circuit known spawns
				  or hdr6 == "hospit"
				  or hdr6 == "muha_h"
				  or hdr6 == "black_"
				  or hdr5 == "hosp_"
				  or hdr4 == "sak_" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "hospital_") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				else
					result = true
				end
			elseif lnum == 26 then
				if hdr4 == "gen_"			--short circuit known spawns
				  or hdr6 == "gener_"
				  or hdr6 == "genera" then		--110003
					result = true
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "generators_")
					  or string_find(obj_name, "gener_") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				else 
					result = true
				end
			elseif lnum == 27 then
				if hdr4 == "war_"			--short circuit known spawns
				  or hdr6 == "warlab"
				  or hdr4 == "sak_" then
					if extended_levels then
						if string_find(obj_name, "bloodsucker") then
							result = true
						else
							dont_spawn_online = true
						end
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if string_find(obj_name, "warlab_") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					end
				else
					result = true
				end
			elseif lnum == 28 then
				if hdr4 == "red_"			--short circuit known spawns
				  or hdr6 == "redfor"
				  or hdr6 == "forest"
				  or hdr6 == "shadow"
				  or hdr6 == "stalk_"
				  or hdr6 == "contr_"
				  or hdr4 == "for_"
				  or hdr4 == "sak_"
				  or hdr4 == "psy_" then
					if string_find(obj_name, "contr_forest") then
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				else		--if hdr4 == "sim_" then										--see if allowed simulation
					result = true
				end
			elseif lnum == 29 then
				if hdr5 == "lost_"			--short circuit known spawns
				  or hdr6 == "after_"
				  or hdr4 == "sak_" then
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sim_" then										--see if allowed simulation
					if extended_levels then
						dont_spawn_online = true
					elseif string_find(obj_name, "village_") then
						result = true
					end
				else
					result = true
				end
			elseif lnum == 30 then
				if hdr6 == "marsh_"
				  or hdr6 == "boloto" then				  				
					if string_find(obj_name, "controller") then				--nw village
						if extended_levels then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 31 then
				if hdr3 == "mg_" then			--short circuit known spawns
					if extended_levels then
						dont_spawn_online = true
					else
						result = true
					end
				elseif hdr4 == "sak_"
				  or hdr5 == "city_"
				  or hdr5 == "stab_"
				  or hdr5 == "vxod_"
				  or hdr6 == "dsity_"						--dsity_rasstrel1,2
				  or hdr6 == "dcity_"
				  or hdr6 == "dcity2"
				  or hdr6 == "dead_c"
				  or hdr6 == "shtab_"
				  or hdr6 == "val_x1"
				  or hdr6 == "kultor"
				  or hdr6 == "patrul" then
					if string_find(obj_name, "bloodsucker_most") then			--109961 NEED CHECK BLOODSUCKERS!!!!
						dont_spawn_online = true
					elseif extended_levels then
						if string_find(obj_name, "biblio")
						  or string_find(obj_name, "bloodsucker")
						  or string_find(obj_name, "burer")
						  or string_find(obj_name, "gigant")
						  or string_find(obj_name, "tushkano")
						  or string_find(obj_name, "snork") then
							result = true
						else
							dont_spawn_online = true
						end
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 32 then
				result = true
			elseif lnum == 33 then
				result = true
			elseif lnum == 34 then
				result = true
			elseif lnum == 35 then
				result = true
			elseif lnum == 36 then
				result = true
			elseif lnum == 37 then
				result = true
			elseif lnum == 38 then
				if hdr5 == "pred_" then											--109998, redone
					result = true
				elseif hdr4 == "pred"			--short circuit known spawns
				  or hdr3 == "st_"
				  or hdr4 == "sak_"
				  or hdr4 == "pre_"
				  or hdr6 == "esc_st" then
					if string_find(obj_name, "bloodsucker_strong") then
						if has_alife_info("predbannik_obmorok_dead") then
							result = true
						else
							dont_spawn_online = true
						end
					elseif string_find(obj_name, "predbannik_trader") then				--110007, now predbannik_m_trader
						--TB3D_Services.abort_alert("blocked: ["..obj_name.."] !!!!")
						dont_spawn_online = true
					elseif string_find(obj_name, "m_trader") then				--sitting traders are monsters
						result = true
						--dont_spawn_online = true
					elseif amk.load_variable("first_started", 0) < 109975 then
						if string_find(obj_name, "st_dog91")					--109975, fixed smts
						  or string_find(obj_name, "st_dog93")
						  or string_find(obj_name, "st_dog93")
						  or string_find(obj_name, "st_dog95")
						  or string_find(obj_name, "st_dog174")
						  or string_find(obj_name, "st_dog172")
						  or string_find(obj_name, "st_boar71")
						  or string_find(obj_name, "st_boar42")
						  or string_find(obj_name, "st_boar46")
						  or string_find(obj_name, "st_boar46")
						  or string_find(obj_name, "st_boar62")
						  or string_find(obj_name, "st_boar122")					--bad paths
						  or string_find(obj_name, "st_zombie51")
						  or string_find(obj_name, "st_zombie52")
						  or string_find(obj_name, "st_boar74")
						  or string_find(obj_name, "st_tushkano18")			--gets grabbed by promz_tushkano3 smart
						  or string_find(obj_name, "st_boar43") then
							dont_spawn_online = true
						else
							result = true
						end
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 39 then
				--not used
			elseif lnum == 40 then
				result = true
			elseif lnum == 41 then
				if hdr6 == "swamp_"			--short circuit known spawns
				  or hdr4 == "sak_" then
					if string_find(obj_name, "controller2_1") then						--in shack, wait for bars quest
						if has_alife_info("tb3d_goldbar_10") then
							result = true
						else
							dont_spawn_online = true
						end
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 42 then
				if hdr3 == "hr_"			--short circuit known spawns
				  or hdr4 == "sak_" then
					if string_find(obj_name, "_tushkano")						--bad paths
					  or string_find(obj_name, "_dog") then
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 43 then
				--if hdr6 == "fallin" then										--add to fix
					--db.check_car_fix(obj)
				--end
				result = true
			elseif lnum == 44 then
				result = true
			elseif lnum == 45 then
				result = true
			elseif lnum == 46 then
				if hdr6 == "swamp_" then		--controller
					dont_spawn_online = true
				else
					result = true
				end
			elseif lnum == 47 then
				--not used
			elseif lnum == 48 then
				result = true
			elseif lnum == 49 then
				if hdr4 == "l02_" then			--short circuit known spawns
					if string_find(obj_name, "l02_zombie_")						--path errors
					  or string_find(obj_name, "zaloj") then					--dd_ds_zaloj1,2				--don't use
						dont_spawn_online = true
					else
						result = true
					end
				else
					result = true
				end
			elseif lnum == 50 then
				result = true
			elseif lnum == 51 then
				result = true
			elseif lnum == 52 then
				result = true
			elseif lnum == 53 then
				result = true
			elseif lnum == 54 then
				result = true
			elseif lnum == 55 then
				--not used
			elseif lnum == 56 then
				result = true
			end
			--------------------------------------------- level spawns end -----------------------------------
			if dont_spawn_online then					--collector levels
				obj.dont_spawn_online = true
				result = false
				if is_report or TB3D_Modders.pop_spawn_message then
					TB3D_Services.packet_alert("population control: monster can go online["..obj_name.."] dont spawn online!!!!")
				end
			elseif is_report then
				if result == true then
					--TB3D_Services.packet_alert("population control: monster can go online["..obj_name.."] [true]")
				else
					TB3D_Services.packet_alert("population control: monster can go online["..obj_name.."] [false]")
				end
			end
		end						--is_spawner
	else
		TB3D_Services.packet_alert("population control: monster can go online obj or obj.name nil")
		result = false
	end
	return result
end
