---TB3D 1.1.0.0.0.9 key game trigger points for expanding the Collector 11/10/11, missing backwater_anoms(),
-- added monolith_over, added game ending alternatives for free play, night creatures,
-- removed fake_ from relocate and spawn item in inv, sid door spawns,radzones, hogg, bar radzones, fanat_laptop_have,
-- tunnel_rat, dynamic spawns, random tanks, din_rad deactivated until fixed, spawn_sak_trader, sak_book4,
-- localized strings, delayed_action, delayed action give info, gold bars, send_tip_id optimization, zaton_lost,
-- NPP1, sleep place, creatures of the night, bar portals, clinic bed, mon over, suits, more spawn functions, get_level_up
-- spawn_enemy_at, random koef, reduced some spawns, tunnel rat, spawn_npcs, check_bar_drop, portals, make_camp_friends(),
-- old_research_send, spawn_sewer_stuff, zat lost, night creatures, collector mobs, jup and jupu random, lim_remove_electros,
-- rsrch_stash, reduced some creatures of the night, jupu tank
function my_ver() return "1.1.0.0.0.9" end
---these trigger points are being re-used for the Collector gameplay
local math_random = math.random
local math_floor = math.floor
local math_ceil = math.ceil
local string_find = string.find

local translate = game.translate_string

--[[	TB3D_Services.remove_info("my1")		to be used as modders interface
	TB3D_Services.remove_info("my2")
	TB3D_Services.remove_info("my3")
	TB3D_Services.remove_info("my4")
	TB3D_Services.remove_info("my5")
	TB3D_Services.remove_info("my6")
	TB3D_Services.remove_info("my7")
	TB3D_Services.remove_info("my8")
	TB3D_Services.remove_info("my9")
	TB3D_Services.remove_info("my10")
	TB3D_Services.remove_info("my11")]]--

---------------------------------- Cordon --------------------------------------------------
-- from arhara_dialog.script 'spawn outfit to Zvedocheta and give to stalker'
-- split into two dialog parts for better response
-- these items are spawned directly, will crash if item non-existant!
function noz_dat1(first_speaker, second_speaker) 
	if TB3D_Modders.default_items then
		amk.spawn_in_inv("bolt", 1)
		amk.spawn_item_in_inv("novice_outfit_rain_1", second_speaker)
		if use_ammo_belt then amk.spawn_item_in_inv("razgruzka",first_speaker) end
		dialogs.relocate_item_section(second_speaker, "novice_outfit_rain_1","in")
	else   ---------give it to me baby!!!
		amk.spawn_item_in_inv("outfit_specnaz_m1",first_speaker)
		amk.spawn_item_in_inv("razgruzka",first_speaker)  --ammo vest
		amk.spawn_item_in_inv("wpn_fn2000_sniper",first_speaker)
		amk.spawn_item_in_inv("wpn_spas12",first_speaker)
		amk.spawn_item_in_inv("wpn_fs",first_speaker)
		amk.spawn_in_inv("af_blood", 4)
		amk.spawn_in_inv("bolt", 20)
		amk.spawn_in_inv("ammo_7.62x54_ap", 6)
		amk.spawn_in_inv("ammo_zhekan_izomorf", 6)
		amk.spawn_in_inv("ammo_5.7x28_ss190", 6)
		amk.spawn_in_inv("ammo_m209", 4)
		amk.spawn_in_inv("grenade_rgd5", 6)
		amk.spawn_item_in_inv("detektor_amorf",first_speaker)
		amk.spawn_item_in_inv("det_artefact_super",first_speaker)
		amk.spawn_item_in_inv("detector_elite_john",first_speaker)
		amk.spawn_item_in_inv("amk_transmutator",first_speaker)
		amk.spawn_item_in_inv("mine_detector",first_speaker)
	end
end

--' obtain first-aid kit knife and binoculars from Zvedocheta
function noz_dat2(first_speaker, second_speaker)
	if TB3D_Modders.default_items then
		dialogs.relocate_item_section(second_speaker, "wpn_pm","in")
		dialogs.relocate_item_section(second_speaker, "wpn_knife","in")
		dialogs.relocate_item_section(second_speaker, "medkit","in")
		dialogs.relocate_item_section(second_speaker, "wpn_binoc","in")
	else   -----------------------------------------------------------item testing
		amk.spawn_item_in_inv("fake_wpn_arm_binoc",first_speaker)
		amk.spawn_item_in_inv("fake_wpn_knife",first_speaker)
		amk.spawn_item_in_inv("medkit",first_speaker)
		amk.spawn_item_in_inv("player",first_speaker)
		amk.spawn_item_in_inv("matras",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_1",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_2",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_3",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_4",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_5",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_6",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_7",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_8",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_9",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_10",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_11",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_12",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_13",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_14",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_15",first_speaker)
		amk.spawn_item_in_inv("ogg_flash_16",first_speaker)
	end
end

function save_start()
	amk.start_timer("autosave",10,"STALKER Start")					--initial save for stalker level
end

function bandranen_pda()				--in collector mode
	news_manager.amk_send_tip_id("sms_bandranen_pda","sms_unknown",20,20,"killer")
end

function spawn_esc_medkit()
	alife():create("esc_medkit", vector():set(-86.2782745361328,-4.92963171005249,-78.3331451416016),594270,0)	--tolik wounded medkit	
end

function moroz_sms()	--message about backpacks
	spawn_alife_rand("dog_normal",-68.769,-4.010,-86.216,204914,76,8)	--add more fun to the area
	spawn_alife_rand("boar_normal",-29.255,-11.466,-88.712,247847,111,6)
	spawn_alife_rand("boar_normal",-88.425,-8.670,-134.431,176700,107,6)
	spawn_alife_rand("dog_habaruch",-69.532,-12.072,-143.237,203836,107,8)
	spawn_alife_rand("tarakan_normal",-253.517,-13.797,-13.596,8840,67,8)
	spawn_alife_rand("tarakan_normal",-247.438,-14.354,-18.323,11500,67,6)
	spawn_alife_rand("tarakan_normal",-253.517,-13.797,-13.596,8840,67,6)
end

function sidor_piyn_sms()	--Sid's door, arhara_dialog.script
	--news_manager.amk_send_tip_id("sms_coll_greet","sms_sid",10,20,"trader")
	spawn_alife_rand("dog_strong",-80.955,-4.894,-74.731,186568,76,6)	--add more fun to the area
	spawn_alife_rand("dog_habaruch",-80.955,-4.894,-74.731,186568,76,6)
end

function kanal_sms()	--warning about artifacts
	news_manager.amk_send_tip_id("sms_plenty_ammo","sms_tb3d",10,20,"tb3d_master")
	spawn_alife_rand("flesh_strong",45.923,1.076,319.172,329924,192,8)
	spawn_alife_rand("dog_habaruch",70.505,0.709,356.311,362035,195,6)
	spawn_alife_rand("dog_strong",122.305,1.829,365.377,426437,229,6)
	spawn_alife_rand("bloodsucker_normal",106.758,1.541,459.684,408586,221,2)
	spawn_alife_rand("tarakan_normal",106.758,1.541,459.684,408586,221,8)
end

function esc_fox_quest()
	news_manager.amk_send_tip_id("sms_being_hunted","sms_tb3d",10,20,"tb3d_master")
	spawn_alife_rand("dog_strong",122.305,1.829,365.377,426437,229,8)
end

---------------------------------Garbage ---------------------------------------------------
function gar_dolg_blokpost_warning()	--entering duty territory, news_manager.script
	spawn_alife_rand("killer_master",13.389,0.399,151.491,186643,357,1)
	spawn_alife_rand("killer_regular",19.532,0.310,148.898,192610,357,1)
	spawn_alife_rand("killer_regular",52.169,0.599,171.018,225365,358,1)
	spawn_alife_rand("killer_veteran",77.902,-0.353,181.149,247370,363,1)
	spawn_alife_rand("killer_veteran",95.748,7.534,180.608,262841,363,1)
end

function broken_pda_mobs()				--in garbage after returning from cordon with broken pda
	spawn_alife_rand("dog_strong",37.773,0.412,-287.243,211389,262,8)
	spawn_alife("bloodsucker_strong",37.222,1.842,-292.221,216694,253,1)
	spawn_alife("killer_regular",-10.319,-0.927,-178.361,168593,287,1)
	spawn_alife_rand("dog_strong",93.498,-2.973,-258.185,260603,263,8)
	if TB3D_Services.is_night() then
		spawn_alife("werewolf",69.510,1.919,-36.638,239874,394,1)
		spawn_alife("werewolf",19.905,0.818,-101.172,192275,290,1)
		spawn_alife("werewolf",92.353,0.087,-120.527,259548,397,1)
		spawn_alife("werewolf",62.764,0.817,78.695,234710,371,1)
		wolf_howls(true)
	else
		spawn_alife("chimera_x_ray",69.510,1.919,-36.638,239874,394,1)
		spawn_alife("chimera_x_ray",19.905,0.818,-101.172,192275,290,1)
		spawn_alife("chimera_x_ray",92.353,0.087,-120.527,259548,397,1)
		spawn_alife("chimera_x_ray",62.764,0.817,78.695,234710,371,1)
	end
end

--------------------------------Agroprom ---------------------------------------------------
function agro_krot_sos1()	--first enter agro
end

function agro_krot_sos2()	--help mole
end

function spawn_sak_trader()
	local obj = alife():story_object(9506)
	if not obj then
		obj = alife():create("sak_military_stalker",vector():set(21.711,-2.134,-222.385),261021,436) 
		local tbl = amk.read_stalker_params(obj)
		tbl.sid = 9506
		amk.write_stalker_params(tbl, obj)
		--TB3D_Services.info_alert("tb3d triggers: sak_military_stalker spawn")
	end
end

-------------------------------Agro Underground --------------------------------------------
function agro_knockdown()	--Strelok's hideout entrance, never called as agro_knockdown.ltx modified
	--do nothing, being used for ZatLost teleport
end

function agr_cam_effect()	--doctor cam, never called as agro_knockdown.ltx modified
end

function agro_contuz()	--psi blackout sounds, never called as agro_knockdown.ltx modified
end

----------------------------------Bar-----------------------------------------------------
function spawn_burer_bar()	--' couple Burers at the bar, arh_disk_nayty_6 in arhara_dialog.script
	spawn_alife_rand("tushkano_normal",99.368,1.213,-122.928,45947,1173,8)
	spawn_alife_rand("tarakan_normal",158.990,4.012,-108.175,45947,1173,6)
	spawn_alife_rand("rat_normal",99.368,1.213,-122.928,45947,1173,6)
	spawn_alife_rand("rat_weak",158.990,4.012,-108.175,45947,1173,8)
end

function bloodsucker()	--3 bloodsuckers at bar, freeman desert eagle quest start, braad_test.script
	spawn_alife_rand("tarakan_normal",99.368,1.213,-122.928,45947,1173,8)				--roaches
	spawn_alife_rand("tarakan_normal",158.990,4.012,-108.175,45947,1173,6)
	spawn_alife_rand("rat_weak",99.368,1.213,-122.928,45947,1173,8)						--rats
	spawn_alife_rand("rat_normal",158.990,4.012,-108.175,45947,1173,6)
	spawn_alife_rand("tarakan_normal",97.246,-1.959,-161.316,45850,1281,6)				--roaches and rats at atp lc
	spawn_alife_rand("rat_normal",97.246,-1.959,-161.316,45850,1281,8)
	spawn_alife_rand("boar_strong",69.267,-6.325,-159.720,45850,1281,8)					--boars beyond atp lc
end

function broken_pda()				--in rostok
	spawn_alife_rand("tushkano_normal",350.597,11.740,-435.072,85922,1289,16)
	if TB3D_Services.is_night() then
		--spawn_alife("werewolf",377.697,24.649,-505.079,84356,1285,1)
		--spawn_alife("werewolf",330.617,23.706,-491.006,73703,1301,1)
		spawn_alife("werewolf",368.467,26.961,-309.708,47432,1281,1)--hill, left, truck
		spawn_alife("werewolf",355.832,12.796,-109.928,80145,1284,1)--hill, right, fence area
		wolf_howls(true)
	else
		--spawn_alife("chimera_x_ray",330.617,23.706,-491.006,73703,1301,1)--hill, left, end
		--spawn_alife("chimera_x_ray",377.697,24.649,-505.079,84356,1285,1)--hill, right, end
		spawn_alife("chimera_x_ray",368.467,26.961,-309.708,47432,1281,1)--hill, left, truck
		spawn_alife("chimera_x_ray",355.832,12.796,-109.928,80145,1284,1)--hill, right, fence area
	end
	--(368.902,25.552,-414.520),47432,1281)--hill, left, mid
	--(358.803,23.039,-422.457),47432,1281)--hill, left, tree
	--(352.297,8.555,-492.889),76317,1168)--in fenced area
	--(418.766,26.039,-373.474),84356,1285)--hill, right, mid
end
----------------------------------dv-----------------------------------------------------
function x18_dream(is_start)
	if is_start == true then TB3D_Services.give_info("dar_x18_dream") end					--terminates dream state and spawns mil
end

--function hogg_chimera()
	--spawn_alife("chimera_x_ray",191.856,5.002,-361.756,388538,938,2)
--end

function fanat_laptop_have()
	TB3D_Services.give_info("dark_btr2_spawn")
	spawn_alife("chimera_x_ray",170.777,0.150,-239.972,371429,976,1)
	spawn_alife("chimera_x_ray",181.418,0.125,-284.652,381719,972,1)
	spawn_alife("bloodsucker_strong",-3.341,-10.815,-0.926,2259,1143,1)
	spawn_alife("bloodsucker_strong",1.212,9.350,-4.252,2983,1109,1)
	spawn_alife("kontroller_yazva",1.006,4.190,-0.710,2897,1124,1)
	spawn_alife_rand("tb3dm_zombie_strong",1.006,4.190,-0.710,2897,1124,8)
end

function dark_btr1_sms()
end

----------------------------------Yantar-----------------------------------------------------
function yantar_dream(is_start)
	if is_start == true then TB3D_Services.give_info("yantar_find_ghost_task_start") end	--terminates dream state and opens gate
end

function yan_ghost_pda()
end

------------------------------------radar------------------------------------------------------
function rad_barman_spam()		--when entering through break in wall
	spawn_suit(1,32.356,-0.431,-50.813,19121,1993)	--attic of trader house
end

function rad_psi_hit()
end

function radar_dream(is_start)
	if is_start == true then
		--TB3D_Services.give_info("bun_patrol_start")
		--xr_effects.enable_ui()
	end
end

function bun_deactivate_radar_ltx()			--executes this instead of dream state timer
	--alife():create("nebo_heavy_outfit", vector():set(32.356,-0.431,-50.813),19121,1993)	--attic of trader house	
end

---------------------------------------pripyat-----------------------------
function aes_mapspot()
	--TB3D_Services.give_info("pri_undeground_respawn_start")
	TB3D_Services.give_info("pri_followers_leader_give_info")
	TB3D_Services.give_info("pri_show_zones")
	--TB3D_Services.give_info("pri_wave7_end")
	--if xr_gulag.getGulagPopulation(823) == 0 then
		--TB3D_Services.give_info("pri_followers_all_dead")
	--end
end

--------------------------------------marsh--------------------------------
--function spawn_marmor()
	--alife():create("nebo_heavy_outfit", vector():set(-279.112,15.244,22.397),7073,3351)	--abandoned tower	
--end

function npp_chaes_exit()
	alife():create("nano_outfit_addw_bastplus", vector():set(-47.442,1.568,252.281),115721,3399)	--below water tower	
	alife():create("medkit_elite", vector():set(-47.442,1.568,252.281),115721,3399)	
	spawn_item_rand("ammo_12x70_buck", -26.723,17.721,268.084,128980,3411,4)						--top of tower
	spawn_alife_rand("tb3dm_snork_jumper",-33.054,1.687,284.845,123510,3402,4)
	spawn_alife("tb3dm_wolf",-39.537,0.898,310.379,120214,3402,2)
	spawn_alife_rand("tb3dm_snork_jumper",-60.545,0.594,270.346,107834,3399,4)
	spawn_alife("tb3dm_wolf",-60.637,0.534,269.422,107425,3399,1)
	spawn_alife_rand("tb3dm_snork_jumper",-48.952,0.704,250.903,114938,3399,2)
	spawn_alife_rand("tb3dm_snork_jumper",-3.568,1.578,280.225,137286,3420,4)
	wolf_howls(true)
end

function spawn_quest_suits()
	local grp = math_random(100)
	if grp > 70 then
		spawn_suit(1,-182.412,3.324,-325.288,49717,3365)									--swamp trader loft
		spawn_suit(1,-172.895,5.015,418.147,55994,3361)										--swamp NW shack roof
	elseif grp > 30 then
		spawn_suit(1,607.257,6.464,419.050,520564,3578)										--swamp NE house attic
		spawn_suit(1,-172.895,5.015,418.147,55994,3361)										--swamp NW shack roof
	else
		spawn_suit(1,273.002,13.626,-161.033,317054,3531)									--swamp church tower
		spawn_suit(1,180.358,12.341,532.991,239674,3484)									--swamp train car agro exit
	end
end

---------------------------------red forest -------------------------------
function tunnel_rat()
	spawn_alife_rand("tarakan_normal",-196.338,3.399,15.292,1271,3240,3)				--chamber 2
	spawn_alife_rand("tarakan_normal",-146.506,0.780,30.413,7071,3240,3)				--chamber 3
	spawn_alife_rand("rat_normal",-141.767,4.940,14.674,7245,3240,6)					--tunnel opening
	spawn_alife_rand("rat_normal",-100.433,0.798,28.918,12285,3240,3)					--chamber 1
	spawn_alife_rand("rat_normal",-111.545,-5.984,-57.600,10390,3240,6)					--pit
	spawn_suit(6,-136.159,0.380,34.015,7478,3240)
	--intersect1: (-137.315,0.673,24.377),7432,3240)
	alife():create("wpn_sg552_fss_de", vector():set(-177.644,3.123,-25.667),3556,3240)	--behind gate
	news_manager.amk_send_tip_id("sms_tunnel_rat_2","sms_sid",10,30,"trader")
	news_manager.amk_send_tip_id("sms_tunnel_rat","sms_sid",10,30,"trader")
end

function tunnel_rat2()				--grabbed weapon, start sequence here
	if amk.load_variable("tb3d_ald_weapons", 0) == 2 then
		spawn_item_rand("ammo_5.56x45_ap", -100.370,0.769,29.004,12285,3240,8)				--tunnel beside chamber
		spawn_item_rand("ammo_5.56x45_ap", -166.593,1.601,19.635,4582,3240,8)				--dead end
		spawn_item_rand("ammo_12x70_buck", -166.593,1.601,19.635,4582,3240,12)				--dead end
		spawn_alife("werewolf",-146.183,0.672,32.542,7074,3240,1)							--dead end
		db.actor:set_actor_position(vector():set(-108.197,0.609,21.772))					--chamber, spawn following grab gun
		wolf_howls(false)
		amk.save_variable("tb3d_ald_weapons", 3)											--starts sequence in actor update
	end
end

function tunnel_rat3()
	spawn_alife("werewolf",-152.996,2.250,8.064,6207,3240,1)							--end of tracks behind cart
	spawn_alife("werewolf",-178.473,2.267,-20.508,3407,3240,1)							--locked gate
	wolf_howls(true)
end

function tunnel_rat4()
	spawn_alife("werewolf",-111.545,-5.984,-57.600,10390,3240,2)						--pit
	spawn_alife("werewolf",-185.679,2.377,-51.694,2744,3240,1)							--blocked tracks
	wolf_howls(true)
end

-------------------------------------------NPP1-----------------------------------------------------------
function spawn_aes_stampede()
	alife():create("tb3dm_gigant_strong", vector():set(39.666,-0.002,-285.541),386473,2400,expendable_object)	--stampede behind actor
	alife():create("tb3dm_gigant_strong", vector():set(39.417,-0.000,-296.101),386473,2400,expendable_object)
	alife():create("tb3dm_gigant_strong", vector():set(17.593,-0.002,-290.086),386473,2400,expendable_object)
	alife():create("tb3dm_gigant_strong", vector():set(20.350,-0.000,-302.154),386473,2400,expendable_object)
	alife():create("tb3dm_gigant_strong", vector():set(39.6,-0.002,-285.541),386473,2400,expendable_object)
	alife():create("tb3dm_gigant_strong", vector():set(39.4,-0.000,-296.101),386473,2400,expendable_object)
	alife():create("tb3dm_gigant_strong", vector():set(17.5,-0.002,-290.086),386473,2400,expendable_object)
	alife():create("tb3dm_gigant_strong", vector():set(20.3,-0.000,-302.154),386473,2400,expendable_object)
	alife():create("tb3dm_gigant_strong", vector():set(139.595,-7.922,-265.308),386473,2400,expendable_object)	--far south sump
	alife():create("tb3dm_gigant_strong", vector():set(159.587,-7.921,-221.581),386473,2400,expendable_object)	--corner by portal
end

function spawn_aes_stampede2()
	if TB3D_Services.level_on_save() == "k01_darkscape" then							--109983
		TB3D_Mobs.spawn_snorks(350.645,-0.001,-390.844,389488,2400,6)
	else
		TB3D_Mobs.spawn_snorks(369.062,0.150,-404.876,389488,2400,3)
		TB3D_Mobs.spawn_snorks(369.264,0.150,-391.710,389488,2400,3)
		TB3D_Mobs.spawn_snorks(369.603,0.147,-338.303,386839,2400,3)
	end
	TB3D_Mobs.spawn_snorks(369.978,0.150,-320.853,386473,2400,3)	--snorks on bridge over viaduct
	TB3D_Mobs.spawn_snorks(363.191,-0.101,-360.855,389488,2400,3)	--s. viduct on tracks
end

----------------------------------Sarcofag-----------------------------------------------------
function osoznanie_call(actor, npc)
	news_manager.amk_send_tip_id("sms_osoznanie_call","sms_incoming",10,20,"o_soznanie")
	local sound_obj_l   = xr_sound.get_safe_sound_object( [[affects\psy_blackout_l]] )
	local sound_obj_r   = xr_sound.get_safe_sound_object( [[affects\psy_blackout_r]] )
	sound_obj_l:play_no_feedback(db.actor, sound_object.s2d, 0, vector():set(-1, 0, 1), 1.0)
	sound_obj_r:play_no_feedback(db.actor, sound_object.s2d, 0, vector():set( 1, 0, 1), 1.0)
end

function sar2_scene_start()
end

function death_monolith_ghosts()
end

function spawn_sarc_pack(count)		--way back behind wish granter
	spawn_alife_rand("werewolf",79.442,71.975,-32.248,6403,2417,count)
	wolf_howls(true)
end

-----------------------------------------zaton----------------------------------------
function zaton_lost()			--109997
	alife():create("m_poltergeist_strong_flame",vector():set(-199.406,6.393,27.741),543661,3674,expendable_object)
	spawn_alife("m_poltergeist_strong_flame",-421.097,-6.691,154.488,230735,3666,2)	--chopper in swirls
	alife():create("kontroller_yazva",vector():set(-221.778,-6.183,165.204),500584,3670,expendable_object)	--viaduct
	alife():create("kontroller_yazva",vector():set(-423.613,36.258,-397.799),142983,3664,expendable_object)
	--alife():create("af_cristall_flower",vector():set(430.570,33.254,-318.276),1671859,3694)
	--alife():create("af_cristall_flower",vector():set(429.551,6.755,-282.545),1670653,3696,3694)
  	spawn_item_rand("ammo_5.56x45_ap", 405.235,33.366,-440.100,1632001,3694,4)	--old factory
  	spawn_item_rand("medkit_scientic", 405.235,33.366,-440.100,1632001,3694,4)	--large storage container
	--alife():create("af_cristall_flower",vector():set(288.217,29.474,-399.527),1457658,3690,3670)
  	spawn_item_rand("ammo_5.56x45_ap", 288.217,29.474,-399.527,1457658,3690,4)
  	spawn_item_rand("medkit_scientic", 288.217,29.474,-399.527,1457658,3690,4)
  	spawn_item_rand("sandwich", -221.778,-6.180,165.204,500584,3670,6)
  	spawn_item_rand("antirad", -221.778,-6.180,165.204,500584,3670,4)
	--alife():create("af_fireball",vector():set(-199.406,6.393,27.741),543661,3674)
	--alife():create("af_cristall_flower",vector():set(-171.915,7.542,103.861),596577,3670)
  	spawn_item_rand("ammo_5.56x45_ap", -221.778,-6.183,165.204,500584,3670,4)
  	spawn_item_rand("medkit_scientic", -221.778,-6.183,165.204,500584,3670,4)
	--alife():create("af_cristall_flower",vector():set(-421.097,-6.691,154.488),230735,3666)
	--alife():create("af_vyvert_green",vector():set(-455.100,-4.365,152.6498),106689,3660)
	--alife():create("af_cristall_flower",vector():set(-423.613,36.258,-397.799),142983,3664)	--lab entrance
  	spawn_item_rand("ammo_5.56x45_ap", -423.613,36.258,-397.799,142983,3664,4)
  	spawn_item_rand("ammo_12x70_buck", -423.613,36.258,-397.799,142983,3664,4)
  	alife():create("neytral_exo_antigas_outfit_blackwhiteplus", vector():set(-423.613,36.258,-397.799),142983,3664)
	alife():create("af_gold_fish",vector():set(-70.115,12.223,-168.374),802854,3679,expendable_object)	--twisted tree
	alife():create("af_cristall_flower",vector():set(-149.779,-23.300,-181.774),642848,3673)
  	spawn_item_rand("ammo_5.56x45_ap", -149.779,-23.300,-181.774,642848,3673,12)
  	spawn_item_rand("ammo_12x70_buck", -149.779,-23.300,-181.774,642848,3673,8)
  	--alife():create("af_water_flower1", vector():set(-149.779,-23.300,-181.774),642848,3673)
  	--alife():create("af_eye_voron", vector():set(-149.779,-23.300,-181.774),642848,3673)
  	spawn_item_rand("ammo_5.56x45_ap", 327.670,44.208,-401.420,1513907,3690,8)	--factory near bridge
  	--alife():create("wpn_fn2000_sniper", vector():set(327.670,44.208,-401.420),1513907,3690)
  	spawn_item_rand("ammo_5.56x45_ap", 322.413,42.826,-404.901,1507608,3690,8)
  	alife():create("fake_wpn_wakizashi", vector():set(322.413,42.826,-404.901),1507608,3690)
  	spawn_item_rand("ammo_12x70_buck", 308.473,33.723,-401.669,1488318,3690,8)
  	alife():create("wpn_kriss_super_v", vector():set(296.110,34.281,-392.063),1469740,3690)
  	spawn_item_rand("ammo_12x70_buck", -363.139,23.928,-181.069,233705,3662,4)	--on bench near twisted tree
  	spawn_item_rand("ammo_5.56x45_ap",7.111,-5.214,37.411,958190,3677,4)
  	spawn_item_rand("ammo_12x70_buck",7.111,-5.214,37.411,958190,3677,4)
  	spawn_item_rand("ammo_5.56x45_ap",7.111,-5.214,37.411,958190,3677,4)
  	spawn_item_rand("ammo_5.56x45_ap",55.248,-9.187,32.501,1050641,3677,4)
  	spawn_item_rand("ammo_12x70_buck",55.248,-9.187,32.501,1050641,3677,4)
  	spawn_item_rand("medkit_scientic",55.248,-9.187,32.501,1050641,3677,4)
  	spawn_item_rand("ammo_5.56x45_ap",105.488,1.360,179.663,1152919,3686,4)
  	spawn_item_rand("ammo_12x70_buck",105.488,1.360,179.663,1152919,3686,4)
  	--spawn_item_rand("ammo_flame",105.488,1.360,179.663,1152919,3686,4)
  	spawn_item_rand("ammo_5.56x45_ap", 152.482,-6.824,-139.548,1227074,3688,4)	--hunter's barge
  	spawn_item_rand("ammo_12x70_buck", 152.482,-6.824,-139.548,1227074,3688,4)
	alife():create("artifact_electro_crystal_thorn", vector():set(-416.169,-10.524,209.710),182015,3666)	--arts in swirls
	alife():create("af_cristall_flower", vector():set(-431.574,-9.825,183.083),183045,3666)
	alife():create("af_gold_fish", vector():set(-447.110,-9.220,161.355),184065,3666)
	alife():create("af_rusty_kristall", vector():set(-436.729,-8.900,156.869),184065,3666)
end

function start_black_doc_sms()
	local count = amk.load_variable("black_doc", 0)
	if count == 0 then
		TB3D_Services.give_info("spawn_prizrak_na_chaes1")
		arhara_dialog.dell_new_prizrak()
		amk.save_variable("black_doc", 1)
		amk.start_timer("black_doc_timer",10)
	elseif count == 1 then
		arhara_dialog.gg_black_doc_sms1()
		amk.save_variable("black_doc", 2)
		amk.start_timer("black_doc_timer",20)
	elseif count == 2 then
		arhara_dialog.gg_black_doc_sms2()
		amk.save_variable("black_doc", 3)
		amk.start_timer("black_doc_timer",20)
	elseif count == 3 then
		arhara_dialog.gg_black_doc_sms3()
		amk.save_variable("black_doc", 4)
		amk.start_timer("black_doc_timer",20)
	elseif count == 4 then
		arhara_dialog.gg_black_doc_sms4()
		amk.save_variable("black_doc", 5)
		amk.start_timer("black_doc_timer",25)
	elseif count == 5 then
		arhara_dialog.gg_black_doc_sms5()
		amk.save_variable("black_doc", 6)
		amk.start_timer("black_doc_timer",15)
	elseif count == 6 then
		arhara_dialog.gg_black_doc_sms6()
		amk.del_variable("black_doc")
	end
end

---spawn night creatures at midnight for certain levels, after wish granter
function creatures_of_the_night()	--only called once after midnight
	local ln = level.name()
	local is_pack = nil
	--TB3D_Services.info_alert("night creatures")
	if ln == "l01_escape" then
			spawn_alife_rand("werewolf",384.692,20.200,284.930,595047,251,2)	--tunnel at end of tracks
			is_pack = true
	elseif ln == "l02_garbage" then
			spawn_alife_rand("werewolf",155.752,7.682,29.582,311457,385,2)		--far east, end of pile
			is_pack = true
	elseif ln == "l03_agroprom" then
	elseif ln == "l03u_agr_underground" then
	elseif ln == "l04_darkvalley" then
			spawn_alife_rand("werewolf",-48.131,-2.958,-143.643,117685,879,2)		--pit with tractor
			spawn_alife_rand("werewolf",132.106,14.174,-404.274,329386,943,2)		--rocks above pond
			is_pack = true
	elseif ln == "l04u_labX18" then
	elseif ln == "l06_rostok" then
	elseif ln == "l05_bar" then
	elseif ln == "l08_yantar" then
	elseif ln == "l08u_brainlab" then
	elseif ln == "l07_military" then
	elseif ln == "l10_radar" then
	elseif ln == "l10u_bunker" then
	elseif ln == "l11_pripyat" then
	elseif ln == "l12_stancia" then
	elseif ln == "l12_stancia_2" then
	elseif ln == "l12u_sarcofag" then
	elseif ln == "l12u_control_monolith" then
	elseif ln == "atp_for_test22" then
	elseif ln == "peshera" then
	elseif ln == "av_peshera" then
	elseif ln == "puzir" then
			spawn_alife_rand("werewolf",-94.990,19.603,130.544,111887,2881,2)	--on northern rocks
			is_pack = true
	elseif ln == "aver" then
			spawn_alife_rand("werewolf",-102.563,23.455,73.455,693513,2894,2)	--center peak on rocks
			spawn_alife_rand("werewolf",369.703,45.638,120.780,1531112,2906,2)	--far E. peak on rocks
			is_pack = true
	elseif ln == "limansk" then
	elseif ln == "hospital" then
	elseif ln == "generators" then
	elseif ln == "warlab" then
	elseif ln == "red_forest" then
			spawn_alife_rand("werewolf",145.121,-0.190,-182.607,106526,3304,2)	--small cave
			is_pack = true 
	elseif ln == "lost_village" then
			spawn_alife_rand("werewolf",124.927,9.906,-19.391,48990,3336,2)		--east tunnel
			is_pack = true
	elseif ln == "marsh" then
			spawn_alife_rand("werewolf",-94.524,0.826,464.607,119948,3393,2)	--northern tracks
			is_pack = true
	elseif ln == "dead_city" then
	elseif ln == "zaton" then
			spawn_alife_rand("werewolf",-111.639,-6.296,-227.265,717557,3673,2)	--in cave under station
			is_pack = true
			spawn_alife_rand("werewolf",-10.250,1.678,250.123,923280,3677,2)	--in cave under burnt ranch
	elseif ln == "jupiter" then
	elseif ln == "pripyat" then	--east pripyat
			spawn_alife_rand("werewolf",234.454,0.547,22.189,452741,3768,2)		--near the hospital
			is_pack = true
	elseif ln == "jupiter_underground" then
	elseif ln == "labx8" then
	elseif ln == "cs_agroprom_underground" then
	elseif ln == "predbannik" then
			spawn_alife_rand("werewolf",-269.439,46.687,238.627,524489,4024,2)	--peak above cave
			is_pack = true
	elseif ln == "yantar_old" then
			spawn_alife_rand("werewolf",231.216,8.801,65.287,543778,4382,2)		--east woods
			spawn_alife_rand("werewolf",188.130,13.851,202.517,496024,4381,1)	--top of bunker
			is_pack = true
	elseif ln == "swamp_old" then
			spawn_alife_rand("werewolf",283.068,5.104,-278.998,1762433,4395,2)	--sw road gate
			spawn_alife_rand("werewolf",-188.400,-5.488,-156.304,743914,4387,2)	--sw corner below tower
			is_pack = true
	elseif ln == "hiding_road" then
			spawn_alife_rand("werewolf",-270.456,-0.077,107.009,67606,4409,2)	--west train tunnel
			is_pack = true
	elseif ln == "k01_darkscape" then
			spawn_alife_rand("werewolf",364.145,26.607,220.181,875143,4646,2)	--sw side of rail tunnel
			spawn_alife_rand("werewolf",442.302,29.191,385.688,944682,4649,2)	--ne side
			is_pack = true
	elseif ln == "dark_forest" then
	elseif ln == "level_f-1" then
	elseif ln == "promzone" then
			spawn_alife_rand("werewolf",-30.338,19.704,-475.190,138458,4817,1)	--south end
			spawn_alife_rand("werewolf",116.248,20.592,-357.635,419106,4973,2)	--behind south trash pile
			spawn_alife_rand("werewolf",-41.726,21.354,445.734,121518,4796,2)	--peak above pipes end
			is_pack = true
	elseif ln == "digger_stash" then
	elseif ln == "l01_krasivay" then
	elseif ln == "l02_dd" then
	elseif ln == "l03_rinok" then
	elseif ln == "l04_pogost" then
	elseif ln == "l05_vokzal" then
	elseif ln == "lab_x14" then
	elseif ln == "l01_poligon" then
	end
	if is_pack ~= nil then wolf_howls(is_pack) end
	return true	--sets TB3D_Services.spawned
end

function eprip_spawns(spawns)	--called when Shadows spawns in the swamp
	local spawned = false
	if spawns == 0 then
		--undergrounds in shop area with tools
		spawn_item_rand("ammo_5.56x45_ap",-132.733,-11.074,-224.099,66013,3752,2)
		spawn_item_rand("ammo_12x70_buck",-135.834,-11.177,-225.825,63897,3752,2)
		spawn_item_rand("ammo_5.56x45_ap",-115.729,-11.154,-229.668,78936,3752,2)
		alife():create("af_cristall_flower",vector():set(-108.143,-3.408,-238.140),85071,3752)
		spawn_item_rand("ammo_12x70_buck",-135.834,-11.177,-225.825,63897,3752,2)
		alife():create("af_fireball",vector():set(-120.424,0.488,-254.691),75244,3752)
		spawn_item_rand("ammo_12x70_buck",-31.836,8.036,-276.651,156332,3756,2)
		alife():create("af_cristall_flower",vector():set(-31.836,8.036,-276.651),156332,3756)
		alife():create("zone_cockroach",vector():set(-124.223,0.600,-264.911),71235,3752)	--in the toilet
		spawn_item_rand("ammo_11.43x23_hydro",-124.223,0.600,-264.911,71235,3752,2)			--in the toilet
		spawn_item_rand("ammo_5.56x45_ss190",-124.223,0.600,-264.911,71235,3752,4)			--in the toilet
		spawn_item_rand("grenade_f1",-124.223,0.600,-264.911,71235,3752,4)					--in the toilet
		alife():create("wpn_fw900k",vector():set(-103.962,-2.652,-233.178),87982,3752)		--on table under light
		------
		spawned = true
	else
		--TODO
	end
	return spawned
end

function dist_center_ambush()						--top of construction site
	spawn_alife_rand("ldk1_troop",-10.013,17.029,162.646,23978,5281,1)	--npc sw corner
	spawn_alife_rand("ldk1_troop",-32.594,17.027,172.092,10786,5281,1)	--npc se corner
	spawn_alife_rand("ldk1_troop",-41.417,17.029,148.853,6981,5281,1)	--npc ne corner
	spawn_alife_rand("ldk1_troop",-24.139,17.029,139.272,15227,5281,1)	--npc n edge
	spawn_alife_rand("ldk1_troop",-11.047,17.028,136.517,22828,5281,1)	--npc nw corner
	spawn_item_rand("glow_grenade_red",-38.397,17.910,148.480,7823,5281,1)	--on stack of vent ducts
	spawn_item_rand("glow_grenade_green",-38.397,17.910,148.480,7823,5281,1)
	spawn_item_rand("glow_grenade_blue",-38.397,17.910,148.480,7823,5281,1)
	spawn_item_rand("glow_grenade_yellow",-38.397,17.910,148.480,7823,5281,1)
end

function wolf_howls(is_pack)			--NEED MAKE SINGLE HOWL!!!!
	local snd_obj
	if is_pack then
		snd_obj = xr_sound.get_safe_sound_object( [[monsters\\werewolf\\howls_dist]] )
	else
		snd_obj = xr_sound.get_safe_sound_object( [[monsters\\werewolf\\howls_dist]] )
	end
	if snd_obj then
		--TB3D_Services.packet_alert("triggers: werewolf howl")
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 2.0)
	end
end

function spawn_alife(name, x, y, z, lv, gv, count)
	for i=1, count do
		alife():create(name, vector():set(x,y,z),lv,gv,expendable_object)
	end
end
function spawn_alife_rand(name, x, y, z, lv, gv, count)
	if count == 1 then
		alife():create(name, vector():set(x,y,z),lv,gv,expendable_object)	--65535 treated as non-important
	else
		local flevel = TB3D_Services.global_koef(TB3D_Services.get_level_up())		--109981, should increase as koef increases
		local min = math_floor(flevel)
		if min < 1 then min = 1 end
		local cnt = math_ceil(count*flevel)
		if cnt <= min then cnt = min+1 end
		cnt = math_random(min,cnt)
		if cnt > count then cnt = count end										--109982, limit spawns
		--TB3D_Services.packet_alert("tb3d_triggers: spawn alife random koef["..utils.to_str(flevel).."] count["..utils.to_str(cnt).."]")
		for i=1, cnt do
			alife():create(name, vector():set(x,y,z),lv,gv,expendable_object)	--65535 treated as non-important
		end
	end
end

function spawn_item(name, x, y, z, lv, gv, count)
	for i=1, count do
		alife():create(name, vector():set(x,y,z),lv,gv)
	end
end
function spawn_item_rand(name, x, y, z, lv, gv, count)
	if count == 1 then
		alife():create(name, vector():set(x,y,z),lv,gv)
	else
		local flevel = TB3D_Services.global_koef(TB3D_Services.get_level_up())		--109981, should decrease as koef increases
		local cnt = math_ceil(math_random(1,count) / flevel)
		if cnt < 1 then cnt = 1 end
		if cnt > count then cnt = count end										--109982, limit spawns
		--TB3D_Services.packet_alert("tb3d_triggers: spawn item random koef["..utils.to_str(flevel).."] count["..utils.to_str(cnt).."]")
		for i=1, cnt do
			alife():create(name, vector():set(x,y,z),lv,gv)
		end
	end
end

function on_net_destroy()
	--if TB3D_Services.remove_info("tb3d_torch_on") then					--shut it down
		--if particles_object(19990) then level.remove_pp_effector(19990) end		--NV off
	--end
end

--------------------------------- game endings -----------------------------------------------------
function monolith_over()													--after wish granter vid
	--TB3D_Services.give_info("tb3d_chaes_done")
	TB3D_Services.give_info("sar_monolith_go")
	--dmx_mod.create_level_changer_sarc_to_bar()			--109975 too soon
	--dmx_mod.create_level_changer_sarc_to_chaes()
	dmx_mod.spawn_upgrades()												--109974, skat15 upgrades
	TB3D_Services.teleportate("mon_over")									--agrounder
end

function join_osoznanie()													--110000, after osozni vids
	--TB3D_Services.give_info("tb3d_chaes_done")
	--change community reps, ecolg should not trust actor
	--relation_registry.set_community_goodwill ("military", db.actor:id(), 0)
	--relation_registry.set_community_goodwill ("freedom", db.actor:id(), 0)
	--relation_registry.set_community_goodwill ("dolg", db.actor:id(), 0)
	--relation_registry.set_community_goodwill ("stalker", db.actor:id(), 0)
	--relation_registry.set_community_goodwill ("bandit", db.actor:id(), 0)
	relation_registry.set_community_goodwill ("monolith", db.actor:id(), 400)
	relation_registry.set_community_goodwill ("ecolog", db.actor:id(), 0)
	local oldrep = db.actor:character_reputation()
	db.actor:change_character_reputation(-oldrep)	--zero out rep, controls runaways
	db.actor:change_character_reputation(900)
	db.actor.health = 2			--full health
	TB3D_Services.give_info("tb3d_joined_oc")
	--TB3D_Services.teleportate("joined")
	TB3D_Services.teleportate("refused")
end
function refuse_osoznanie()													--110000, after osozni vids
	--TB3D_Services.give_info("tb3d_chaes_done")
	--change community reps, ecolg should like actor
	--relation_registry.set_community_goodwill ("military", db.actor:id(), 0)
	--relation_registry.set_community_goodwill ("freedom", db.actor:id(), 0)
	--relation_registry.set_community_goodwill ("dolg", db.actor:id(), 0)
	--relation_registry.set_community_goodwill ("stalker", db.actor:id(), 0)
	--relation_registry.set_community_goodwill ("bandit", db.actor:id(), 0)
	relation_registry.set_community_goodwill ("monolith", db.actor:id(), -500)
	relation_registry.set_community_goodwill ("ecolog", db.actor:id(), 400)
	--sorry, health stay as is, what did you expect?
	TB3D_Services.teleportate("refused")
end

function chaes_tower_portal()												--aes final portal
	if TB3D_Services.give_info("tb3d_chaes_done") then
		game.start_tutorial("dolg_dream")
		TB3D_Services.give_info("bar_dolg_video_start")		--110000
	else
		dmx_mod.create_level_changer_marsh_yantar()
		TB3D_Services.teleportate("npp_chaes_exit")							--to marsh
	end
end

function set_freeplay()														--arhara_dialog.dell_dcity_norman() 109955
	if TB3D_Services.is_collector(100) == false then
		TB3D_Services.give_info("tb3d_game_end")
	end
	TB3D_Services.teleportate("finish")
end

function treasure_hunt_ending()
	if not has_alife_info("tb3d_ready_for_tunnel") then
		news_manager.amk_send_tip_id("sms_finish_goldbars","sms_unknown",20,20,"killer")
	elseif has_alife_info("tb3d_ready_for_tunnel") and not has_alife_info("tb3d_x14_done") then
		news_manager.amk_send_tip_id("sms_finish_secretlab","sms_unknown",20,20,"default")
	end
	if has_alife_info("tweed_zep1_start") and not has_alife_info("tweed_zep1_done") then
		news_manager.amk_send_tip_id("sms_finish_tweedbook","sms_tweed",20,20,"default")
	end
end
----------------------------------------------------------------------------------------------------

function look_for_object(object)
	--TB3D_Services.packet_alert("tb3d trig: look for object["..utils.to_str(object).."]")
	local obj
	for a=first_object,last_object,1 do
		obj = alife():object(a)
		if obj and obj.name and string_find(obj:name(), utils.to_str(object)) then
			--TB3D_Services.packet_alert("tb3d trig: found object["..utils.to_str(obj.id).."]")
			return obj
		end
	end
	return nil
end

function spawn_zone_teleports()
	if TB3D_Services.give_info("tb3d_zone_teleports") then
		local v = vector()
		local se_obj = look_for_object("zone_teleport_new")			--clearsky enter
		if not se_obj then
			alife():create("zone_teleport_new",v:set(-208.9479,0.86408543,-291.8642),37124,3362)
		end
		se_obj = look_for_object("zone_teleport_new_out")			--clearsky exit
		if not se_obj then
			alife():create("zone_teleport_new_out",v:set(34.4663,0.87717,-287.2317),156875,3436)
		end
		if TB3D_Services.is_collector(101) == false then			--not starting as collector
			se_obj = look_for_object("lim_zone_teleport1")
			if not se_obj then
				alife():create("lim_zone_teleport1",vector():set(40.821,11.0686,215.0173),48310,3020)
			end
			se_obj = look_for_object("lim_zone_teleport2")
			if not se_obj then
				alife():create("lim_zone_teleport2",vector():set(49.1074,2.948,300.0252),51380,3022)
			end
			se_obj = look_for_object("hos_zone_teleport1")
			if not se_obj then
				alife():create("hos_zone_teleport1",v:set(-86.273,25.844,674.829),3736,3044)
			end
			se_obj = look_for_object("hos_zone_teleport2")
			if not se_obj then
				alife():create("hos_zone_teleport2",v:set(-104.113,34.25,615.65),127,3028)
			end
			se_obj = look_for_object("hos_zone_teleport3")
			if not se_obj then
				alife():create("hos_zone_teleport3",v:set(-92.780,33.493,719.939),1801,3034)
			end
		end
		amk.del_variable("m_teleport_31")			--useless vars in saves
		amk.del_variable("m_teleport_32")
		amk.del_variable("m_teleport_33")
		amk.del_variable("m_teleport_34")
		amk.del_variable("m_teleport_exit")
		amk.del_variable("m_teleport_hospital")
	end
end

function remove_zone_teleports()
	local se_obj = look_for_object("lim_zone_teleport1")
	if se_obj then alife():release(se_obj, true) end
	se_obj = look_for_object("lim_zone_teleport2")
	if se_obj then alife():release(se_obj, true) end
	se_obj = look_for_object("hos_zone_teleport1")
	if se_obj then alife():release(se_obj, true) end
	se_obj = look_for_object("hos_zone_teleport2")
	if se_obj then alife():release(se_obj, true) end
	se_obj = look_for_object("hos_zone_teleport3")
	if se_obj then alife():release(se_obj, true) end
end

function spawn_bar_portals()			--109987
	alife():create("bar_gexit_tele", vector():set(351.671,11.766,-435.218),85666,1289)	--portal garbage exit to bar
	alife():create("zone_teleport", vector():set(351.671,11.766,-435.218),85666,1289)		--marker
	alife():create("bar_roof_tele", vector():set(157.160,11.053,80.468),41387,1211)		--portal arena roof to garbage exit
	alife():create("zone_teleport", vector():set(157.160,11.053,80.468),41387,1211)		--marker
	alife():create("bar_sroof_tele", vector():set(108.345,3.438,73.511),33034,1225)		--sleep place roof to whse exit
	alife():create("zone_teleport", vector():set(108.345,3.438,73.511),33034,1225)		--marker
	alife():create("bar_wexit_tele", vector():set(1.493,1.999,289.353),21537,1245)		--whse exit to sleep place roof
	alife():create("zone_teleport", vector():set(1.493,1.999,289.353),21537,1245)		--marker
end

-- Spawn places to sleep
--  place_of_sleep if bed exists
--  place_of_sleep_vid to spawn bed w/pillow
function spawn_sleep_places()
	TB3D_Services.packet_alert("tb3d triggers: spawn sleep places")
	alife():create("place_of_sleep",vector():set(-210.765,-22.881,-122.198),42632,59) -- Cordon in the basement of the village
	alife():create("place_of_sleep",vector():set(47.043,1.567,243.461),219251,359) -- Dump - on the outpost of Debt
	alife():create("place_of_sleep",vector():set(-135.309,1.424,-318.204),77666,3374) -- marsh - base CHN
	alife():create("place_of_sleep",vector():set(-183.689,2.193,537.252),110573,3393) -- marsh - cave
	alife():create("place_of_sleep_vid",vector():set(-410.158,0.771,69.751),162553,2889) -- NC - infirmary
	alife():create("place_of_sleep",vector():set(48.180,1.101,-59.024),235536,1083) -- AP - At the bandits
	alife():create("place_of_sleep",vector():set(-213.998,1.396,91.526),122710,3600) -- MG - House Perfume
	alife():create("place_of_sleep",vector():set(117.971,0.206,66.106),34340,1252) -- Bar - a room about Zahara
	alife():create("place_of_sleep_vid",vector():set(42.121,7.499,-17.377),279888,664) -- Agroprom - about Adrenaline
	alife():create("place_of_sleep",vector():set(-68.412,-6.368,-68.965),3552,717) -- Agro Underground
	alife():create("place_of_sleep",vector():set(138.037,-7.041,-71.337),575215,2830) -- ATP - in the center
	alife():create("place_of_sleep",vector():set(9.233,-7.186,20.183),316476,1582) -- AC - in barracks
	alife():create("place_of_sleep",vector():set(27.627,-10.949,-280.456),54978,1480) -- Yantar (Amber) - the bunker
	alife():create("place_of_sleep",vector():set(36.312,-3.370,-48.361),22448,1996) -- Radar - the home Syaka
	alife():create("place_of_sleep",vector():set(99.587,4.333,131.124),210226,2171) -- Pripyat - the flat arrow
	alife():create("place_of_sleep",vector():set(146.228,5.035,-172.466),375746,3765) -- East Pripyat - laundry
	alife():create("place_of_sleep",vector():set(-45.021,-0.778,-252.296),4671,2994) -- Limansk - the house on the corner
	alife():create("place_of_sleep_vid",vector():set(19.020,9.701,29.558),19080,3330) -- Old Village - The Staff
	alife():create("place_of_sleep",vector():set(-122.429,38.783,-523.148),194437,3089) -- Generators - Neutral Village
	alife():create("place_of_sleep",vector():set(12.903,0.268,-39.544),74533,3290) -- Red Forest - trailer near Woodman
	alife():create("place_of_sleep_vid",vector():set(-31.129,0.556,-129.076),162684,2882) -- Forgotten Forest - Cross in the camp
	alife():create("place_of_sleep_vid",vector():set(-172.368,-2.678,-72.607),1765,2863) -- Cave - in miners
	alife():create("place_of_sleep",vector():set(-259.608,61.695,199.170),77941,2939) -- Labrynth in unlocked room
	alife():create("place_of_sleep",vector():set(104.962,-0.887,185.068),1149482,3686) -- backwater - ship
	alife():create("place_of_sleep",vector():set(23.365,4.674,363.584),992729,3682) -- backwater - cave
	--alife():create("place_of_sleep",vector():set(155.726,-6.558,-138.531),1231927,3688) -- hunter's barge
	alife():create("place_of_sleep_vid",vector():set(-145.177,23.583,-428.528),652504,3678) -- factory behind gas station
	alife():create("place_of_sleep_vid",vector():set(-99.547,25.127,723.881),291,3035) -- Hosp - stairs
	alife():create("place_of_sleep",vector():set(-76.493,19.628,563.786),6740,3075) -- Hosp - stairs at exit
	alife():create("place_of_sleep",vector():set(-95.800,31.033,591.607),854,3038) -- hosp - doc's level
	alife():create("place_of_sleep",vector():set(-50.014,-0.540,201.961),636203,3717) -- Jup Station
	alife():create("place_of_sleep_vid",vector():set(-254.878,-3.897,88.693),8119,1382) -- Wild Territory - on boxes in tunnel
	alife():create("place_of_sleep_vid",vector():set(303.978,-39.390,-22.460),67636,1930) -- Radar - room with Warlab lc
	alife():create("place_of_sleep",vector():set(-7.731,24.020,243.981),702881,3725) -- jupiter - room in tower
	-----new levels-------------------------
	alife():create("place_of_sleep",vector():set(-257.365,20.140,258.838),543291,3938) 		-- waiting room - in cave
	alife():create("place_of_sleep",vector():set(-285.401,-1.344,343.176),289906,4678)		--dark_forest shed
	alife():create("place_of_sleep",vector():set(-42.290,10.440,-83.721),729659,4660)		--dark forest tent
	alife():create("place_of_sleep",vector():set(-315.727,2.989,74.119),465856,4399)		--dead marshes main base
	alife():create("place_of_sleep",vector():set(190.235,3.496,-41.043),1562777,4399)		--dead marshes clinic
	alife():create("place_of_sleep",vector():set(-54.999,30.265,-125.271),231786,4679)		--f1 old bar couch
	alife():create("place_of_sleep",vector():set(241.647,0.823,21.572),853563,4554)			--broken road house behind garage
	alife():create("place_of_sleep",vector():set(-10.910,1.655,-43.447),22644,5277)			--dist. center
	alife():create("place_of_sleep",vector():set(255.166,0.057,-182.168),674905,4633)		--darkscape house
	alife():create("place_of_sleep",vector():set(171.073,13.131,-91.392),484361,5025)		--techniques
	alife():create("place_of_sleep",vector():set(-90.449,4.926,-1.491),134,5312)			--market
	alife():create("place_of_sleep",vector():set(-2.859,-8.126,2.400),117,5355)				--hole
	alife():create("place_of_sleep",vector():set(-430.777,12.411,-142.672),282924,3908)		--waiting room hq top floor
	alife():create("place_of_sleep",vector():set(-40.353,-0.547,332.464),879755,3985)		--waiting room next to N. trader
	alife():create("place_of_sleep",vector():set(-57.676,7.322,-40.176),290606,3620)		--110000, dead city HQ
	--TB3D_Services.packet_alert("tb3d triggers: spawn sleep places done")
end

-------------------------tb3d_suits---------------------------------
--1 = agro tunnel - 109934
--2 = radar after deact - 109934
--3 = hotel room, decoder docs - 109934
--7 = locker in east prip - 109980
--10 = prip on lockers near zep doc 4 - 109950
function spawn_suit(type, x, y, z, lv, gv)
	local suit
	if type == 1 then
		suit = "merc_scientific_outfit"				--cube quest suit
	elseif type == 2 then
		suit = "hunter_novice_outfit"
	elseif type == 3 then
		suit = "military_outfit"					--scat9
	elseif type == 4 then
		suit = "dolg_outfit_good"
	elseif type == 5 then
		suit = "outfit_soldier_m1_defaultplus"
	elseif type == 6 then
		suit = "stalker_outfit_blackwhiteplus"
	elseif type == 7 then
		suit = "militaryspec_outfit_psy"			--scat10 + nv
	elseif type == 8 then
		suit = "military_outfit_bastplus"			--scat9 + nv
	elseif type == 9 then
		suit = "specops_outfit_kat_eyeplus"
	elseif type == 10 then
		suit = "monolit_exoskeleton"
	elseif type == 11 then
		suit = "neytral_exo_antigas_outfit_default"
	elseif type == 12 then
		suit = "nebo_scientific_outfit_good"
	elseif type == 13 then
		suit = "bandit_outfit_blue_plus"
	else
		suit = "novice_outfit"
	end
	alife():create(suit, vector():set(x,y,z),lv,gv)
end

function delayed_action(info_id)					--called from timers
	TB3D_Services.give_info(info_id)
end

local has_spawned = false
function actor_idle()							--109999 called from timers, levelup 1 and up
	local pos = db.actor:position()
	local is_idle = (db.actor:position():distance_to_sqr(db.actor_pos) <= TB3D_Modders.actor_idle_dist)		-- if still idle then see if need stimulation
	if has_spawned then
		--if is_idle == false then has_spawned = false end									-- reset it
		--tb3d_services.packet_alert("tb3d triggers: actor idle has already spawned!!!!")
	elseif is_idle then
		if TB3D_Services.blow() then
			--tb3d_services.packet_alert("tb3d triggers: actor idle blowout!!!!")
			--blowouts?
		else
			has_spawned = true
			--tb3d_services.packet_alert("tb3d triggers: actor idle!!!!")
			local ln = level.name()
			if ln == "l01_escape" then
				if has_alife_info("zep00_have") then
					TB3D_Mobs.spawn_bandits(113.044,-7.495,8.628,414741,118,6)		--carpark
				end
			elseif ln == "l02_garbage" then
				if has_alife_info("zep00_have") then
					spawn_gar_bandits()	--hangar and swamps
					TB3D_Mobs.spawn_dogs(192.357,-1.344,57.052,338382,384, math_random(6,12))				--big tree
				end
			elseif lname == "l05_bar" then
				--nothing
			elseif lname == "l06_rostok" then
				if has_alife_info("zep00_have") then
					TB3D_Mobs.spawn_ros_bandits()
				end
			elseif lname == "l04_darkvalley" then
				TB3D_Mobs.check_dv_spawns()
			elseif lname == "l03_agroprom" then
				spawn_agro_dogs()
			elseif lname == "l03u_agr_underground" then
				TB3D_Mobs.spawn_agrou_bandits()
			elseif lname == "l08_yantar" then
				TB3D_Mobs.check_yantar_spawns()
			elseif lname == "l12u_sarcofag" then
				sarc_spawns(1)
			elseif lname == "l12u_control_monolith" then
				--future
			elseif lname == "marsh" then
				TB3D_Mobs.check_swamp_spawns()
			elseif lname == "l10u_bunker" then
				bunker_spawns(1)
			elseif lname == "l10_radar" then
				if not has_alife_info("tb3d_harsh_environment") then
					TB3D_Mobs.check_radar_spawns()
				end
			elseif lname == "jupiter" then
				if not has_alife_info("collector_ready_for_jupiter") or has_alife_info("collector_done_with_jupiter") then
					TB3D_Mobs.check_jupiter_spawns()
				end
			elseif lname == "jupiter_underground" then
				if not has_alife_info("collector_ready_for_jupund") or has_alife_info("collector_done_with_jupund") then
					TB3D_Mobs.check_jupu_spawns(1)			
				end
			elseif lname == "zaton" then
				if not has_alife_info("collector_ready_for_zaton") or has_alife_info("collector_done_with_zaton") then
					zat_spawns(1)
				end
			elseif lname == "l11_pripyat" then
				TB3D_Mobs.check_pripyat_spawns()
			elseif lname == "pripyat" then
				if not has_alife_info("collector_ready_for_eastprip") or has_alife_info("collector_done_with_eastprip") then
					TB3D_Mobs.check_eprip_spawns()
				end
			elseif lname == "dead_city" then
				if not has_alife_info("collector_ready_for_dcity") or has_alife_info("collector_done_with_dcity") then
					TB3D_Mobs.check_dcity_spawns(1)
				end
			elseif lname == "l07_military" then
				if not has_alife_info("tb3d_harsh_environment") then
					TB3D_Mobs.check_mil_spawns(spawns)
					TB3D_Dialog.killers_in_camp()
				end
			elseif lname == "l12_stancia_2" then
				if not has_alife_info("tb3d_harsh_environment") then
					TB3D_Dialog.npp2_killers_npp1()
					TB3D_Mobs.check_npp2_spawns()
				end
			elseif lname == "l12_stancia" then
				if not has_alife_info("tb3d_harsh_environment") then
					npp_spawns(1)
					TB3D_Mobs.check_npp1_spawns()
				end
			elseif lname == "l01_poligon" then
				--TODO
			elseif lname == "k01_darkscape" then
				TB3D_Mobs.check_ds_spawns()
				ds_spawns(1)
			elseif lname == "l04_pogost" then
				if not has_alife_info("tb3d_harsh_environment") then
					TB3D_Mobs.check_cemetery_spawns()
				end
			elseif lname == "dark_forest" then
				TB3D_Mobs.check_wasted_spawns()
				spawn_df_killers()
			elseif lname == "l01_krasivay" then
				TB3D_Mobs.check_kras_spawns()
			elseif lname == "l02_dd" then
				--future use
			elseif lname == "hiding_road" then
				hr_spawns(1)
			elseif lname == "predbannik" then
				--TODO
			elseif lname == "level_f-1" then
				if not has_alife_info("tb3d_harsh_environment") then
					TB3D_Mobs.check_f1_spawns()
				end
			elseif lname == "generators" then
				if not has_alife_info("tb3d_harsh_environment") then
					TB3D_Mobs.spawn_gen_skelets()
					warlab_spawns(1)
					TB3D_Mobs.spawn_gen_north(1)
					TB3D_Mobs.check_gen_spawns(1)
				end
			elseif lname == "swamp_old" then
				TB3D_Mobs.spawn_deadm_mobs()																--dogs, dogs, dogs
			elseif lname == "aver" then
				if not has_alife_info("tb3d_harsh_environment") then
					TB3D_Mobs.spawn_recon_mobs()
				end
			elseif lname == "l03_rinok" then
				if not has_alife_info("tb3d_harsh_environment") then
					TB3D_Mobs.check_mkt_spawns()
				end
			elseif lname == "lost_village" then
				TB3D_Mobs.check_village_spawns()
			elseif lname == "limansk" then
				TB3D_Mobs.check_limansk_spawns()
			elseif lname == "warlab" then
				TB3D_Mobs.check_warlab_spawns(1)
			elseif lname == "red_forest" then
				if not has_alife_info("collector_ready_for_redf") or has_alife_info("collector_done_with_redf") then
					TB3D_Mobs.check_redf_spawns()
				end
			elseif lname == "cs_agroprom_underground" then
				if has_alife_info("tb3d_gb1_done") then
					TB3D_Mobs.check_tunnels_spawns(1)
				end
			elseif lname == "promzone" then	
				TB3D_Mobs.check_promzone_spawns(1, 1)
			elseif lname == "digger_stash" then	
				if has_alife_info("zep18_have") then TB3d_Mobs.check_diggers_spawns(1) end
			end
		end
		if not has_spawned then
			db.actor_pos = pos
			amk.start_timer("tb3d_delay_idle", TB3D_Modders.actor_idle_delay)
		end
	end
end

function check_bar_drop(barnum)
	local seq = amk.load_variable("tb3d_bar_seq", 0)
	if seq == 0 then
		if barnum == 2 then dropped = true end
	elseif seq == 1 then
		if barnum == 3 then dropped = true end
	elseif seq == 2 then
		if barnum == 4 then dropped = true end
	elseif seq == 3 then
		if barnum == 5 then dropped = true end
	elseif seq == 4 then
		if barnum == 13 then dropped = true end
	elseif seq == 5 then
		if barnum == 12 then dropped = true end
	elseif seq == 6 then
		if barnum == 11 then dropped = true end
	elseif seq == 7 then
		if barnum == 10 then dropped = true end
	elseif seq == 8 then
		if barnum == 6 then dropped = true end
	elseif seq == 9 then
		if barnum == 7 then dropped = true end
	elseif seq == 10 then
		if barnum == 15 then
			create_tunnel_ports()
			tb3d_dyn_spawn.spawn_tunnels_markers()
			TB3D_Services.give_info("tb3d_gb1_done")
			dropped = true
		end
	end
	if dropped == true then
		local snd_obj = xr_sound.get_safe_sound_object([[ambient\earthquake]])
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		level.add_cam_effector("camera_effects\\earthquake.anm", 1974, false, "")
		amk.save_variable("tb3d_bar_seq", seq + 1)
		return true
	end
	return false
end

function create_tunnel_ports()
	local obj = alife():story_object(1999978)		--ws6 pump station lookout
	if not obj then
		dmx_mod.create_level_changer(1999978, vector():set(67.289,-19.291,-179.899),1190,3868, 	
			136294,3414, vector():set(-5.511,11.181,21.070), 							
			vector():set(0.0,0.0,-1.0), 												
			"marsh",1,1,"to_swamp") 													
	end
	obj = alife():story_object(1999979)				--wn5	f1 room in old compound
	if not obj then
		dmx_mod.create_level_changer(1999979, vector():set(76.439,-19.294,-165.031),1426,3868, 	
			216009,4679, vector():set(-69.871,30.352,-62.691), 							
			vector():set(0.0,0.0,-1.0), 												
			"level_f-1",1,1,"to_f1") 													
	end
	obj = alife():story_object(1999980)				--ws3	cordon box on train car
	if not obj then
		dmx_mod.create_level_changer(1999980, vector():set(102.585,-19.291,-166.463),2501,3868, 	
			274024,95, vector():set(-2.880,21.937,156.883), 							
			vector():set(0.0,0.0,-1.0), 												
			"l01_escape",1,1,"to_cordon") 													
	end
	obj = alife():story_object(1999981)				--wn2	broken road strange hut
	if not obj then
		dmx_mod.create_level_changer(1999981, vector():set(101.998,-19.294,-148.729),2626,3868, 	
			91881,4412, vector():set(-243.896,24.862,-201.748), 							
			vector():set(0.0,0.0,-1.0), 												
			"hiding_road",1,1,"to_broken") 													
	end
	obj = alife():story_object(1999982)				--w0	waiting room top of the hill
	if not obj then
		dmx_mod.create_level_changer(1999982, vector():set(112.343,-19.292,-131.400),3760,3868, 	
			539987,4024, vector():set(-260.011,46.838,243.201), 							
			vector():set(0.0,0.0,-1.0), 												
			"predbannik",1,1,"to_waiting") 													
	end
	obj = alife():story_object(1999983)				--e0	recon tree by the lake
	if not obj then
		dmx_mod.create_level_changer(1999983, vector():set(124.621,-19.291,-135.644),4148,3868, 	
			1002308,2902, vector():set(69.502,14.894,-71.124), 							
			vector():set(0.0,0.0,-1.0), 												
			"aver",1,1,"to_ff") 													
	end
	obj = alife():story_object(1999984)				--es2	npp2 between the globes
	if not obj then
		dmx_mod.create_level_changer(1999984, vector():set(128.237,-19.200,-110.850),4793,3868, 	
			189412,2619, vector():set(490.354,17.102,365.571), 							
			vector():set(0.0,0.0,-1.0), 												
			"l12_stancia_2",1,1,"to_npp2") 													
	end
	obj = alife():story_object(1999985)				--en3	generators center
	if not obj then
		dmx_mod.create_level_changer(1999985, vector():set(114.846,-19.291,-98.598),4245,3868, 	
			350468,3110, vector():set(12.485,38.105,-231.626), 							
			vector():set(0.0,0.0,-1.0), 												
			"generators",1,1,"to_generators") 													
	end
	obj = alife():story_object(1999986)				--es4	black market top of the stairs
	if not obj then
		dmx_mod.create_level_changer(1999986, vector():set(128.183,-19.293,-86.628),4638,3868, 	
			13655,5309, vector():set(23.628,4.225,0.825), 							
			vector():set(0.0,0.0,-1.0), 												
			"l03_rinok",1,1,"to_market") 													
	end
	obj = alife():story_object(1999987)				--es6	darkscape tunnel near station
	if not obj then
		dmx_mod.create_level_changer(1999987, vector():set(127.311,-19.291,-62.485),4673,3868, 	
			969226,4653, vector():set(493.525,-1.866,-424.212), 							
			vector():set(0.0,0.0,-1.0), 												
			"k01_darkscape",1,1,"to_darkscape") 													
	end
end

function spawn_df_killers()
	spawn_alife_rand("dav_ldk_veteran_respawn1",-370.220,8.902,-361.284,139403,4675,2)
	spawn_alife_rand("dav_ldk_master_respawn1",-338.456,15.736,-61.428,194849,4677,2)
	spawn_alife_rand("dav_ldk_veteran_respawn1",-334.423,9.107,250.325,202652,4678,3)
	spawn_alife_rand("dav_ldk_veteran_respawn1",-286.992,-1.760,341.979,287392,4678,3)
	spawn_alife_rand("dav_ldk_master_respawn1",-447.698,-1.152,149.022,8747,4677,2)
	spawn_alife_rand("dav_ldk_master_respawn1",-450.163,0.189,-364.263,4632,4675,2)
	spawn_alife_rand("dav_ldk_master_respawn1",-452.346,-0.001,-434.817,1149,4675,1)
end

function hr_spawns(idx)			--109978
	local is_save = false
	if idx == 0 then
		alife():create("vehicle_tb3d_btr", vector():set(-43.379,-3.021,1.548),393882,4467)			--in village
		alife():create("vehicle_tb3d_btr", vector():set(-76.988,3.001,338.276),342695,4458)			--in motorpool
		spawn_item_rand("grenade_rgd6",-75.015,-6.525,2.427,345520,4456,6)							--bottom of well
		is_save = true
	elseif idx == 1 then
		alife():create("grenade_rgd6", vector():set(-245.593,30.712,-201.925),89566,4412)		--stash1 - roof
		alife():create("grenade_rgd12", vector():set(-240.129,20.390,-201.870),95903,4416)		--stash1
		alife():create("grenade_rgd6", vector():set(-240.129,20.390,-201.870),95903,4416)		--stash1
		alife():create("grenade_rgd11", vector():set(-343.482,10.232,-167.246),21706,4404)		--stash2 - rocks
		alife():create("grenade_rgd7", vector():set(-343.482,10.232,-167.246),21706,4404)		--stash2
		alife():create("grenade_rgd8", vector():set(-343.482,10.232,-167.246),21706,4404)		--stash2
		alife():create("grenade_rgd9", vector():set(-343.482,10.232,-167.246),21706,4404)		--stash2
		alife():create("tb3dm_gigant_strong", vector():set(-275.012,11.994,-203.376),63256,4410,expendable_object)		--gigant1
		alife():create("tb3dm_gigant_strong", vector():set(-247.722,12.109,-172.212),87437,4412,expendable_object)		--gigant2
		--alife():create("tb3dm_gigant_strong", vector():set(-221.770,14.858,-223.422),119816,4416,expendable_object)	--gigant3
		is_save = true
	end
	if is_save then amk.save_variable("hr_spawns", idx+1) end
end

function warlab_spawns(level_up)			--109978
	if level_up == 1 then
		TB3D_Mobs.spawn_killer_squad(187.740,30.820,-493.186,553011,3139,6,1,false)			--around lab entrance
		TB3D_Mobs.spawn_killer_squad(158.189,30.681,-499.143,518915,3131,6,1,false)
		TB3D_Mobs.spawn_killer_squad(141.388,31.783,-444.763,499813,3127,6,1,false)
	else
		local cnt = math_random(3)
		TB3D_Mobs.spawn_killer_squad(187.740,30.820,-493.186,553011,3139,6,cnt,false)		--around lab entrance
		TB3D_Mobs.spawn_killer_squad(158.189,30.681,-499.143,518915,3131,6,cnt,false)
		TB3D_Mobs.spawn_killer_squad(141.388,31.783,-444.763,499813,3127,6,cnt,false)
	end
end

function npp_spawns(idx)			--109978
	local is_save = false
	if idx == 0 then
		alife():create("vehicle_tb3d_btr", vector():set(966.393,-0.037,-219.751),432458,2285)	--drivable tank at entrance
		alife():create("vehicle_tb3d_btr", vector():set(516.691,-0.101,-41.436),229322,2304)	--drivable tank near large pipes
		alife():create("vehicle_tb3d_sport", vector():set(873.004,-0.102,-361.184),389488,2400)	--buggy behind gate for fast travel
		alife():create("vehicle_tb3d_sport", vector():set(-177.544,0.108,-701.286),389488,2400)	--buggy near tracks for fast travel
		alife():create("vehicle_tb3d_atv", vector():set(370.780,-7.920,-274.760),386473,2400)	--atv under viaduct
		is_save = true		--109996
	end
	if is_save then amk.save_variable("npp1_spawns", idx+1) end
end

function eprip_spawns(idx)			--109978
	local is_save = false
	if idx == 0 then
		alife():create("ammo_9x39_izomorf", vector():set(-174.123,1.031,-199.342),39113,3748)			--in locker
		alife():create("grenade_rgd11", vector():set(-174.123,1.031,-199.342),39113,3748)
		alife():create("grenade_rgd7", vector():set(-174.123,1.031,-199.342),39113,3748)
		alife():create("grenade_rgd8", vector():set(-174.123,1.031,-199.342),39113,3748)
		alife():create("grenade_rgd9", vector():set(-174.123,1.031,-199.342),39113,3748)
		spawn_suit(7,-174.123,1.031,-199.342,39113,3748)									--scat10 plus nv
		is_save = true
	end
	if is_save then amk.save_variable("eprip_spawns", idx+1) end
end

function zat_spawns(idx)			--109978
	local is_save = false
	if idx == 0 then
		TB3D_Mobs.spawn_killer_squad(-333.718,9.476,397.311,284411,3665,6,6,false)						--npc in center of mill
		TB3D_Mobs.check_zaton_spawns1()
		TB3D_dialog.stack_money(-76.915,7.619,254.742,783122,3675,1,6)		--109976, in hot spot of fiery cave
		TB3D_dialog.stack_money(-76.821,7.623,255.320,783122,3675,2,9)
		TB3D_dialog.stack_money(-77.176,7.612,255.547,783122,3675,3,7)
		alife():create("vehicle_tb3d_btr_80", vector():set(252.653,27.686,-458.967),1397665,3685)		--drivable tank far north near factory
		is_save = true
	elseif idx == 1 then
		TB3D_Mobs.spawn_killer_squad(315.418,9.193,-77.785,1498606,3688,6,4,false)
		TB3D_Mobs.spawn_killer_squad(41.830,8.339,-239.381,1014781,3681,6,4,false)
		TB3D_Mobs.check_zaton_spawns2()
		spawn_suit(1,112.014,4.006,183.493,1158849,3686)								--suit type 1 on roof of ship cabin
		is_save = true
	elseif idx == 2 then
		TB3D_Mobs.spawn_killer_squad(162.406,4.821,-194.288,1243956,3688,6,4,false)
		TB3D_Mobs.spawn_killer_squad(170.868,10.786,-260.843,1258149,3683,6,4,false)
		TB3D_Mobs.check_zaton_spawns1()
		is_save = true
	elseif idx == 3 then
		TB3D_Mobs.spawn_killer_squad(315.418,9.193,-77.785,1498606,3688,6,4,false)
		TB3D_Mobs.spawn_killer_squad(41.830,8.339,-239.381,1014781,3681,6,4,false)
		TB3D_Mobs.check_zaton_spawns2()
		is_save = true
	elseif idx == 4 then
		TB3D_Mobs.spawn_killer_squad(162.406,4.821,-194.288,1243956,3688,6,4,false)
		TB3D_Mobs.spawn_killer_squad(170.868,10.786,-260.843,1258149,3683,6,4,false)
		TB3D_Mobs.check_zaton_spawns2()
		TB3D_Mobs.spawn_killer_squad(-333.718,9.476,397.311,284411,3665,6,6,false)				--npc in center of mill
		idx = 1																					--rotate through 2 and 4 for now
		is_save = true
	end
	if has_alife_info("tb3d_spawn_backwater_stash") then
		alife():create("tb3dm_controller_normal", vector():set(-110.759,4.996,-157.111),759130,3679,expendable_object)		--controller cave
	end
	if is_save then amk.save_variable("zat_spawns", idx+1) end
end

function bunker_spawns(idx)			--109978
	local is_save = false
	if idx == 0 then
		if TB3D_Services.give_info("tb3d_portals_x10") then							--quick way back out
			local se_obj = alife():create("m_teleport_tb3d2",vector():set(7.162,-23.572,15.393),7695,2773)	--lower door
			local t = amk.get_anomaly_data(se_obj) 
			t.sid = 1999902
			amk.set_anomaly_data(t, se_obj)
			se_obj = alife():create("m_teleport_tb3d3",vector():set(-59.914,-21.214,16.735),267,2723)		--midway
			t = amk.get_anomaly_data(se_obj) 
			t.sid = 1999903
			amk.set_anomaly_data(t, se_obj)
			se_obj = alife():create("m_teleport_tb3d4",vector():set(-21.673,-8.990,5.378),3159,2674)		--upper room
			t = amk.get_anomaly_data(se_obj) 
			t.sid = 1999904
			amk.set_anomaly_data(t, se_obj)
			is_save = true
		end
	end
	if is_save then amk.save_variable("bunker_spawns", idx+1) end
end

function sarc_spawns(idx)			--109978
	local is_save = false
	if idx == 0 then
		if has_alife_info("tb3d_gold_bar_15") then
			dmx_mod.create_level_changer_sarc_to_bar()
			dmx_mod.create_level_changer_sarc_to_chaes()
			is_save = true
		end
	elseif idx == 1 then
		--future use
	end
	if is_save then amk.save_variable("sarc_spawns", idx+1) end
end

function ds_spawns(idx)			--109978
	local is_save = false
	if idx == 0 then
		if has_alife_info("zep24_have") then
			spawn_ds_portals()
			is_save = true
		end
	end
	if is_save then amk.save_variable("ds_spawns", idx+1) end
end

function spawn_ds_portals()			--109978, moved here
	alife():create("ds_nexit_tele", vector():set(-451.410,13.797,559.419),35192,4599)		--n exit portal to w tunnel return
	alife():create("zone_teleport", vector():set(-451.410,13.797,559.419),35192,4599)		--marker
	alife():create("ds_wtunnel_tele", vector():set(337.312,20.109,285.644),889710,4646)		--w tunnel portal to n exit return
	alife():create("zone_teleport", vector():set(337.312,20.109,285.644),889710,4646)		--marker
	alife():create("ds_etunnel_tele", vector():set(470.296,20.117,285.721),948720,4646)		--e tunnel portal to se tunnel return
	alife():create("zone_teleport", vector():set(470.296,20.117,285.721),948720,4646)		--marker
	alife():create("ds_setunnel_tele", vector():set(518.712,-1.468,-420.649),971751,4653)	--se tunnel portal to e tunnel return
	alife():create("zone_teleport", vector():set(518.712,-1.468,-420.649),971751,4653)		--marker
end

function spawn_jup_portals()			--109987
	alife():create("jup_trlrright_tele", vector():set(302.991,29.062,-139.740),1207252,3741)	--trailer right portal to tower by table
	alife():create("zone_teleport", vector():set(302.991,29.062,-139.740),1207252,3741)			--marker
	alife():create("jup_trlrleft_tele", vector():set(311.083,29.030,-141.033),1217531,3741)		--trailer left portal to radar complex under S
	alife():create("zone_teleport", vector():set(311.083,29.030,-141.033),1217531,3741)			--marker
	alife():create("jup_cmplx_tele", vector():set(-414.609,2.641,16.106),25032,3708)			--radar complex under N, portal to trailer
	alife():create("zone_teleport", vector():set(-414.609,2.641,16.106),25032,3708)				--marker
	alife():create("jup_tower_tele", vector():set(-14.675,23.074,253.074),692825,3725)			--tower at window
	alife():create("zone_teleport", vector():set(-14.675,23.074,253.074),692825,3725)			--marker
end

function spawn_zat_portals()			--109987
	alife():create("zat_bridge_tele", vector():set(429.719,40.359,-230.540),1670637,3694)	--bridge to ship
	alife():create("zone_teleport", vector():set(429.719,40.359,-230.540),1670637,3694)		--marker
	alife():create("zat_shipb_tele", vector():set(70.596,-0.347,36.479),1021131,3677)		--ship to bridge
	alife():create("zone_teleport", vector():set(70.596,-0.347,36.479),1021131,3677)		--marker
	alife():create("zat_shipr_tele", vector():set(76.357,-0.263,33.978),1021131,3677)		--ship to radar
	alife():create("zone_teleport", vector():set(76.357,-0.263,33.978),1021131,3677)		--marker
	alife():create("zat_radar_tele", vector():set(-412.857,12.192,-22.607),158823,3663)		--radar to ship
	alife():create("zone_teleport", vector():set(-412.857,12.192,-22.607),158823,3663)		--marker
end

function spawn_npp1_portals()
	alife():create("npp1_train_tele", vector():set(1063.704,1.518,-28.231),473438,2280)		--train car portal
	alife():create("zone_teleport", vector():set(1063.704,1.518,-28.231),473438,2280)		--marker
	alife():create("npp1_sarc_tele", vector():set(387.701,0.215,62.286),168994,2385)		--sarc entrance
	alife():create("zone_teleport", vector():set(387.701,0.215,62.286),168994,2385)			--marker
	alife():create("npp1_tower_tele", vector():set(1095.0,0.758,-390.0),408027,2401)		--inside tower
	alife():create("zone_teleport", vector():set(1094.891,0.758,-380.806),408027,2401)		--marker
	alife():create("npp1_tank_tele", vector():set(393.454,-0.002,-209.491),171475,2347)		--between tanks near gen exit
	alife():create("zone_teleport", vector():set(393.454,-0.002,-209.491),171475,2347)		--marker
	alife():create("npp1_sign_tele", vector():set(929.176,-0.000,-197.663),409630,2285)		--behind sign
	alife():create("zone_teleport", vector():set(929.176,-0.000,-197.663),409630,2285)		--marker
end

function signal_green(x,y,z,lv,gv)			--109978, moved here
	if TB3D_Services.is_night() then
		alife():create("glow_stick_green",vector():set(x,y+1,z),lv,gv)
	end
	alife():create("zone_green_smoke_signal_tb3d", vector():set(x,y,z),lv,gv)
end

function spawn_enemy_at(npc)							--109981, used to motivate non-mob traders on supply change
	if npc then
		local pos = npc:position()
		spawn_alife_rand("tushkano_normal",pos.x,pos.y,pos.z+2,npc:level_vertex_id(),npc:game_vertex_id(),1)
	end
end

function spawn_x14_guard()
	local sname = amk.load_variable("level_on_save","start")
	if sname == "pripyat" then
		amk_mod.spawn_military_tech_pack( alife():create("vehicle_btr",vector():set(24.278,0.148,44.296),28106,3806) ,"vehicle_btr","jupu")		--large room
		amk_mod.spawn_military_tech_pack( alife():create("vehicle_btr",vector():set(9.147,8.047,308.679),19257,3789) ,"vehicle_btr","jupu")		--second tank behind door
	else			--110004, came from elevator
		amk_mod.spawn_military_tech_pack( alife():create("vehicle_btr",vector():set(-8.654,0.000,29.461),8108,3779) ,"vehicle_btr","jupu")		--large room
		amk_mod.spawn_military_tech_pack( alife():create("vehicle_btr",vector():set(10.078,8.044,282.823),19671,3799) ,"vehicle_btr","jupu")	--second tank behind door
	end
	amk_mod.spawn_military_tech_pack( alife():create("vehicle_btr",vector():set(1.359,8.066,416.059),14537,3787) ,"vehicle_btr","jupu")			--110009, first tank from elevator
	amk_mod.spawn_military_tech_pack( alife():create("vehicle_btr",vector():set(9.901,8.055,234.552),19639,3798) ,"vehicle_btr","jupu")			--110009, third tank amoung trucks
	spawn_suit(6,64.986,4.131,-0.547,39059,3808)													--desk in booth
	alife():create("wpn_rg-6",vector():set(54.844,2.798,11.796),33426,3808)							--side room
	alife():create("ammo_vog-25",vector():set(54.844,2.798,11.796),33426,3808)
	alife():create("ammo_vog-25",vector():set(54.844,2.798,11.796),33426,3808)
	alife():create("ammo_vog-25",vector():set(54.844,2.798,11.796),33426,3808)
	alife():create("ammo_vog-25",vector():set(2.375,9.427,381.752),14489,3793)						--jeep near last tank
	alife():create("ammo_vog-25",vector():set(2.375,9.427,381.752),14489,3793)
	alife():create("ammo_vog-25",vector():set(2.375,9.427,381.752),14489,3793)
	alife():create("ammo_vog-25",vector():set(3.775,8.982,325.709),14902,3785)						--jeep halfway
	alife():create("ammo_vog-25",vector():set(3.775,8.982,325.709),14902,3785)
	alife():create("ammo_vog-25",vector():set(3.775,8.982,325.709),14902,3785)
	alife():create("ammo_vog-25",vector():set(52.941,18.506,252.425),33351,3798)					--behind pillar before tank
	alife():create("ammo_vog-25",vector():set(52.941,18.506,252.425),33351,3798)
	alife():create("ammo_vog-25",vector():set(52.941,18.506,252.425),33351,3798)
	alife():create("ammo_vog-25",vector():set(15.797,9.570,203.948),23746,3798)						--open container before tank
	alife():create("ammo_vog-25",vector():set(15.797,9.570,203.948),23746,3798)
	alife():create("ammo_vog-25",vector():set(15.797,9.570,203.948),23746,3798)
end

function treasure_hunt_spawn(stash_num, rnd)												--109982, spawn alife in empty areas
	local qty = 1
	local rand = amk.load_variable("hunt_last_rnd", 1)
	amk.save_variable("hunt_last_rnd", rnd)
	--TB3D_Services.packet_alert("tb3d triggers: treasure hunt spawn["..utils.to_str(stash_num).."] rand["..utils.to_str(rand).."]")
	if stash_num == 1 then			--109999, cordon, house/start
		TB3D_Mobs.spawn_bandits(113.044,-7.495,8.628,414741,118,qty)					--carpark
		TB3D_Mobs.spawn_bandits(216.924,12.865,66.787,509099,154,qty)					--tree on hill
		TB3D_Mobs.spawn_bandits(309.609,2.860,119.955,569821,143,qty)					--north campfire
	elseif stash_num < 4 then			--109999, cordon, on tunnel w/exit to dv
		qty = 2
		TB3D_Mobs.spawn_killer_squad(-58.486,-30.666,-362.659,218265,16,3,qty,true)		--fallen tree by mines
		TB3D_Mobs.spawn_bandits(-17.653,0.638,253.559,259851,184,qty)					--barn
		TB3D_Mobs.spawn_bandits(-20.830,2.474,90.465,256236,86,qty)						--factory
		TB3D_Mobs.spawn_bandits(-57.682,-0.837,202.535,220954,164,qty)					--viaduct
		qty = 3
		TB3D_Mobs.spawn_killer_squad(-118.567,-26.226,-474.365,135535,11,3,qty,true)	--gate to firing range
		TB3D_Mobs.spawn_bandits(131.663,-0.454,312.142,436179,236,qty)					--skygazer camp
		TB3D_Mobs.spawn_bandits(309.734,14.935,275.283,570028,246,qty)					--fallen tree by tracks
		TB3D_Mobs.spawn_bandits(256.294,3.111,301.735,535972,245,qty)					--tree with corpse
		TB3D_Mobs.spawn_bandits(183.217,1.817,360.398,484425,230,qty)					--tent
	elseif stash_num == 4 then		--garbage
		TB3D_dialog.spawn_gar_found()		--snorks and spetnaz
		qty = 3
		TB3D_Mobs.spawn_bandits(-198.757,0.419,-28.941,30412,306,qty)					--pipes
		qty = 4
		TB3D_Mobs.spawn_bandits(-60.105,-2.433,-215.753,136069,268,qty)					--graveyard camp
		TB3D_Mobs.spawn_bandits(-58.560,0.421,-11.850,136967,324,qty)					--hangar yard
	elseif stash_num == 5 then		--agro
		spawn_agro_dogs()
	elseif stash_num == 6 then		--garbage
		TB3D_dialog.spawn_gar_found()		--snorks and spetnaz
	elseif stash_num == 7 then		--dv
		TB3D_Mobs.check_dv_spawns()
	elseif stash_num == 8 then		--bar
		--none, 3 rand
	elseif stash_num == 9 then		--rostok
		qty = 3
		if rand == 1 then
			TB3D_Mobs.spawn_snorks(-240.717,-0.005,37.312,13510,1423,qty)
			TB3D_Mobs.spawn_snorks(-237.589,-0.000,71.116,15237,1376,qty)
			TB3D_Mobs.spawn_snorks(-207.689,-0.030,86.989,25108,1373,qty)
		--elseif rand == 2 then
		else
			TB3D_Mobs.spawn_killer_squad(-145.445,-0.015,144.576,39631,1313,6,qty,false)
			TB3D_Mobs.spawn_killer_squad(-32.389,-0.001,144.550,62406,1417,6,qty,false)
		end
		qty = 6
		spawn_alife_rand("dog_strong",-25.368,-1.347,-168.590,63723,1432,qty)				--wt on hill near yantar exit
	elseif stash_num == 10 then		--yantar
		if rand < 3 then
			qty = 4
		else
			qty = 6
		end
		spawn_alife_rand("tb3dm_zombie_strong",116.301,1.523,-70.573,102270,1441,qty)		--on the road back
		spawn_alife_rand("dog_strong",-25.368,-1.347,-168.590,63723,1432,qty)			--wt on hill near yantar exit
	elseif stash_num == 11 then		--rostok
		qty = 4
		if rand == 1 then
			TB3D_Mobs.spawn_killer_squad(-253.802,-0.002,102.696,8349,1378,6,qty,false)
			TB3D_Mobs.spawn_killer_squad(-246.876,-0.002,61.497,10778,1383,6,qty,false)
		elseif rand == 2 then
			TB3D_Mobs.spawn_killer_squad(-145.445,-0.015,144.576,39631,1313,6,qty,false)
			TB3D_Mobs.spawn_killer_squad(-32.389,-0.001,144.550,62406,1417,6,qty,false)
		else
			TB3D_Mobs.spawn_killer_squad(-160.540,0.098,185.461,35929,1329,6,qty,false)
			TB3D_Mobs.spawn_killer_squad(-251.983,0.799,172.561,9149,1342,6,qty,false)
		end
		if TB3D_Services.get_level_up() == 2 then TB3D_Services.give_info("tb3d_sms_storm_suit") end		--article about storm and geeks
		
	---------------------------------------------------------------------------------------------------------	
	--following are in storm area and may have to wait for storm to end or wear special suit from lanky
	elseif stash_num == 12 then		--warehouses
		local enemies
		if has_alife_info("tb3d_harsh_environment") then
			enemies = "tb3dm_zombie_babka_strong"
			spawn_alife_rand(enemies,-6.784,-6.146,78.494,300362,1580, rand)			--warehouses, entrance to base
			spawn_alife_rand(enemies,27.919,-8.876,-47.801,333061,1590, rand)			--warehouses, inside base
			spawn_alife_rand(enemies,80.613,-13.523,402.588,378152,1808, rand)			--warehouses, exit to radar
			spawn_alife_rand(enemies,-26.449,-13.582,335.959,281075,1803, rand)			--warehouses, chopper
			spawn_alife_rand(enemies,-269.732,-6.571,406.570,68860,1851, rand)			--warehouses, below rocks
			qty = 4
		else
			enemies = "tb3dm_killer_exo_unic"
			qty = 2
			spawn_alife_rand(enemies,-269.732,-6.571,406.570,68860,1851, rand)			--warehouses, below rocks
			spawn_alife_rand(enemies,-26.449,-13.582,335.959,281075,1803, rand)			--warehouses, chopper
		end
		spawn_alife_rand(enemies,615.869,-52.257,-301.292,221303,1882, qty)				--radar, camp 1
		spawn_alife_rand(enemies,583.710,-63.105,-179.654,207039,1886, qty)				--radar, camp 2 with tank
		spawn_alife_rand(enemies,590.816,-50.166,15.045,210249,1900, qty)				--radar, camp at turn
		spawn_alife_rand(enemies,376.672,-50.020,9.989,108274,1864, qty)				--radar, prip intersection
		spawn_alife_rand(enemies,195.515,-12.702,83.415,53913,1936, qty)				--radar, camp on upper road
	elseif stash_num == 13 then		--109999, radar
		local enemies
		if has_alife_info("tb3d_harsh_environment") then
			enemies = "tb3dm_zombie_babka_strong"
		else
			enemies = "tb3dm_zombie_strong"
			TB3D_Mobs.spawn_npcs(382.320,-33.843,145.775,112679,1926, 2, rand)						--109999, zombied npc below stash
		end
		gty = rand
		spawn_alife_rand(enemies,382.320,-33.843,145.775,112679,1926, qty)			--exit to pripyat
		spawn_alife_rand(enemies,208.683,3.740,-0.728,67298,1930, qty)				--all around power lines
		spawn_alife_rand(enemies,202.037,6.476,14.384,67298,1930, qty)
		spawn_alife_rand(enemies,175.939,10.920,-39.170,67298,1930, qty)
		spawn_alife_rand(enemies,150.206,11.950,-77.123,67298,1930, qty)
		spawn_alife_rand(enemies,204.447,5.769,-14.557,72763,2030, qty)
		spawn_alife_rand(enemies,133.932,6.594,-42.438,72759,2030, qty)
		spawn_alife_rand(enemies,127.306,1.572,-9.984,51093,1975, qty)
	elseif stash_num == 15 then		--npp
		if rand == 1 then
			--TODO
		elseif rand == 2 then
			--TODO
		else
			--TODO
		end
		dmx_mod.create_level_changer_npp1_to_radar()
	elseif stash_num == 16 then		--radar, monster tree
		--TODO, 1 rand
	elseif stash_num == 17 then		--radar, final stash for part 1
		qty = 6
		if has_alife_info("tb3d_harsh_environment") then
			spawn_alife_rand("tb3dm_zombie_strong",590.280,-51.316,-45.751,209879,1898, qty)		--below stash
			spawn_alife_rand("tb3dm_zombie_strong",590.987,-50.149,15.658,210250,1900, qty)			--camp at corner
			spawn_alife_rand("tb3dm_zombie_strong",652.157,-43.881,182.037,226763,1912, qty)		--exit to dv
		else
			TB3D_Mobs.spawn_npcs(590.280,-51.316,-45.751,209879,1898, 2, qty)						--zombied npc below stash
			TB3D_Mobs.spawn_npcs(590.987,-50.149,15.658,210250,1900, 2, qty)						--zombied camp at corner
			TB3D_Mobs.spawn_npcs(652.157,-43.881,182.037,226763,1912, 2, qty)						--zombied npc exit to dv
		end
	-----------------------------------------------------------------------------------------------------
	
	elseif stash_num == 14 then		--pripyat
		if rand == 1 then
			--TODO
		elseif rand == 2 then
			--TODO
		else
			--TODO
		end
	elseif stash_num == 18 then		--atp, nw tree, start of part 2
			--TODO
	elseif stash_num == 19 then		--atp, pipe in motorpool
		if rand == 1 then
			--TODO
		elseif rand == 2 then
			--TODO
		else
			--TODO
		end
	elseif stash_num == 20 then		--recon
		local enemies
		if has_alife_info("tb3d_harsh_environment") then
			enemies = "tb3dm_zombie_strong"
			qty = 10
		else
			enemies = "tb3dm_dog_habaruch"
			if rand == 1 then
				qty = 8
			elseif rand == 2 then
				qty = 10
			else
				qty = 6
			end
			spawn_alife_rand(enemies,328.834,-6.943,-19.136,1454049,2902, qty)		--center of crater
			spawn_alife_rand(enemies,383.709,13.251,-103.709,1557659,2907, qty)		--above rock
		end
	elseif stash_num == 21 then					--swamp
		if rand == 1 then
			--TODO
		elseif rand == 2 then					--water tower
			TB3D_Dialog.spawn_swmp1_found()
		else
			--TODO
		end
	end
end

-- on item take: amk_zapiska, 109999 this works
-- Critical: SMapLocation binded to non-existent object id=22462 stalker:x16_stalker_ghost
-- Critical: SMapLocation binded to non-existent object id=22521 stalker_zombied:x16_zombied_0018
-- Critical: SMapLocation binded to non-existent object id=22533 stalker_zombied:x16_zombied_0013
function remove_brainlab_alife()
	if not fix_done then
		local is_fixed
		local obj_level
		local level_name
		for a=first_object,last_object,1 do		--skip actor (0)
			is_fixed = false
			obj = alife():object(a)
			if obj then
				if game_graph():valid_vertex_id(obj.m_game_vertex_id) then
					obj_level = game_graph():vertex(obj.m_game_vertex_id):level_id()
					level_name = alife():level_name(obj_level)
					if level_name == "l08u_brainlab" then
						if obj.alive then is_fixed = true end
						--if string_find(obj:name(), "x16_stalker_ghost")
						--or string_find(obj:name(), "x16_zombied_0018")
						--or string_find(obj:name(), "x16_zombied_0013") then
							--is_fixed = true
						--end
					end
				else
					is_fixed = true		--always get rid of bad objects
				end
				if is_fixed then alife():release(obj, true) end
			end
		end
	end
end

function spawn_decoder_mob()
	spawn_alife_rand("burer_strong", -122.711,21.587,-31.473,126,1529,2)			--spawn upto 2 burers in upper brainlab
	spawn_alife_rand("burer_strong", -7.510,1.116,-12.251,4091,1536,2)				--spawn upto 2 burers in lower brainlab
end

function spawn_tunnel_zombied()
	spawn_alife_rand("tb3dm_zombied_eco", -259.461,-17.278,-42.781,12,1458,1)			--spawn upto 2 zombied in tunnel behind lab exit
	spawn_alife_rand("tb3dm_zombied_eco", -192.189,-19.088,-42.861,553,1499,2)			--spawn upto 2 zombied in tunnel near lab exit
	spawn_alife_rand("tb3dm_zombied_eco", -80.663,-19.088,-37.183,11300,1495,2)			--spawn upto 2 zombied in tunnel near flame
	spawn_alife_rand("tb3dm_zombied_eco", -55.936,-19.088,-97.945,19538,1456,2)			--spawn upto 2 zombied in tunnel intersection
	spawn_alife_rand("tb3dm_zombied_eco", -25.560,-18.439,-90.889,29501,1492,4)			--spawn upto 4 zombied in tunnel dead end
	spawn_alife_rand("tb3dm_zombied_eco", -87.830,-11.456,-218.146,9013,1485,2)			--spawn upto 2 zombied behind pipe wall
	spawn_alife_rand("tb3dm_zombied_eco", -55.929,-12.470,-249.126,19369,1454,4)		--spawn upto 4 zombied on island
	spawn_alife_rand("tb3dm_zombied_eco", -8.698,-11.880,-261.798,35697,1482,2)			--spawn upto 2 zombied by station wall
end

function check_coll_portals()												--109987
	local spawned = amk.load_variable("tb3d_coll_ports", 0)
	if spawned < 1 then							--109987
		spawn_jup_portals()
		spawn_bar_portals()
		spawn_zat_portals()
		spawned = 1
	end
	if spawned < 2 then							--109996
		spawn_npp1_portals()
		spawned = 2
	end
	amk.save_variable("tb3d_coll_ports", spawned)
end

function make_camp_friends()			--109991, make rookie camp your friends
	xr_gulag.setGulagRelation("esc_lager", game_object.friend, db.actor)
	xr_gulag.setGulagRelation("esc_shustryi", game_object.friend, db.actor)
	xr_gulag.setGulagRelation("esc_wolf", game_object.friend, db.actor)
end

function old_research_send()				--109993, from basements without ladders
	local spot = math_random(5)
	if spot == 1 then
		TB3D_Services.move_actor(225.906,9.046,-193.022)		--,535639,4379)		--toilet
	elseif spot == 2 then
		TB3D_Services.move_actor(242.455,5.762,-118.937)		--,555935,4380)		--celler
	elseif spot == 3 then
		TB3D_Services.move_actor(209.135,13.619,-59.065)		--,519562,4384)		--platform
	elseif spot == 4 then
		TB3D_Services.move_actor(196.056,8.467,-12.389)			--,504521,4378)		--trailor w/tree
	else
		TB3D_Services.move_actor(76.826,18.205,-39.850)			--,369589,4384)		--comm ctr roof
	end
end

function spawn_sewer_stuff()	--109995, start collector
	--TB3D_Services.packet_alert("spawned sewer stuff")
	alife():create("bioradar", vector():set(-117.921,-1.824,5.525),224007,3615)
	alife():create("wpn_fn2000_sniper", vector():set(-117.921,-1.824,5.525),224007,3615)
	alife():create("outfit_specnaz_m1", vector():set(-117.921,-1.824,5.525),224007,3615)
end

function spawn_gar2_bandits()					--109996, when talk to gar_hellcar_group_2
	TB3D_Mobs.spawn_bandits(-125.320,-2.600,-197.555,90553,269,12)	--veh graveyard
end

function spawn_gar_bandits()					--109996, entering garbage after storm starts
	TB3D_Mobs.spawn_bandits(-63.527,0.847,7.235,134373,330,6)		--hangar campfire
	TB3D_Mobs.spawn_bandits(-86.797,0.382,9.641,121247,328,6)		--hangar center
	TB3D_Mobs.spawn_bandits(77.985,0.139,-148.290,247047,397,10)	--next to swamps
end

function spawn_agro_dogs()
	TB3D_Mobs.spawn_dogs(80.551,0.034,-133.653,315623,427, 6)		--van on road to base
	TB3D_Mobs.spawn_dogs(-150.344,-0.390,-305.699,87193,447, 10)	--S campfire behind base
	TB3D_Mobs.spawn_dogs(-140.965,7.594,-101.493,98014,602, 8)		--N hill above base
	TB3D_Mobs.spawn_dogs(-114.171,10.455,27.215,126000,527, 8)		--hill above swamp
	TB3D_Mobs.spawn_dogs(-15.992,7.149,140.283,224351,515, 12)		--N powerlines
end

function spawn_jup_001()
	spawn_alife_rand("ldk4_master",412.0438,3.693,-74.9348,1366967,3744,1) -- outside area
	spawn_alife_rand("ldk1_troop",412.9438,3.693,-74.0348,1366967,3744,1) -- outside area
	spawn_alife_rand("ldk1_troop",412.438,3.693,-73.7348,1366967,3744,1) -- outside area
	spawn_alife_rand("dav_ldk_veteran_respawn1",413.438,3.693,-75.348,1366967,3744,1) -- outside area
	spawn_alife_rand("dav_ldk_master_respawn1",419.645,9.955,-70.047,1379513,3744,3)  -- 3rd level room window
end

function spawn_jup_002()
	spawn_alife_rand("dav_ldk_master_respawn1",420.191,9.953,-79.437,1379488,3744,2)  -- 3rd level room
	spawn_alife_rand("dav_ldk_master_respawn1",423.690,4.454,-72.995,1384992,3744,2)  -- entrance 1st level room
	spawn_alife_rand("sim_nano_master",420.191,9.953,-79.437,1379488,3744,1)  -- 3rd level room
end

function spawn_jup_003()
	spawn_alife_rand("dav_ldk_master_respawn2",420.191,9.953,-79.437,1379488,3744,2)  -- 3rd level room
	spawn_alife_rand("ldk7_master",400.012,4.279,-129.0600,1345632,3744,1)  -- Main inside area
	spawn_alife_rand("dav_ldk_master_respawn1",402.012,4.279,-130.600,1345632,3744,1)  -- Main inside area
	spawn_alife_rand("sim_nano_master",399.012,4.279,-131.600,1345632,3744,1)  -- Main inside area
	spawn_alife_rand("ldk4_master",398.012,4.279,-129.600,1345632,3744,1)  -- Main inside area
	spawn_alife_rand("dav_ldk_veteran_respawn2",397.012,4.279,-127.600,1345632,3744,2)  -- Main inside area
	spawn_alife_rand("ldk1_troop",400.012,4.279,-129.600,1345632,3744,1)  -- Main inside area
	spawn_alife_rand("ldk9_master",403.012,4.279,-128.600,1345632,3744,1)  -- Main inside area
end

function spawn_jup_004()
	spawn_alife_rand("dav_ldk_master_respawn1",-324.238,4.231,394.971,167652,3703,1)
	spawn_alife_rand("ldk7_master",-368.178,3.567,404.037,93580,3703,1)
	spawn_alife_rand("sim_troop_master",-368.431,3.566,411.702,93592,3703,1)
	spawn_alife_rand("dav_ldk_veteran_respawn1",-340.702,3.612,415.413,138901,3703,2)
	spawn_alife_rand("ldk1_troop",-368.0431,3.566,411.0702,93592,3703,1)
	spawn_alife_rand("sim_troop_master",-340.0702,3.612,415.413,138901,3703,1)
end

function spawn_jup_005()
	spawn_alife_rand("ldk7_master",-422.055,-0.002,-350.327,15494,3702,1)
	spawn_alife_rand("dav_ldk_veteran_respawn2",-450.261,0.101,-380.495,372,3702,1)
	spawn_alife_rand("sim_troop_master",-407.745,-0.002,-368.701,33875,3702,1)
	spawn_alife_rand("dav_ldk_master_respawn1",-411.362,0.005,-357.825,28123,3702,1)
	spawn_alife_rand("ldk8_master",-419.725,-0.014,-333.137,17849,3702,1)
	spawn_alife_rand("sim_troop_master",-434.794,0.018,-349.348,5545,3702,1)
	spawn_alife_rand("dav_ldk_veteran_respawn1",-407.003,0.026,-378.496,34855,3702,1)
end

function spawn_jup_006()
	spawn_alife_rand("ldk1_master",20.119,24.615,-193.569,747268,3727,1)
	spawn_alife_rand("ldk2_master",55.023,27.961,-178.965,808998,3727,1)
	spawn_alife_rand("ldk1_troop",56.055,24.162,-180.240,810226,3727,1)
	spawn_alife_rand("ldk3_nano",21.092,24.368,-203.153,748458,3727,1)
	spawn_alife_rand("sim_troop_master",20.119,24.615,-193.569,747268,3727,1)
	spawn_alife_rand("dav_ldk_veteran_respawn2",55.023,27.961,-178.965,808998,3727,1)
	spawn_alife_rand("sim_troop_master",56.055,24.162,-180.240,810226,3727,1)
	spawn_alife_rand("dav_ldk_master_respawn1",21.092,24.368,-203.153,748458,3727,1)
end

function spawn_jup_007()
	spawn_alife_rand("ldk1_master",20.119,24.615,-193.569,747268,3727,1)
	spawn_alife_rand("ldk8_master",55.023,27.961,-178.965,808998,3727,1)
	spawn_alife_rand("ldk1_troop",56.055,24.162,-180.240,810226,3727,1)
	spawn_alife_rand("ldk4_nano",21.092,24.368,-203.153,748458,3727,1)
	spawn_alife_rand("sim_troop_master",20.119,24.615,-193.569,747268,3727,1)
	spawn_alife_rand("dav_ldk_master_respawn2",55.023,27.961,-178.965,808998,3727,1)
	spawn_alife_rand("sim_troop_master",56.055,24.162,-180.240,810226,3727,1)
	spawn_alife_rand("dav_ldk_master_respawn1",21.092,24.368,-203.153,748458,3727,1)
end

function spawn_jup_008()
	spawn_alife_rand("sim_troop_master",398.69,27.542,-382.278,1344104,3745,2)
	spawn_alife_rand("dav_ldk_veteran_respawn1",410.020,27.543,-366.803,1362984,3745,2)
	spawn_alife_rand("dav_ldk_master_respawn1",421.893,27.1,-369.037,1382563,3745,2)
	spawn_alife_rand("dav_ldk_master_respawn1",357.684,27.544,-375.026,1284547,3745,2)	-- Main area
	spawn_alife_rand("ldk8_master",312.166,21.928,-320.185,1219192,3745,1)				-- Main area
end

function spawn_jup_009()
	spawn_alife_rand("sim_troop_master",404.934,24.221,-381.337,1353675,3745,3)
	spawn_alife_rand("dav_ldk_veteran_respawn1",400.406,24.222,-364.394,1346588,3745,3)
	spawn_alife_rand("dav_ldk_master_respawn1",394.220,22.892,-368.966,1336811,3745,3)
	spawn_alife_rand("sim_troop_master",322.241,27.541,-358.657,1235490,3745,3)			-- Main area
	spawn_alife_rand("ldk5_master",313.166,21.928,-320.85,1219192,3745,1)					-- Main area
end

function spawn_jup_010()
	spawn_alife_rand("dav_ldk_veteran_respawn1",351.711,20.540,-305.920,1275706,3745,2)
	spawn_alife_rand("ldk1_troop",331.389,27.544,-300.995,1245489,3745,2)
	spawn_alife_rand("sim_nano_master",356.443,27.544,-342.409,1282612,3745,2)
	spawn_alife_rand("dav_ldk_veteran_respawn2",343.170,20.54,-304.34,1263284,3745,2)		-- Elevator level containers
	spawn_alife_rand("dav_ldk_master_respawn2",310.963,21.928,-326.663,1217363,3727,2)	-- Elevator level first ramp
end

function spawn_jupu_easy_001()
	-- news_manager.send_tip(db.actor, "LDK random spawn 1", nil, nil, 12000)
	spawn_alife_rand("dav_ldk_master_respawn1",64.9131,3.093,2.0625,39312,3808,3) -- main buiding gnd floor inner room 2
	spawn_alife_rand("dav_ldk_veteran_respawn2",13.0597,0.561,-53.0598,21811,3797,2) -- main hall small door to east Prip
	spawn_alife_rand("ldk1_nano",13.597,0.561,-53.598,21811,3797,2) -- main hall small door to east Prip
end

function spawn_jupu_easy_002()
	-- news_manager.send_tip(db.actor, "LDK random spawn 2", nil, nil, 12000)
	spawn_alife_rand("ldk1_nano",66.131,3.093,3.625,39312,3808,1) -- main buiding gnd floor inner room 2
	spawn_alife_rand("ldk3_nano",45.996,1.916,-0.061,34451,3808,1) -- main buiding gnd floor main room 
	spawn_alife_rand("ldk4_nano",14.597,0.561,-52.598,21811,3797,1) -- main hall small door to east Prip
	spawn_alife_rand("dav_ldk_master_respawn1",1.0881,8.064,406.0,14999,3787,2)    -- entrance first corner
	spawn_alife_rand("dav_ldk_master_respawn2",4.0671,8.066,236.85,16423,3796,2)  --    entrance first tunnel
	spawn_alife_rand("dav_ldk_veteran_respawn2",53.69,0.0,182.037,36477,3818,5)   --  entrance first stairs
	spawn_alife_rand("dav_ldk_master_respawn1",22.584,0.0,74.25,27484,3805,5)   --  2nd tunnel from entrance
end

function spawn_jupu_easy_003()
	-- news_manager.send_tip(db.actor, "LDK random spawn 3", nil, nil, 12000)
	spawn_alife_rand("ldk1_troop",37.569,4.492,-175.135,31823,3810,1) -- Tunnel to east Prip room inv box
	spawn_alife_rand("ldk1_troop",58.947,4.232,-150.617,38016,3821,3) -- Tunnel to east Prip
	spawn_alife_rand("ldk1_troop",52.789,4.703,-194.866,36774,3820,2) -- Tunnel to east Prip 2
	spawn_alife_rand("ldk1_troop",-50.551,3.210,1.134,729,3775,2) -- Main hall room behind containers
	spawn_alife_rand("dav_ldk_master_respawn1",-51.551,3.210,-1.134,729,3775,2) -- Main hall room behind containers
	spawn_alife_rand("dav_ldk_master_respawn2",46.996,1.916,-1.061,34451,3808,2) -- main buiding gnd floor main room
	spawn_alife_rand("ldk1_troop",47.996,1.916,-0.061,34451,3808,2) -- main buiding gnd floor main room
	spawn_alife_rand("dav_ldk_master_respawn1",65.131,3.093,3.625,39312,3808,2) -- main buiding gnd floor inner room 2
	spawn_alife_rand("dav_ldk_master_respawn2",14.597,0.561,-53.598,21811,3797,2) -- main hall small door to east Prip
	spawn_alife_rand("dav_ldk_master_respawn1",38.569,4.492,-173.135,31823,3810,2) -- Tunnel to east Prip room inv box
	spawn_alife_rand("dav_ldk_master_respawn2",56.947,4.232,-151.617,38016,3821,2) -- Tunnel to east Prip 
	spawn_alife_rand("dav_ldk_master_respawn1",52.789,4.703,-193.866,36774,3820,2) -- Tunnel to east Prip 2
end

function spawn_jupu_easy_004()
	-- news_manager.send_tip(db.actor, "LDK random spawn 4", nil, nil, 12000)
	spawn_alife_rand("ldk2_nano",37.569,4.492,-174.135,31823,3810,1) -- Tunnel to east Prip room inv box
	spawn_alife_rand("ldk1_troop",57.947,4.232,-150.617,38016,3821,2) -- Tunnel to east Prip
	spawn_alife_rand("ldk1_nano",53.789,4.703,-194.866,36774,3820,1) -- Tunnel to east Prip 2
	spawn_alife_rand("ldk4_nano",-50.551,3.210,0.134,729,3775,1) -- Main hall room behind containers	
	spawn_alife_rand("ldk1_troop",8.464,23.757,11.45,8933,3776,3)   -- main hall sniper 2 mid rail
	spawn_alife_rand("ldk1_troop",-51.551,3.210,-1.134,729,3775,2) -- Main hall room behind containers
	spawn_alife_rand("ldk2_nano",46.996,1.916,-1.061,34451,3808,1) -- main buiding gnd floor main room
	spawn_alife_rand("ldk1_troop",47.996,1.916,-0.061,34451,3808,2) -- main buiding gnd floor main room
	spawn_alife_rand("ldk1_nano",66.131,3.093,2.625,39312,3808,1) -- main buiding gnd floor inner room 2
	spawn_alife_rand("ldk4_nano",65.131,3.093,3.625,39312,3808,2) -- main buiding gnd floor inner room 2
	spawn_alife_rand("ldk3_nano",14.597,0.561,-53.598,21811,3797,2) -- main hall small door to east Prip
	spawn_alife_rand("ldk1_troop",13.597,0.561,-52.598,21811,3797,1) -- main hall small door to east Prip
	spawn_alife_rand("ldk1_troop",38.569,4.492,-173.135,31823,3810,2) -- Tunnel to east Prip room inv box
	spawn_alife_rand("ldk1_nano",56.947,4.232,-151.617,38016,3821,1) -- Tunnel to east Prip 
	spawn_alife_rand("ldk3_nano",52.789,4.703,-193.866,36774,3820,1) -- Tunnel to east Prip 2
end

function spawn_jupu_easy_005()
	-- news_manager.send_tip(db.actor, "LDK random spawn 5", nil, nil, 12000)
	spawn_alife_rand("dav_ldk_master_respawn1",38.569,4.492,-173.135,31823,3810,2) -- Tunnel to east Prip room inv box
	spawn_alife_rand("dav_ldk_master_respawn2",56.947,4.232,-151.617,38016,3821,2) -- Tunnel to east Prip 
	spawn_alife_rand("dav_ldk_veteran_respawn1",52.789,4.703,-193.866,36774,3820,1) -- Tunnel to east Prip 2
	spawn_alife_rand("dav_ldk_master_respawn1",-51.551,3.210,-1.134,729,3775,2) -- Main hall room behind containers
	spawn_alife_rand("dav_ldk_master_respawn2",66.131,3.093,2.625,39312,3808,1) -- main buiding gnd floor inner room 2
	spawn_alife_rand("dav_ldk_veteran_respawn2",46.996,1.916,-1.061,34451,3808,1) -- main buiding gnd floor main room
	spawn_alife_rand("dav_ldk_master_respawn1",14.597,0.561,-53.598,21811,3797,2) -- main hall small door to east Prip
	spawn_alife_rand("dav_ldk_master_respawn1",65.131,3.093,3.625,39312,3808,1) -- main buiding gnd floor inner room 2
	spawn_alife_rand("dav_ldk_master_respawn2",47.996,1.916,-0.061,34451,3808,2) -- main buiding gnd floor main room
	spawn_alife_rand("dav_ldk_master_respawn1",13.597,0.561,-52.598,21811,3797,3) -- main hall small door to east Prip
	spawn_alife_rand("ldk1_troop",1.881,8.064,406.0,14999,3787,1)    -- entrance first corner
	spawn_alife_rand("ldk1_troop",4.671,8.066,236.85,16423,3796,2)   -- entrance first tunnel
	spawn_alife_rand("ldk1_troop",52.69,0.0,182.037,36477,3818,1)   --  entrance first stairs
	spawn_alife_rand("ldk1_troop",22.584,0.0,73.25,27484,3805,2)   --  2nd tunnel from entrance
	spawn_alife_rand("dav_ldk_master_respawn1",0.0,26.6,-43.0,13286,3797,2)  -- main hall sniper 1 east
	spawn_alife_rand("dav_ldk_veteran_respawn2",0.35,26.47,-38.0,13585,3797,1)  -- main hall sniper 1 ledge east
	spawn_alife_rand("dav_ldk_master_respawn1",8.464,23.757,11.45,8933,3776,3)   -- main hall sniper 2 mid rail
	spawn_alife_rand("dav_ldk_master_respawn2",-51.551,3.210,-1.134,729,3775,2) -- Main hall room behind containers
	spawn_alife_rand("dav_ldk_master_respawn1",47.996,1.916,-0.061,34451,3808,2) -- main buiding gnd floor main room
	spawn_alife_rand("dav_ldk_veteran_respawn2",65.131,3.093,3.625,39312,3808,2) -- main buiding gnd floor inner room 2
	spawn_alife_rand("dav_ldk_master_respawn1",14.597,0.561,-53.598,21811,3797,3) -- main hall small door to east Prip
	spawn_alife_rand("ldk1_troop",38.569,4.492,-173.135,31823,3810,1) -- Tunnel to east Prip room inv box
	spawn_alife_rand("ldk1_troop",56.947,4.232,-151.617,38016,3821,2) -- Tunnel to east Prip 
	spawn_alife_rand("ldk1_troop",52.789,4.703,-193.866,36774,3820,3) -- Tunnel to east Prip 2
end

function spawn_jupu_easy_006()
	-- news_manager.send_tip(db.actor,"LDK random spawn 6", nil, nil, 12000)
	spawn_alife_rand("dav_ldk_master_respawn1",-52.551,3.210,-1.134,729,3775,2) -- Main hall room behind containers
	spawn_alife_rand("dav_ldk_veteran_respawn1",1.881,8.064,406.0,14999,3787,1)    -- entrance first corner
	spawn_alife_rand("dav_ldk_master_respawn1",4.671,8.066,236.85,16423,3796,2)   -- entrance first tunnel
	spawn_alife_rand("dav_ldk_veteran_respawn2",52.69,0.0,182.037,36477,3818,1)   --  entrance first stairs
	spawn_alife_rand("dav_ldk_master_respawn1",22.584,0.0,73.25,27484,3805,2)   --  2nd tunnel from entrance
	spawn_alife_rand("dav_ldk_master_respawn2",38.569,4.492,-173.9135,31823,3810,3) -- Tunnel to east Prip room inv box
	spawn_alife_rand("dav_ldk_master_respawn1",56.0947,4.232,-151.617,38016,3821,2) -- Tunnel to east Prip 
	spawn_alife_rand("dav_ldk_master_respawn1",52.789,4.703,-193.0866,36774,3820,2) -- Tunnel to east Prip 2
end

function spawn_jupu_tough_001()
	-- news_manager.send_tip(db.actor, "Tough LDK random spawn 1", nil, nil, 12000)
	spawn_alife_rand("ldk6_master",4.671,8.066,236.85,16423,3796,2)   -- entrance first tunnel
	spawn_alife_rand("ldk4_master",22.584,0.0,73.25,27484,3805,1)   --  2nd tunnel from entrance
	spawn_alife_rand("ldk5_master",0.35,26.47,-38.0,13585,3797,1)  -- main hall sniper 1 ledge (east,1)
	spawn_alife_rand("ldk9_master",-51.551,3.210,-1.134,729,3775,1) -- Main hall room behind containers
	spawn_alife_rand("ldk2_master",47.996,1.916,-0.061,34451,3808,1) -- main buiding gnd floor main room
	spawn_alife_rand("ldk4_master",65.131,3.093,3.625,39312,3808,1) -- main buiding gnd floor inner room 2
	spawn_alife_rand("ldk1_master",13.597,0.561,-52.598,21811,3797,2) -- main hall small door to east Prip
	spawn_alife_rand("ldk8_master",56.947,4.232,-151.617,38016,3821,1) -- Tunnel to east Prip 
end

function spawn_jupu_tough_002()
	-- news_manager.send_tip(db.actor, "Tough LDK random spawn 2", nil, nil, 12000)
	spawn_alife_rand("ldk5_master",1.881,8.064,406.0,14999,3787,2)    -- entrance first corner
	spawn_alife_rand("ldk7_master",52.69,0.0,182.037,36477,3818,1)   --  entrance first stairs
	spawn_alife_rand("ldk1_master",0.0,26.6,-43.0,13286,3797,1)  -- main hall sniper 1 (east,1)
	spawn_alife_rand("ldk3_master",8.464,23.757,11.45,8933,3776,1)   -- main hall sniper 2 mid rail
	spawn_alife_rand("ldk2_nano",46.996,1.916,-1.061,34451,3808,1) -- main buiding gnd floor main room
	spawn_alife_rand("ldk1_nano",66.131,3.093,2.625,39312,3808,1) -- main buiding gnd floor inner room 2
	spawn_alife_rand("ldk3_nano",14.597,0.561,-53.598,21811,3797,1) -- main hall small door to east Prip
	spawn_alife_rand("ldk2_master",38.569,4.492,-173.135,31823,3810,1) -- Tunnel to east Prip room inv box
	spawn_alife_rand("ldk4_master",52.789,4.703,-193.866,36774,3820,2) -- Tunnel to east Prip 2
end

function spawn_jupu_tough_003()
	-- news_manager.send_tip(db.actor, "Tough LDK random spawn 3", nil, nil, 12000)
	spawn_alife_rand("ldk9_master",4.671,8.066,236.85,16423,3796,1)   -- entrance first tunnel
	spawn_alife_rand("ldk1_master",52.69,0.0,182.037,36477,3818,3)   --  entrance first stairs
	spawn_alife_rand("ldk1_master",22.584,0.0,73.25,27484,3805,1)   --  2nd tunnel from entrance
	spawn_alife_rand("ldk5_master",8.464,23.757,11.45,8933,3776,1)   -- main hall sniper 2 mid rail
	spawn_alife_rand("ldk9_master",-51.551,3.210,-1.134,729,3775,1) -- Main hall room behind containers
	spawn_alife_rand("ldk2_nano",46.996,1.916,-1.061,34451,3808,3) -- main buiding gnd floor main room
	spawn_alife_rand("ldk1_troop",13.597,0.561,-52.598,21811,3797,1) -- main hall small door to east Prip
	spawn_alife_rand("ldk8_master",56.947,4.232,-151.617,38016,3821,1) -- Tunnel to east Prip 
end

function spawn_jupu_tough_004()
	-- news_manager.send_tip(db.actor, "Tough LDK random spawn 4", nil, nil, 12000)
	spawn_alife_rand("ldk1_master",0.0,26.6,-43.0,13286,3797,1)  -- main hall sniper 1 (east,1)
	spawn_alife_rand("ldk9_master",-51.551,3.210,-1.134,729,3775,1) -- Main hall room behind containers
	spawn_alife_rand("ldk3_master",47.996,1.916,-0.061,34451,3808,1) -- main buiding gnd floor main room
	spawn_alife_rand("ldk6_master",66.131,3.093,2.625,39312,3808,1) -- main buiding gnd floor inner room 2
	spawn_alife_rand("ldk2_master",14.597,0.561,-53.598,21811,3797,1) -- main hall small door to east Prip
end

function spawn_jupu_tough_005()
	-- news_manager.send_tip(db.actor, "Tough LDK random spawn 5", nil, nil, 12000)
	spawn_alife_rand("ldk2_master",-47.0,8.007,459.0,1244,3772,1)    -- lift entrance
	spawn_alife_rand("ldk6_master",1.881,8.064,406.0,14999,3787,2)    -- entrance first corner
	spawn_alife_rand("ldk4_master",4.671,8.066,236.85,16423,3796,1)   -- entrance first tunnel
	spawn_alife_rand("ldk7_master",52.69,0.0,182.037,36477,3818,1)   --  entrance first stairs
	spawn_alife_rand("ldk3_master",22.584,0.0,73.25,27484,3805,1)   --  2nd tunnel from entrance
	spawn_alife_rand("ldk1_master",38.569,4.492,-173.135,31823,3810,2) -- Tunnel to east Prip room inv box
	spawn_alife_rand("ldk8_master",56.947,4.232,-151.617,38016,3821,1) -- Tunnel to east Prip 
	spawn_alife_rand("ldk4_master",52.789,4.703,-193.866,36774,3820,1) -- Tunnel to east Prip 2
end

function spawn_jupu_tough_006()
	-- news_manager.send_tip(db.actor, "Tough LDK random spawn 6", nil, nil, 12000)
	spawn_alife_rand("ldk7_master",-47.0,8.007,459.0,1244,3772,1)    -- lift entrance
	spawn_alife_rand("ldk6_master",52.69,0.0,182.037,36477,3818,2)   --  entrance first stairs
	spawn_alife_rand("ldk8_master",22.584,0.0,73.25,27484,3805,1)   --  2nd tunnel from entrance
	spawn_alife_rand("ldk9_master",-51.551,3.210,-1.134,729,3775,1) -- Main hall room behind containers
	spawn_alife_rand("ldk2_master",46.996,1.916,-1.061,34451,3808,1) -- main buiding gnd floor main room
	spawn_alife_rand("ldk4_master",47.996,1.916,-0.061,34451,3808,2) -- main buiding gnd floor main room
	spawn_alife_rand("ldk4_master",14.597,0.561,-53.598,21811,3797,1) -- main hall small door to east Prip
	spawn_alife_rand("ldk9_master",38.569,4.492,-173.135,31823,3810,1) -- Tunnel to east Prip room inv box
end

function jup_spawn_random_enemy()
	local grp = math_random(10)
	if grp == 10 then
		spawn_jup_001()
		spawn_jup_010()
	elseif grp == 9 then
		spawn_jup_002()
		spawn_jup_009()
	elseif grp == 8 then
		spawn_jup_003()
		spawn_jup_008()
	elseif grp == 7 then
		spawn_jup_004()
		spawn_jup_007()
	elseif grp == 6 then
		spawn_jup_005()
		spawn_jup_009()
		spawn_jup_006()
	elseif grp == 5 then
		spawn_jup_001()
		spawn_jup_006()
	elseif grp == 4 then
		spawn_jup_002()
		spawn_jup_007()
		spawn_jup_009()
	elseif grp == 3 then
		spawn_jup_003()
		spawn_jup_002()
		spawn_jup_008()
	elseif grp == 2 then
		spawn_jup_004()
		spawn_jup_004()
		spawn_jup_009()
	elseif grp == 1 then
		spawn_jup_005()
		spawn_jup_003()
		spawn_jup_010()
	else
		spawn_jup_001()
		spawn_jup_005()
		spawn_jup_010()
	end
end

function jupu_spawn_random_enemy()
	local group = math_random(10)
	if group == 10 then
		spawn_jupu_easy_001()
		spawn_jupu_tough_001()
		spawn_jupu_easy_006()
	elseif group == 9 then
		spawn_jupu_easy_002()
		spawn_jupu_tough_002()
		spawn_jupu_easy_005()
	elseif group == 8 then
		spawn_jupu_easy_003()
		spawn_jupu_tough_003()
		spawn_jupu_easy_004()
	elseif group == 7 then
		spawn_jupu_easy_004()
		spawn_jupu_tough_004()
		spawn_jupu_easy_003()
	elseif group == 6 then
		spawn_jupu_easy_005()
		spawn_jupu_tough_005()
		spawn_jupu_easy_002()
	elseif group == 5 then
		spawn_jupu_easy_006()
		spawn_jupu_tough_006()
		spawn_jupu_easy_001()
	elseif group == 4 then
		spawn_jupu_easy_001()
		spawn_jupu_easy_004()
		spawn_jupu_tough_002()
		spawn_jupu_easy_006()
	elseif group == 3 then
		spawn_jupu_easy_002()
		spawn_jupu_tough_003()
		spawn_jupu_easy_004()
		spawn_jupu_easy_006()
	elseif group == 2 then
		spawn_jupu_easy_001()
		spawn_jupu_easy_003()
		spawn_jupu_tough_004()
		spawn_jupu_easy_005()
	elseif group == 1 then
		spawn_jupu_easy_001()
		spawn_jupu_easy_003()
		spawn_jupu_tough_005()
		spawn_jupu_easy_006()
	else
		spawn_jupu_easy_001()
		spawn_jupu_tough_001()
		spawn_jupu_tough_006()
		spawn_jupu_easy_006()
	end
end

function lim_remove_electros()			--110004, deactivates electric fence in Limansk
	local obj_level
	local obj
	local obj_name
	for a=first_object,last_object,1 do		--skip actor (0)
		obj = alife():object(a)
		if obj then
			if game_graph():valid_vertex_id(obj.m_game_vertex_id) then
				obj_level = game_graph():vertex(obj.m_game_vertex_id):level_id()
				if obj_level == 24 then
					if obj.name then obj_name = obj:name() else obj_name = "NIL" end
					if string_find(obj_name, "zone_emi_tb3d") then
						alife():release(obj, true)
					end
				end
			end
		end
	end
end

function collector_found_esc_stash()
	TB3D_Mobs.spawn_bandits(313.630,3.548,120.234,572044,143,8)					--wolf's group campfire
	TB3D_Mobs.spawn_bandits(210.544,2.129,319.883,504984,238,8)					--large rocks near house
end

function collector_found_rsrch_stash()											--110005, zombied npc around cellar
	TB3D_Mobs.spawn_npcs(27.467,8.859,-166.709,314832,4359,2,5)					--gate
	TB3D_Mobs.spawn_npcs(13.966,1.831,-130.210,300796,4355,2,5)					--under swamp hut
	TB3D_Mobs.spawn_npcs(168.657,7.922,-161.753,473260,4376,2,5)				--fenced in tanks
	TB3D_Mobs.spawn_npcs(130.260,3.723,-263.876,429292,4373,2,5)				--road near gen lc
end

function spawn_backwater_stash()												--110004, stash under gas station after talking to Arnie
	alife():create("killer_outfit_bastplus", vector():set(-129.106,-4.618,-229.811),683720,3673)	--dead end
	alife():create("grenade_gravi", vector():set(-95.991,-8.137,-198.424),748975,3673)				--special grenades
	alife():create("grenade_gravi", vector():set(-95.991,-8.137,-198.424),748975,3673)				--special grenades
	alife():create("grenade_gravi", vector():set(-95.991,-8.137,-198.424),748975,3673)				--special grenades
	alife():create("ammo_gravi", vector():set(-96.593,-7.355,-207.852),747521,3673)					--rare ammo
	alife():create("ammo_gravi", vector():set(-96.593,-7.355,-207.852),747521,3673)					--rare ammo
	alife():create("ammo_gravi", vector():set(-96.593,-7.355,-207.852),747521,3673)					--rare ammo
	alife():create("grenade_shok", vector():set(-113.589,-6.179,-229.927),713471,3673)				--special grenades
	alife():create("grenade_shok", vector():set(-113.589,-6.179,-229.927),713471,3673)				--special grenades
	alife():create("grenade_shok", vector():set(-113.589,-6.179,-229.927),713471,3673)				--special grenades
	alife():create("grenade_shok", vector():set(-148.045,-18.360,-188.849),645724,3673)				--car
	alife():create("grenade_shok", vector():set(-148.045,-18.360,-188.849),645724,3673)				--car
	alife():create("grenade_gravi", vector():set(-148.045,-18.360,-188.849),645724,3673)			--car
	alife():create("grenade_gravi", vector():set(-148.045,-18.360,-188.849),645724,3673)			--car
	alife():create("ammo_gravi", vector():set(-148.045,-18.360,-188.849),645724,3673)				--car
	alife():create("ammo_gravi", vector():set(-148.045,-18.360,-188.849),645724,3673)				--car
	alife():create("wpn_gravigun", vector():set(-148.045,-18.360,-188.849),645724,3673)				--car
	TB3D_dialog.stack_money(-92.466,7.943,-173.329,775003,3679,3,6)									--cave above arches
	TB3D_dialog.stack_money(-111.497,5.192,-159.420,759130,3679,3,10)										--controller cave
	alife():create("artifact_electro_crystal_thorn", vector():set(-416.169,-10.524,209.710),182015,3666)	--controller cave
	local obj = alife():create("zep_note_backwater1", vector():set(-149.289,16.738,-160.550),644289,3672)	--document for spot
	if obj then level.map_add_object_spot_ser(obj.id, "crlc_biggest", "back1_stash_hint") end
	amk.save_variable("back1_id", obj.id)
end