--TB3D 1.0.9.9.7.5 now saves volume, zone underground, active_station
function my_ver() return "1.0.9.9.7.5" end
-- initialization
-- Directed Vergas player
class "cheat" (CUIScriptWnd)

local play_menu = false			--player in the bag does not spawn
--local i

function cheat:__init(owner) super()
	self.owner = owner
	self:InitControls()
	self:InitCallBacks()
end

function cheat:__finalize() 
end

function cheat:InitControls()
	-- Here we determine the coordinates of the upper-left corner and width-height
	--self:Init(300,300,729,426)
	self:Init(284,270,740,740)
	self:SetAutoDelete(true)		--109975

	-- file descriptor of our elements
	local xml = CScriptXmlInit()
	xml:ParseFile("ui_cheat_player.xml")

	-- video in the background
	xml:InitStatic("back_video", self)

	-- frame
	xml:InitStatic("background", self)
	xml:InitStatic("background_2", self)
	xml:InitStatic("background_3", self)
	xml:InitStatic("background_4", self)
	xml:InitStatic("background_5", self)
	xml:InitStatic("background_5_2", self)
	xml:InitStatic("background_5_2_1", self)
	xml:InitStatic("background_5_2_2", self)
	xml:InitStatic("background_5_3", self)
	xml:InitStatic("background_5_3_1", self)
	xml:InitStatic("background_5_3_2", self)
	xml:InitStatic("background_6", self)
	xml:InitStatic("background_7", self)
	xml:InitStatic("background_8", self)
	
	-- frame files
	for i=1,3 do
		xml:InitStatic("background_r"..i, self)
	end
	
	-- radio (signature)
	for i=1,7 do
		xml:InitStatic("background_btn_"..i, self)
	end
	
	local slot = player_ogg.work_flash_return()
	if slot == nil or slot == 0 then										-- Working slot is empty
		xml:InitStatic("background_18", self)								-- Bone in the working slot
		--xml:InitStatic("background_10", self)  							-- Insert the USB flash drive, TB3D not used
		for i=1,12 do
			if i<10 then
				xml:InitStatic("background_btn_00"..i, self)				-- the "No File"
			else
				xml:InitStatic("background_btn_0"..i, self)
			end
		end
	else
		if slot < 7 then
			k = slot+11
			l = slot+18 
		elseif (slot > 6) and (slot<15) then
			k = slot+18
			l = slot+26
		elseif slot >14 then
			k = slot+26
			l = slot+28
		end
		xml:InitStatic("background_f"..slot.."_slot", self)				-- Icon flashes in the working slot
		xml:InitStatic("background_"..k, self)							-- Inscription stick in the slot working
		xml:InitStatic("background_"..l, self)							-- The bones of the stick in the slot
		for j=1,12 do
			xml:InitStatic("background_f"..slot.."_t"..j, self)			-- Names of tracks near the buttons Tracks
		end
	end
	
	-- button
	slot = player_ogg.get_work_trek()
	for i=1,12 do														--Button music files (always displayed)
		if i<10 then
			if slot and slot == i then
				xml:InitStatic("background_S0"..i, self)
			else
				xml:InitStatic("background_00"..i, self)
			end
			self:Register(xml:Init3tButton("btn_00"..i, self),"btn_00"..i)
		else
			if slot and slot == i then
				xml:InitStatic("background_S"..i, self)
			else
				xml:InitStatic("background_0"..i, self)
			end
			self:Register(xml:Init3tButton("btn_0"..i, self),"btn_0"..i)
		end
	end

	-- Radio buttons (always displayed)
	slot = player_ogg.get_station()
	for i =1,7 do
		if slot == i then
			xml:InitStatic("background_radio_5"..i, self)
		else
			xml:InitStatic("background_radio_"..i, self)
		end
		self:Register(xml:Init3tButton("btn_"..i, self),"btn_"..i)
	end

	-- Player control buttons are always displayed
	self:Register(xml:Init3tButton("btn_stop", self),"btn_stop")	-- Button Off
	self:Register(xml:Init3tButton("btn_quit", self),"btn_quit")	-- Exit button

	--Button Sticks
	for i=1, 16 do
		slot = player_ogg.return_flash_slot(i)
		if i <=14 then
			k = i+18
		else
			k = i+26
		end
		if slot == 1 then
			self:Register(xml:Init3tButton("btn_flash_"..i, self),"btn_flash_"..i) 	-- Definition button
			xml:InitStatic("background_f"..i, self)									-- Icon flashes in the slot stick
		else
			xml:InitStatic("background_"..k, self)									-- Icon bones stick in the slot
		end
	end
	
	--volume buttons
	local vol = player_ogg.get_vol()
	
	if vol ==1 then
		xml:InitStatic("background_vol_11", self)
	else
		xml:InitStatic("background_vol_1", self)
	end
	
	if vol ==2 then
		xml:InitStatic("background_vol_21", self)
	else
		xml:InitStatic("background_vol_2", self)
	end
	
	if vol ==3 then
		xml:InitStatic("background_vol_31", self)
	else
		xml:InitStatic("background_vol_3", self)
	end
	
	if vol ==4 then
		xml:InitStatic("background_vol_41", self)
	else
		xml:InitStatic("background_vol_4", self)
	end
	
	if vol ==5 then
		xml:InitStatic("background_vol_51", self)
	else
		xml:InitStatic("background_vol_5", self)
	end
	
	self:Register(xml:Init3tButton("btn_vol_1", self),"btn_vol_1")
	self:Register(xml:Init3tButton("btn_vol_2", self),"btn_vol_2")
	self:Register(xml:Init3tButton("btn_vol_3", self),"btn_vol_3")
	self:Register(xml:Init3tButton("btn_vol_4", self),"btn_vol_4")
	self:Register(xml:Init3tButton("btn_vol_5", self),"btn_vol_5")
	
	--Button repeat
	if player_ogg.ring_return() == 0 then
		xml:InitStatic("background_ring_off", self)
	else
		xml:InitStatic("background_ring_on", self)
	end
	self:Register(xml:Init3tButton("btn_ring", self),"btn_ring")
end

function cheat:InitCallBacks()
	-- then interactive elements with a certain action is performed a given f-Ia
	
	-- Radio buttons always work
	self:AddCallback("btn_1", ui_events.BUTTON_CLICKED, self.cheat1, self)
	self:AddCallback("btn_2", ui_events.BUTTON_CLICKED, self.cheat2, self)
	self:AddCallback("btn_3", ui_events.BUTTON_CLICKED, self.cheat3, self)
	self:AddCallback("btn_4", ui_events.BUTTON_CLICKED, self.cheat4, self)
	self:AddCallback("btn_5", ui_events.BUTTON_CLICKED, self.cheat5, self)
	self:AddCallback("btn_6", ui_events.BUTTON_CLICKED, self.cheat6, self)
	self:AddCallback("btn_7", ui_events.BUTTON_CLICKED, self.cheat7, self)
	
	-- Player control buttons always work
	self:AddCallback("btn_stop", ui_events.BUTTON_CLICKED, self.btn_stop, self)
	self:AddCallback("btn_quit", ui_events.BUTTON_CLICKED, self.btn_quit, self)
	
	-- Control buttons flash drive
	local slot = player_ogg.return_flash_slot(1)											-- Stick slot 1 (Sidorovicha)
	if slot == 1 then
		self:AddCallback("btn_flash_1", ui_events.BUTTON_CLICKED, self.flash1, self)
	end
	
	local slot = player_ogg.return_flash_slot(2)											-- Stick slot 2 (Bartender)
	if slot == 1 then
		self:AddCallback("btn_flash_2", ui_events.BUTTON_CLICKED, self.flash2, self)
	end
	
	local slot = player_ogg.return_flash_slot(3)											-- Stick slot 3 (Debt)
	if slot == 1 then
		self:AddCallback("btn_flash_3", ui_events.BUTTON_CLICKED, self.flash3, self)
	end
	
	local slot = player_ogg.return_flash_slot(4)											-- Slot stick 4 (Freedom)
	if slot == 1 then
		self:AddCallback("btn_flash_4", ui_events.BUTTON_CLICKED, self.flash4, self)
	end
	
	local slot = player_ogg.return_flash_slot(5)											-- Slot flash 5 (Bandit)
	if slot == 1 then
		self:AddCallback("btn_flash_5", ui_events.BUTTON_CLICKED, self.flash5, self)
	end
	
	local slot = player_ogg.return_flash_slot(6)											-- Stick slot 6 (Syaka)
	if slot == 1 then
		self:AddCallback("btn_flash_6", ui_events.BUTTON_CLICKED, self.flash6, self)
	end
	
	local slot = player_ogg.return_flash_slot(7)											-- Slot flash 7
	if slot == 1 then
		self:AddCallback("btn_flash_7", ui_events.BUTTON_CLICKED, self.flash7, self)
	end
	
	local slot = player_ogg.return_flash_slot(8)											-- Slot flash 8
	if slot == 1 then
		self:AddCallback("btn_flash_8", ui_events.BUTTON_CLICKED, self.flash8, self)
	end
	
	local slot = player_ogg.return_flash_slot(9)											-- Slot flash 9
	if slot == 1 then
		self:AddCallback("btn_flash_9", ui_events.BUTTON_CLICKED, self.flash9, self)
	end
	
	local slot = player_ogg.return_flash_slot(10)											-- Slot stick 10
	if slot == 1 then
		self:AddCallback("btn_flash_10", ui_events.BUTTON_CLICKED, self.flash10, self)
	end
	
	local slot = player_ogg.return_flash_slot(11)											-- Slot stick 11
	if slot == 1 then
		self:AddCallback("btn_flash_11", ui_events.BUTTON_CLICKED, self.flash11, self)
	end
	
	local slot = player_ogg.return_flash_slot(12)											-- Slot stick 12
	if slot == 1 then
		self:AddCallback("btn_flash_12", ui_events.BUTTON_CLICKED, self.flash12, self)
	end
	
	local slot = player_ogg.return_flash_slot(13)											-- Slot stick 13
	if slot == 1 then
		self:AddCallback("btn_flash_13", ui_events.BUTTON_CLICKED, self.flash13, self)
	end
	
	local slot = player_ogg.return_flash_slot(14)											-- Slot stick 14
	if slot == 1 then
		self:AddCallback("btn_flash_14", ui_events.BUTTON_CLICKED, self.flash14, self)
	end
	
	local slot = player_ogg.return_flash_slot(15)											-- Slot stick 15
	if slot == 1 then
		self:AddCallback("btn_flash_15", ui_events.BUTTON_CLICKED, self.flash15, self)
	end
	
	local slot = player_ogg.return_flash_slot(16)											-- Slot stick 16
	if slot == 1 then
		self:AddCallback("btn_flash_16", ui_events.BUTTON_CLICKED, self.flash16, self)
	end
	
	-- Start button files
	slot = player_ogg.return_flash_slot(0)
	
	if slot == nil then
		-- Working slot is empty
		for i=1,12 do
			if i<10 then
				self:AddCallback("btn_00"..i, ui_events.BUTTON_CLICKED, self.cheat01, self)		--File 1 - 9
			else
				self:AddCallback("btn_0"..i, ui_events.BUTTON_CLICKED, self.cheat01, self)		--File 10 - 12
			end
		end
	else
		self:AddCallback("btn_001", ui_events.BUTTON_CLICKED, self.cheat_t1, self)		--File 1
		self:AddCallback("btn_002", ui_events.BUTTON_CLICKED, self.cheat_t2, self)		--File 2
		self:AddCallback("btn_003", ui_events.BUTTON_CLICKED, self.cheat_t3, self)		--File 3
		self:AddCallback("btn_004", ui_events.BUTTON_CLICKED, self.cheat_t4, self)		--File 4
		self:AddCallback("btn_005", ui_events.BUTTON_CLICKED, self.cheat_t5, self)		--File 5
		self:AddCallback("btn_006", ui_events.BUTTON_CLICKED, self.cheat_t6, self)		--File 6
		self:AddCallback("btn_007", ui_events.BUTTON_CLICKED, self.cheat_t7, self)		--File 7
		self:AddCallback("btn_008", ui_events.BUTTON_CLICKED, self.cheat_t8, self)		--File 8
		self:AddCallback("btn_009", ui_events.BUTTON_CLICKED, self.cheat_t9, self)		--File 9
		self:AddCallback("btn_010", ui_events.BUTTON_CLICKED, self.cheat_t10, self)		--File 10
		self:AddCallback("btn_011", ui_events.BUTTON_CLICKED, self.cheat_t11, self)		--File 11
		self:AddCallback("btn_012", ui_events.BUTTON_CLICKED, self.cheat_t12, self)		--File 12
	end
	
	--volume buttons
	self:AddCallback("btn_vol_1", ui_events.BUTTON_CLICKED, self.cheat_vol_1, self)
	self:AddCallback("btn_vol_2", ui_events.BUTTON_CLICKED, self.cheat_vol_2, self)
	self:AddCallback("btn_vol_3", ui_events.BUTTON_CLICKED, self.cheat_vol_3, self)
	self:AddCallback("btn_vol_4", ui_events.BUTTON_CLICKED, self.cheat_vol_4, self)
	self:AddCallback("btn_vol_5", ui_events.BUTTON_CLICKED, self.cheat_vol_5, self)
	
	-- button zakoltsovki
	self:AddCallback("btn_ring", ui_events.BUTTON_CLICKED, self.cheat_ring, self)

end

function cheat:OnKeyboard(dik, keyboard_action)
	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		-- to hang out Esc
		if dik == DIK_keys.DIK_ESCAPE then
			player_ogg.set_play_flag(2)
			play_menu = true				-- The player spawns in a bag
			self:on_quit()
		end
	end
	return true
end

function cheat:flash1()						-- Selected as a USB flash drive (Sidorovicha)
		player_ogg.s_stop()
		player_ogg.set_show_flash(1)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash2()						-- Selected flash drive 2 (Bartender)
		player_ogg.s_stop()
		player_ogg.set_show_flash(2)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash3()						-- Selected flash drive 3 (Debt)
		player_ogg.s_stop()
		player_ogg.set_show_flash(3)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash4()						-- Selected flash drive 4 (Freedom)
		player_ogg.s_stop()
		player_ogg.set_show_flash(4)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash5()						-- Selected fleshka 5 (Bandit)
		player_ogg.s_stop()
		player_ogg.set_show_flash(5)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash6()						-- Selected fleshka 6 (Syaka)
		player_ogg.s_stop()
		player_ogg.set_show_flash(6)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash7()						-- Selected flash drive 7
		player_ogg.s_stop()
		player_ogg.set_show_flash(7)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash8()						-- Selected flash drive 8
		player_ogg.s_stop()
		player_ogg.set_show_flash(8)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash9()						-- Selected flash drive 9
		player_ogg.s_stop()
		player_ogg.set_show_flash(9)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash10()						-- Selected flash drive 10
		player_ogg.s_stop()
		player_ogg.set_show_flash(10)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash11()						-- Selected flash drive 11
		player_ogg.s_stop()
		player_ogg.set_show_flash(11)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash12()						-- Selected flash drive 12
		player_ogg.s_stop()
		player_ogg.set_show_flash(12)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash13()						-- Selected flash drive 13
		player_ogg.s_stop()
		player_ogg.set_show_flash(13)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash14()						-- Selected flash drive 14
		player_ogg.s_stop()
		player_ogg.set_show_flash(14)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash15()						-- Selected flash drive 15
		player_ogg.s_stop()
		player_ogg.set_show_flash(15)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:flash16()						-- Selected flash drive 16
		player_ogg.s_stop()
		player_ogg.set_show_flash(16)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:cheat01()					-- No Files
		player_ogg.s_play(0)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:btn_stop()					-- Button Off
		player_ogg.ring_set(0)
		player_ogg.s_stop()
		player_ogg.set_play_flag(2)
		player_ogg.set_show_flash(nil)
		play_menu = true				-- The player spawns in a bag
		self:on_quit()
end

function cheat:btn_quit()					-- Button to remove the player
		player_ogg.set_play_flag(2)
		play_menu = true				-- The player spawns in a bag
		self:on_quit()
end

function cheat:cheat1() 					-- Radio Debt
		player_ogg.s_play(13)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:cheat2()						-- Radio Liberty
		player_ogg.s_play(14)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:cheat3()						-- Radio Stalkers
		player_ogg.s_play(15)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:cheat4()						-- Military Radio
		player_ogg.s_play(16)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:cheat5()						-- General Radio wave
		player_ogg.s_play(17)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:cheat6()						-- Radio Monolith
		player_ogg.s_play(18)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

function cheat:cheat7()						-- car radio
		player_ogg.s_play(19)
		player_ogg.set_play_flag(1)
		play_menu = false	
		self:on_quit()
end

-- First of all slot flash drives
function cheat:cheat_t1()					-- Track 1
	local prefix = player_ogg.work_flash_return()
	if prefix == null then
		return
	end
	player_ogg.s_play(1)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

-- The second slot of all flash drives
function cheat:cheat_t2()					-- Track 2
	player_ogg.s_play(2)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

-- The third slot all flash drives
function cheat:cheat_t3()					-- Track 3
	player_ogg.s_play(3)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

-- The fourth slot is all flash drives
function cheat:cheat_t4()					-- Track 4
	player_ogg.s_play(4)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

-- The fifth slot is all flash drives
function cheat:cheat_t5()					-- Track 5
	player_ogg.s_play(5)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

-- The sixth slot is all flash drives
function cheat:cheat_t6()					-- Track 6
	player_ogg.s_play(6)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

-- The seventh slot, all flash drives
function cheat:cheat_t7()					-- Track 7
	player_ogg.s_play(7)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

-- Eighth slot, all flash drives
function cheat:cheat_t8()					-- Track 8
	player_ogg.s_play(8)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end 

--The ninth slot all flash drives
function cheat:cheat_t9()					-- Track 9
	player_ogg.s_play(9)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

--Tenth of all slot flash drives
function cheat:cheat_t10()					-- Track 10
	player_ogg.s_play(10)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

--Eleventh slot is all flash drives
function cheat:cheat_t11()					-- Track 11
	player_ogg.s_play(11)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

--Twelfth slot of all flash drives
function cheat:cheat_t12()					-- Track 12
	player_ogg.s_play(12)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

--The first volume
function cheat:cheat_vol_1()					
	player_ogg.sound_vol_set(1)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

--The second volume
function cheat:cheat_vol_2()					
	player_ogg.sound_vol_set(2)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

--The third volume
function cheat:cheat_vol_3()					
	player_ogg.sound_vol_set(3)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

--The fourth volume
function cheat:cheat_vol_4()					
	player_ogg.sound_vol_set(4)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

--The fifth volume
function cheat:cheat_vol_5()					
	player_ogg.sound_vol_set(5)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

-- Turn on / off zakoltsovki
function cheat:cheat_ring()					
	if player_ogg.ring_return() == 0 then
		player_ogg.ring_set(1)
	else
		player_ogg.ring_set(0)
	end
	--player_ogg.work_trek_set(0)
	player_ogg.set_play_flag(1)
	play_menu = false	
	self:on_quit()
end

function cheat:check_game()
	-- returns true if the running game
	local check = false
	if level.present() and (db.actor ~= nil) and db.actor:alive() then
		check = true
	end
	return check
end

function cheat:on_quit()
	self:GetHolder():start_stop_menu (self,true)
	if play_menu == true then
		amk.spawn_item_in_inv("player")
--		player_ogg.spawn_item_in_inv("player")
	end
end

